export const INVENTORY_ACCURACY_DAILY = 'DAILY';
export const INVENTORY_ACCURACY_HOURLY = 'HOURLY';

export const BOOKING_TYPE_DAILY = 'DAILY';
export const BOOKING_TYPE_HOURLY = 'HOURLY';

export const BOOKING_STATUS_REVIEWED = 'REVIEWED';
export const BOOKING_STATUS_NOT_REVIEWED = 'NOT_REVIEWED';
export const BOOKING_STATUS_IGNORED = 'IGNORED';
export const BOOKING_STATUS_AUTO_REVIEWED = 'AUTO_REVIEWED';

export const CHANNEL_LOG_STATUS_PROCESSING = 'PROCESSING'
export const CHANNEL_LOG_STATUS_PENDING = 'PENDING'
export const CHANNEL_LOG_STATUS_SUCCESS = 'SUCCESS'
export const CHANNEL_LOG_STATUS_FAILED = 'FAILED'
export const CHANNEL_LOG_STATUS_EXPIRED = 'EXPIRED'
export const CHANNEL_LOG_STATUS_UNKNOWN = 'UNKNOWN'

export const CHANNEL_LOG_SETTINGS_ACTIVE = 'ACTIVE'
export const CHANNEL_LOG_SETTINGS_INACTIVE = 'INACTIVE'

export const BE_GROUP_STATUS_ACTIVE = 'ACTIVE'
export const BE_GROUP_STATUS_INACTIVE = 'INACTIVE'

export const BE_GROUP_PROPERTY_STATUS_ACTIVE = 'ACTIVE'
export const BE_GROUP_PROPERTY_STATUS_INACTIVE = 'INACTIVE'

export const EXTRANET_USER_GRANT_ACCESS = 'GRANT_ACCESS'
export const EXTRANET_USER_REVOKE_ACCESS = 'REVOKE_ACCESS'

export const CHANNEL_ID_RESAVENUE = 'RESAVENUE'
export const CHANNEL_ID_GOOGLE_HOTEL_CENTER = 'GOOGLE_HOTEL_CENTER'
export const CHANNEL_ID_INTERNAL = 'INTERNAL'

export const AGE_CODE_ADULT = 'A';
export const AGE_CODE_CHILD = 'C';
export const AGE_CODE_INFANT = 'I';

export const EARLY_CHECKIN_STATUS_ALLOWED = 'ALLOWED';
export const EARLY_CHECKIN_STATUS_NOT_ALLOWED = 'NOT_ALLOWED';
export const EARLY_CHECKIN_STATUS_AS_PER_AVAILABILITY = 'AS_PER_AVAILABILITY';

export const LATE_CHECKOUT_STATUS_ALLOWED = 'ALLOWED';
export const LATE_CHECKOUT_STATUS_NOT_ALLOWED = 'NOT_ALLOWED';
export const LATE_CHECKOUT_STATUS_AS_PER_AVAILABILITY = 'AS_PER_AVAILABILITY';

export const PAYMENT_GATEWAY_RAZORPAY = 'RAZORPAY';
export const PAYMENT_GATEWAY_CASHFREE = 'CASHFREE';
export const PAYMENT_SERVICE_PROVIDER_RAZORPAY = 'RAZORPAY';

export const BOOKING_SCHEME_DAILY = 'DAILY';
export const BOOKING_SCHEME_HOURLY = 'HOURLY';

export const BOOKING_STATUS_CONFIRMED = 'CONFIRMED';
export const BOOKING_STATUS_CANCELLED = 'CANCELLED';
export const BOOKING_STATUS_ATTEMPT = 'ATTEMPT';
export const BOOKING_STATUS_MODIFIED = 'MODIFIED';
export const BOOKING_STATUS_FAILED = 'FAILED';
export const BOOKING_STATUS_INTERNAL_ERROR = 'INTERNAL_ERROR';
export const BOOKING_STATUS_EXPIRED = 'EXPIRED';

export const PAYMENT_DETAILS_SERVICE_PROVIDER_RAZORPAY = 'RAZORPAY';

export const BOOKING_PAYMENT_STATUS_PAID = 'PAID';
export const BOOKING_PAYMENT_STATUS_PENDING = 'PENDING';
export const BOOKING_PAYMENT_STATUS_FAILED = 'FAILED';
export const BOOKING_PAYMENT_STATUS_INTERNAL_ERROR = 'INTERNAL_ERROR';

export const PAYMENT_TRANSACTION_STATUS_CREATED = 'CREATED';
export const PAYMENT_TRANSACTION_STATUS_AUTHORIZED = 'AUTHORIZED';
export const PAYMENT_TRANSACTION_STATUS_CAPTURED = 'CAPTURED';
export const PAYMENT_TRANSACTION_STATUS_FAILED = 'FAILED'; //be
export const PAYMENT_TRANSACTION_STATUS_REFUNDED = 'REFUNDED';

export const CHANNEL_PUSH_BOOKING_LOG_STATUS_PROCESSING = 'PROCESSING';
export const CHANNEL_PUSH_BOOKING_LOG_STATUS_SUCCESS = 'SUCCESS';
export const CHANNEL_PUSH_BOOKING_LOG_STATUS_PENDING = 'PENDING';
export const CHANNEL_PUSH_BOOKING_LOG_STATUS_FAILED = 'FAILED';

export const BOOKING_REFUND_TO_TYPE_SOURCE_ACCOUNT = 'SOURCE_ACCOUNT';
export const BOOKING_REFUND_TO_TYPE_OTHER = 'OTHER';
export const BOOKING_REFUND_STATUS_PENDING = 'PENDING';
export const BOOKING_REFUND_STATUS_INITIATED = 'INITIATED';
export const BOOKING_REFUND_STATUS_COMPLETED = 'COMPLETED';

export const API_RESPONSE_STATUS_SUCCESS = 'SUCCESS'
export const API_RESPONSE_STATUS_ERROR = 'ERROR'

export const RESPONSE_STATUS_TYPE_SUCCESS = 'SUCCESS'
export const RESPONSE_STATUS_TYPE_INFO = 'INFO'
export const RESPONSE_STATUS_TYPE_WARNING = 'WARNING'
export const RESPONSE_STATUS_TYPE_ERROR = 'ERROR'

export const GUEST_STATUS_ACTIVE = 'ACTIVE';
export const GUEST_STATUS_BLOCKED = 'BLOCKED';

export const CHANNEL_ID_RMS_REST_API = 'RMS_REST_API'
export const CHANNEL_ID_RESAVENUE_CM_API = 'RESAVENUE_CM_API'
export const CHANNEL_ID_GOOGLE_PLACES_API = 'GOOGLE_PLACES_API'
export const CHANNEL_ID_RATE_GAIN_DEMAND_AI = 'RATE_GAIN_DEMAND_AI'

export const SPACE_RESTRICTION_TYPE_OPEN = 'OPEN'
export const SPACE_RESTRICTION_TYPE_CLOSE = 'CLOSE'
export const SPACE_RESTRICTION_TYPE_PARTIAL = 'PARTIAL'

export const BOOKING_SETUP_STATUS_ACTIVE = 'ACTIVE';
export const BOOKING_SETUP_STATUS_DISABLED = 'DISABLED';
export const BOOKING_SETUP_STATUS_ONBOARDING = 'ONBOARDING';

export const BOOKING_SETUP_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
export const BOOKING_SETUP_ONBOARDING_STATUS_REJECTED = 'REJECTED';
export const BOOKING_SETUP_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const BOOKING_SETUP_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

export const PROMOTION_CATEGORY_PROMOTION = 'PROMOTION';
export const PROMOTION_CATEGORY_PROMO_CODE = 'PROMO_CODE';

export const PROMOTION_STATUS_ACTIVE = 'ACTIVE';
export const PROMOTION_STATUS_INACTIVE = 'INACTIVE';
export const PROMOTION_STATUS_EXPIRED = 'EXPIRED';

export const PROMOTION_TYPE_BASIC = 'BASIC';
export const PROMOTION_TYPE_EARLY_BIRD = 'EARLY_BIRD';
export const PROMOTION_TYPE_LAST_MINUTE = 'LAST_MINUTE';

export const BOOKING_SOURCE_ID_EXTRANET = 'EXTRANET';
export const BOOKING_SOURCE_ID_CHANNEL = 'CHANNEL';
export const BOOKING_SOURCE_ID_BOOKING_BLOCK = 'BOOKING_BLOCK';
export const BOOKING_SOURCE_ID_BOOKING_UNBLOCK = 'BOOKING_UNBLOCK';

export const BOOKING_MARKET_SOURCE_B2C = 'B2C';
export const BOOKING_MARKET_SOURCE_B2B = 'B2B';
export const BOOKING_MARKET_SOURCE_CORP = 'CORP';

export const SENTIMENTAL_POLARITY_TYPE_POSITIVE = "POSITIVE";
export const SENTIMENTAL_POLARITY_TYPE_NEGATIVE = "NEGATIVE";
export const SENTIMENTAL_POLARITY_TYPE_NEUTRAL = "NEUTRAL";

export const REVIEWER_TYPE_GUEST = "GUEST";
export const REVIEWER_TYPE_MANAGEMENT = "MANAGEMENT";
export const REVIEWER_TYPE_UNKNOWN = "UNKNOWN";
export const  PAYMENT_GATEWAY_AIRPAY='AIRPAY';
export const  PAYMENT_GATEWAY_PAYU='PAYU';

export const CHANNEL_LOGS_PROVIDE_BOOKING_SECTION = 'PROVIDE_BOOKING_SECTION';
export const CHANNEL_LOGS_PROVIDE_INVENTORY_DETAILS_SECTION = 'PROVIDE_INVENTORY_DETAILS_SECTION';
export const CHANNEL_LOGS_PROVIDE_PROPERTY_DETAILS_SECTION = 'PROVIDE_PROPERTY_DETAILS_SECTION';
export const CHANNEL_LOGS_PROVIDE_RATE_DETAILS_SECTION = 'PROVIDE_RATE_DETAILS_SECTION';

export const CHANNEL_LOGS_PUSH_AVAILABILITY_SECTION = 'PUSH_AVAILABILITY_SECTION';
export const CHANNEL_LOGS_PUSH_BOOKING_SECTION = 'PUSH_BOOKING_SECTION';
export const CHANNEL_LOGS_PUSH_INVENTORY_SECTION = 'PUSH_INVENTORY_SECTION';
export const CHANNEL_LOGS_PUSH_PROMOTION_DETAILS_SECTION = 'PUSH_PROMOTION_DETAILS_SECTION';
export const CHANNEL_LOGS_PUSH_PROPERTY_SECTION = 'PUSH_PROPERTY_SECTION';
export const CHANNEL_LOGS_PUSH_PROPERTY_TAX_SECTION = 'PUSH_PROPERTY_TAX_SECTION';
export const CHANNEL_LOGS_PUSH_RATE_SECTION = 'PUSH_RATE_SECTION';

export const CHANNEL_LOGS_UPDATE_AVAILABILITY_SECTION = 'UPDATE_AVAILABILITY_SECTION';
export const CHANNEL_LOGS_UPDATE_INVENTORY_SECTION = 'UPDATE_INVENTORY_SECTION';
export const CHANNEL_LOGS_UPDATE_RATE_SECTION = 'UPDATE_RATE_SECTION';
export const BE_API_LOGS_STATUS_PENDING = 'PENDING';
export const BE_API_LOGS_STATUS_SUCCESS = 'SUCCESS';
export const BE_API_LOGS_STATUS_FAILED = 'FAILED';
export const BE_API_LOGS_STATUS_UNKNOWN = 'UNKNOWN';

export const RMS_REST_API = 'RMS_REST_API';
export const WINCLOUD_PMS = 'WINCLOUD_PMS';
export const HOTELOGIX_CM = 'HOTELOGIX_CM';
export const RESAVENUE ='RESAVENUE';

export const  LOG_LEVEL_EMERGENCY = 'EMERGENCY';
export const  LOG_LEVEL_ALERT = 'ALERT';
export const  LOG_LEVEL_CRITICAL = 'CRITICAL';
export const  LOG_LEVEL_ERROR = 'ERROR';
export const  LOG_LEVEL_WARNING = 'WARNING';
export const  LOG_LEVEL_NOTICE = 'NOTICE';
export const  LOG_LEVEL_INFO = 'INFO';
export const  LOG_LEVEL_DEBUG = 'DEBUG';

export const  CHANNEL_RATE_PUSH = 'CHANNEL_RATE_PUSH';
export const  CHANNEL_INVENTORY_PUSH = 'CHANNEL_INVENTORY_PUSH';
export const  CHANNEL_AVAILABILITY_PUSH = 'CHANNEL_AVAILABILITY_PUSH';
export const  CHANNEL_PUSH_PROPERTY_CONTENT = 'CHANNEL_PUSH_PROPERTY_CONTENT';
export const  CHANNEL_PUSH_BOOKING = 'CHANNEL_PUSH_BOOKING';
export const  CHANNEL_PUSH_PROMOTIONS = 'CHANNEL_PUSH_PROMOTIONS';
export const  CHANNEL_PUSH_TAX_AND_CHARGES = 'CHANNEL_PUSH_TAX_AND_CHARGES';

export const COMMAND_STATUS_IN_PROGRESS = 'IN_PROGRESS'
export const COMMAND_STATUS_SUCCESS = 'SUCCESS'
export const COMMAND_STATUS_FAILURE = 'FAILURE'
export const COMMAND_STATUS_ABORTED = 'ABORTED'

export const COMMAND_PROCESS_STATUS_RUNNING = 'RUNNING'
export const COMMAND_PROCESS_STATUS_STOPPED = 'STOPPED'

