export const INVENTORY_ACCURACY_DAILY = 'DAILY';
export const INVENTORY_ACCURACY_HOURLY = 'HOURLY';

export const BOOKING_TYPE_DAILY = 'DAILY';
export const BOOKING_TYPE_HOURLY = 'HOURLY';

export const AGE_CODE_ADULT = 'A';
export const AGE_CODE_CHILD = 'C';
export const AGE_CODE_INFANT = 'I';

export const EARLY_CHECKIN_STATUS_ALLOWED = 'ALLOWED';
export const EARLY_CHECKIN_STATUS_NOT_ALLOWED = 'NOT_ALLOWED';
export const EARLY_CHECKIN_STATUS_AS_PER_AVAILABILITY = 'AS_PER_AVAILABILITY';

export const LATE_CHECKOUT_STATUS_ALLOWED = 'ALLOWED';
export const LATE_CHECKOUT_STATUS_NOT_ALLOWED = 'NOT_ALLOWED';
export const LATE_CHECKOUT_STATUS_AS_PER_AVAILABILITY = 'AS_PER_AVAILABILITY';

export const PAYMENT_GATEWAY_RAZORPAY = 'RAZORPAY';
export const PAYMENT_GATEWAY_CASHFREE = 'CASHFREE';
export const PAYMENT_SERVICE_PROVIDER_RAZORPAY = 'RAZORPAY';

export const BOOKING_SCHEME_DAILY = 'DAILY';
export const BOOKING_SCHEME_HOURLY = 'HOURLY';

export const BOOKING_STATUS_CONFIRMED = 'CONFIRMED';
export const BOOKING_STATUS_CANCELLED = 'CANCELLED';
export const BOOKING_STATUS_ATTEMPT = 'ATTEMPT';
export const BOOKING_STATUS_MODIFIED = 'MODIFIED';
export const BOOKING_STATUS_FAILED = 'FAILED';
export const BOOKING_STATUS_INTERNAL_ERROR = 'INTERNAL_ERROR';

export const PAYMENT_DETAILS_SERVICE_PROVIDER_RAZORPAY = 'RAZORPAY';

export const BOOKING_PAYMENT_STATUS_PAID = 'PAID';
export const BOOKING_PAYMENT_STATUS_PENDING = 'PENDING';
export const BOOKING_PAYMENT_STATUS_FAILED = 'FAILED';
export const BOOKING_PAYMENT_STATUS_INTERNAL_ERROR = 'INTERNAL_ERROR';

export const PAYMENT_TRANSACTION_STATUS_CREATED = 'CREATED';
export const PAYMENT_TRANSACTION_STATUS_AUTHORIZED = 'AUTHORIZED';
export const PAYMENT_TRANSACTION_STATUS_CAPTURED = 'CAPTURED';
export const PAYMENT_TRANSACTION_STATUS_FAILED = 'FAILED'; //be
export const PAYMENT_TRANSACTION_STATUS_REFUNDED = 'REFUNDED';

export const CHANNEL_PUSH_BOOKING_LOG_STATUS_PROCESSING = 'PROCESSING';
export const CHANNEL_PUSH_BOOKING_LOG_STATUS_SUCCESS = 'SUCCESS';
export const CHANNEL_PUSH_BOOKING_LOG_STATUS_PENDING = 'PENDING';
export const CHANNEL_PUSH_BOOKING_LOG_STATUS_FAILED = 'FAILED';

export const BOOKING_REFUND_TO_TYPE_SOURCE_ACCOUNT = 'SOURCE_ACCOUNT';
export const BOOKING_REFUND_TO_TYPE_OTHER = 'OTHER';
export const BOOKING_REFUND_STATUS_PENDING = 'PENDING';
export const BOOKING_REFUND_STATUS_INITIATED = 'INITIATED';
export const BOOKING_REFUND_STATUS_COMPLETED = 'COMPLETED';

export const API_RESPONSE_STATUS_SUCCESS = 'SUCCESS'
export const API_RESPONSE_STATUS_ERROR = 'ERROR'

export const RESPONSE_STATUS_TYPE_SUCCESS = 'SUCCESS'
export const RESPONSE_STATUS_TYPE_INFO = 'INFO'
export const RESPONSE_STATUS_TYPE_WARNING = 'WARNING'
export const RESPONSE_STATUS_TYPE_ERROR = 'ERROR'

export const GUEST_STATUS_ACTIVE = 'ACTIVE';
export const GUEST_STATUS_BLOCKED = 'BLOCKED';

export const CHANNEL_ID_RMS_REST_API = 'RMS_REST_API'
export const CHANNEL_ID_RESAVENUE_CM_API = 'RESAVENUE_CM_API'
export const CHANNEL_ID_GOOGLE_PLACES_API = 'GOOGLE_PLACES_API'
export const CHANNEL_ID_RATE_GAIN_DEMAND_AI = 'RATE_GAIN_DEMAND_AI'