module.exports.INVENTORY_ACCURACY_DAILY = 'DAILY';
module.exports.INVENTORY_ACCURACY_HOURLY = 'HOURLY';

module.exports.BOOKING_TYPE_DAILY = 'DAILY';
module.exports.BOOKING_TYPE_HOURLY = 'HOURLY';

module.exports.BOOKING_STATUS_REVIEWED = 'REVIEWED';
module.exports.BOOKING_STATUS_NOT_REVIEWED = 'NOT_REVIEWED';
module.exports.BOOKING_STATUS_IGNORED = 'IGNORED';
module.exports.BOOKING_STATUS_AUTO_REVIEWED = 'AUTO_REVIEWED';

module.exports.CHANNEL_LOG_STATUS_PROCESSING = 'PROCESSING'
module.exports.CHANNEL_LOG_STATUS_PENDING = 'PENDING'
module.exports.CHANNEL_LOG_STATUS_SUCCESS = 'SUCCESS'
module.exports.CHANNEL_LOG_STATUS_FAILED = 'FAILED'
module.exports.CHANNEL_LOG_STATUS_EXPIRED = 'EXPIRED'
module.exports.CHANNEL_LOG_STATUS_UNKNOWN = 'UNKNOWN'

module.exports.CHANNEL_LOG_SETTINGS_ACTIVE = 'ACTIVE'
module.exports.CHANNEL_LOG_SETTINGS_INACTIVE = 'INACTIVE'

module.exports.BE_GROUP_STATUS_ACTIVE = 'ACTIVE'
module.exports.BE_GROUP_STATUS_INACTIVE = 'INACTIVE'

module.exports.BE_GROUP_PROPERTY_STATUS_ACTIVE = 'ACTIVE'
module.exports.BE_GROUP_PROPERTY_STATUS_INACTIVE = 'INACTIVE'

module.exports.EXTRANET_USER_GRANT_ACCESS = 'GRANT_ACCESS'
module.exports.EXTRANET_USER_REVOKE_ACCESS = 'REVOKE_ACCESS'

module.exports.CHANNEL_ID_RESAVENUE = 'RESAVENUE'
module.exports.CHANNEL_ID_GOOGLE_HOTEL_CENTER = 'GOOGLE_HOTEL_CENTER'
module.exports.CHANNEL_ID_INTERNAL = 'INTERNAL'
module.exports.SYSOTEL_IBE_OPEN_API = 'SYSOTEL_IBE_OPEN_API';

module.exports.AGE_CODE_ADULT = 'A';
module.exports.AGE_CODE_CHILD = 'C';
module.exports.AGE_CODE_INFANT = 'I';

module.exports.EARLY_CHECKIN_STATUS_ALLOWED = 'ALLOWED';
module.exports.EARLY_CHECKIN_STATUS_NOT_ALLOWED = 'NOT_ALLOWED';
module.exports.EARLY_CHECKIN_STATUS_AS_PER_AVAILABILITY = 'AS_PER_AVAILABILITY';

module.exports.LATE_CHECKOUT_STATUS_ALLOWED = 'ALLOWED';
module.exports.LATE_CHECKOUT_STATUS_NOT_ALLOWED = 'NOT_ALLOWED';
module.exports.LATE_CHECKOUT_STATUS_AS_PER_AVAILABILITY = 'AS_PER_AVAILABILITY';

module.exports.PAYMENT_GATEWAY_RAZORPAY = 'RAZORPAY';
module.exports.PAYMENT_GATEWAY_CASHFREE = 'CASHFREE';
module.exports.PAYMENT_SERVICE_PROVIDER_RAZORPAY = 'RAZORPAY';
module.exports.PAYMENT_SERVICE_PROVIDER_PAYU = 'PAYU';

module.exports.BOOKING_SCHEME_DAILY = 'DAILY';
module.exports.BOOKING_SCHEME_HOURLY = 'HOURLY';

module.exports.BOOKING_STATUS_CONFIRMED = 'CONFIRMED';
module.exports.BOOKING_STATUS_CANCELLED = 'CANCELLED';
module.exports.BOOKING_STATUS_ATTEMPT = 'ATTEMPT';
module.exports.BOOKING_STATUS_MODIFIED = 'MODIFIED';
module.exports.BOOKING_STATUS_FAILED = 'FAILED';
module.exports.BOOKING_STATUS_INTERNAL_ERROR = 'INTERNAL_ERROR';
module.exports.BOOKING_STATUS_EXPIRED = 'EXPIRED';

module.exports.PAYMENT_DETAILS_SERVICE_PROVIDER_RAZORPAY = 'RAZORPAY';

module.exports.BOOKING_PAYMENT_STATUS_PAID = 'PAID';
module.exports.BOOKING_PAYMENT_STATUS_PENDING = 'PENDING';
module.exports.BOOKING_PAYMENT_STATUS_FAILED = 'FAILED';
module.exports.BOOKING_PAYMENT_STATUS_INTERNAL_ERROR = 'INTERNAL_ERROR';

module.exports.PAYMENT_TRANSACTION_STATUS_CREATED = 'CREATED';
module.exports.PAYMENT_TRANSACTION_STATUS_AUTHORIZED = 'AUTHORIZED';
module.exports.PAYMENT_TRANSACTION_STATUS_CAPTURED = 'CAPTURED';
module.exports.PAYMENT_TRANSACTION_STATUS_FAILED = 'FAILED'; //be
module.exports.PAYMENT_TRANSACTION_STATUS_REFUNDED = 'REFUNDED';

module.exports.CHANNEL_PUSH_BOOKING_LOG_STATUS_PROCESSING = 'PROCESSING';
module.exports.CHANNEL_PUSH_BOOKING_LOG_STATUS_SUCCESS = 'SUCCESS';
module.exports.CHANNEL_PUSH_BOOKING_LOG_STATUS_PENDING = 'PENDING';
module.exports.CHANNEL_PUSH_BOOKING_LOG_STATUS_FAILED = 'FAILED';

module.exports.BOOKING_REFUND_TO_TYPE_SOURCE_ACCOUNT = 'SOURCE_ACCOUNT';
module.exports.BOOKING_REFUND_TO_TYPE_OTHER = 'OTHER';
module.exports.BOOKING_REFUND_STATUS_PENDING = 'PENDING';
module.exports.BOOKING_REFUND_STATUS_INITIATED = 'INITIATED';
module.exports.BOOKING_REFUND_STATUS_COMPLETED = 'COMPLETED';

module.exports.API_RESPONSE_STATUS_SUCCESS = 'SUCCESS'
module.exports.API_RESPONSE_STATUS_ERROR = 'ERROR'

module.exports.RESPONSE_STATUS_TYPE_SUCCESS = 'SUCCESS'
module.exports.RESPONSE_STATUS_TYPE_INFO = 'INFO'
module.exports.RESPONSE_STATUS_TYPE_WARNING = 'WARNING'
module.exports.RESPONSE_STATUS_TYPE_ERROR = 'ERROR'

module.exports.GUEST_STATUS_ACTIVE = 'ACTIVE';
module.exports.GUEST_STATUS_BLOCKED = 'BLOCKED';

module.exports.RMS_CHANNEL_API = 'RMS_CHANNEL_API'
module.exports.CHANNEL_ID_RMS_REST_API = 'RMS_REST_API'
module.exports.CHANNEL_ID_RESAVENUE_CM_API = 'RESAVENUE_CM_API'
module.exports.CHANNEL_ID_GOOGLE_PLACES_API = 'GOOGLE_PLACES_API'
module.exports.CHANNEL_ID_RATE_GAIN_DEMAND_AI = 'RATE_GAIN_DEMAND_AI'

module.exports.SPACE_RESTRICTION_TYPE_OPEN = 'OPEN'
module.exports.SPACE_RESTRICTION_TYPE_CLOSE = 'CLOSE'
module.exports.SPACE_RESTRICTION_TYPE_PARTIAL = 'PARTIAL'

module.exports.BOOKING_SETUP_STATUS_ACTIVE = 'ACTIVE';
module.exports.BOOKING_SETUP_STATUS_DISABLED = 'DISABLED';
module.exports.BOOKING_SETUP_STATUS_ONBOARDING = 'ONBOARDING';

module.exports.BOOKING_SETUP_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
module.exports.BOOKING_SETUP_ONBOARDING_STATUS_REJECTED = 'REJECTED';
module.exports.BOOKING_SETUP_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
module.exports.BOOKING_SETUP_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

module.exports.PROMOTION_CATEGORY_PROMOTION = 'PROMOTION';
module.exports.PROMOTION_CATEGORY_PROMO_CODE = 'PROMO_CODE';

module.exports.PROMOTION_STATUS_ACTIVE = 'ACTIVE';
module.exports.PROMOTION_STATUS_INACTIVE = 'INACTIVE';
module.exports.PROMOTION_STATUS_EXPIRED = 'EXPIRED';

module.exports.PROMOTION_TYPE_BASIC = 'BASIC';
module.exports.PROMOTION_TYPE_EARLY_BIRD = 'EARLY_BIRD';
module.exports.PROMOTION_TYPE_LAST_MINUTE = 'LAST_MINUTE';

module.exports.BOOKING_SOURCE_ID_EXTRANET = 'EXTRANET';
module.exports.BOOKING_SOURCE_ID_CHANNEL = 'CHANNEL';
module.exports.BOOKING_SOURCE_ID_BOOKING_BLOCK = 'BOOKING_BLOCK';
module.exports.BOOKING_SOURCE_ID_BOOKING_UNBLOCK = 'BOOKING_UNBLOCK';

module.exports.BOOKING_MARKET_SOURCE_B2C = 'B2C';
module.exports.BOOKING_MARKET_SOURCE_B2B = 'B2B';
module.exports.BOOKING_MARKET_SOURCE_CORP = 'CORP';

module.exports.SENTIMENTAL_POLARITY_TYPE_POSITIVE = "POSITIVE";
module.exports.SENTIMENTAL_POLARITY_TYPE_NEGATIVE = "NEGATIVE";
module.exports.SENTIMENTAL_POLARITY_TYPE_NEUTRAL = "NEUTRAL";

module.exports.REVIEWER_TYPE_GUEST = "GUEST";
module.exports.REVIEWER_TYPE_MANAGEMENT = "MANAGEMENT";
module.exports.REVIEWER_TYPE_UNKNOWN = "UNKNOWN";
module.exports.PAYMENT_GATEWAY_AIRPAY = 'AIRPAY';
module.exports.PAYMENT_GATEWAY_PAYU = 'PAYU';

module.exports.CHANNEL_LOGS_PROVIDE_BOOKING_SECTION = 'PROVIDE_BOOKING_SECTION';
module.exports.CHANNEL_LOGS_PROVIDE_INVENTORY_DETAILS_SECTION = 'PROVIDE_INVENTORY_DETAILS_SECTION';
module.exports.CHANNEL_LOGS_PROVIDE_PROPERTY_DETAILS_SECTION = 'PROVIDE_PROPERTY_DETAILS_SECTION';
module.exports.CHANNEL_LOGS_PROVIDE_RATE_DETAILS_SECTION = 'PROVIDE_RATE_DETAILS_SECTION';

module.exports.CHANNEL_LOGS_PUSH_AVAILABILITY_SECTION = 'PUSH_AVAILABILITY_SECTION';
module.exports.CHANNEL_LOGS_PUSH_BOOKING_SECTION = 'PUSH_BOOKING_SECTION';
module.exports.CHANNEL_LOGS_PUSH_INVENTORY_SECTION = 'PUSH_INVENTORY_SECTION';
module.exports.CHANNEL_LOGS_PUSH_PROMOTION_DETAILS_SECTION = 'PUSH_PROMOTION_DETAILS_SECTION';
module.exports.CHANNEL_LOGS_PUSH_PROPERTY_SECTION = 'PUSH_PROPERTY_SECTION';
module.exports.CHANNEL_LOGS_PUSH_PROPERTY_TAX_SECTION = 'PUSH_PROPERTY_TAX_SECTION';
module.exports.CHANNEL_LOGS_PUSH_RATE_SECTION = 'PUSH_RATE_SECTION';

module.exports.CHANNEL_LOGS_UPDATE_AVAILABILITY_SECTION = 'UPDATE_AVAILABILITY_SECTION';
module.exports.CHANNEL_LOGS_UPDATE_INVENTORY_SECTION = 'UPDATE_INVENTORY_SECTION';
module.exports.CHANNEL_LOGS_UPDATE_RATE_SECTION = 'UPDATE_RATE_SECTION';
module.exports.BE_API_LOGS_STATUS_PENDING = 'PENDING';
module.exports.BE_API_LOGS_STATUS_SUCCESS = 'SUCCESS';
module.exports.BE_API_LOGS_STATUS_FAILED = 'FAILED';
module.exports.BE_API_LOGS_STATUS_UNKNOWN = 'UNKNOWN';

module.exports.RMS_REST_API = 'RMS_REST_API';
module.exports.MAXIMOJO_CM = 'MAXIMOJO_CM';
module.exports.WINCLOUD_PMS = 'WINCLOUD_PMS';
module.exports.HOTELOGIX_CM = 'HOTELOGIX_CM';
module.exports.RESAVENUE = 'RESAVENUE';
module.exports.IDS_NEXT = 'IDS_NEXT';
module.exports.CHANNEL_MANAGER_EASEROOMS = 'EASEROOMS';

module.exports.LOG_LEVEL_EMERGENCY = 'EMERGENCY';
module.exports.LOG_LEVEL_ALERT = 'ALERT';
module.exports.LOG_LEVEL_CRITICAL = 'CRITICAL';
module.exports.LOG_LEVEL_ERROR = 'ERROR';
module.exports.LOG_LEVEL_WARNING = 'WARNING';
module.exports.LOG_LEVEL_NOTICE = 'NOTICE';
module.exports.LOG_LEVEL_INFO = 'INFO';
module.exports.LOG_LEVEL_DEBUG = 'DEBUG';

module.exports.CHANNEL_RATE_PUSH = 'CHANNEL_RATE_PUSH';
module.exports.CHANNEL_INVENTORY_PUSH = 'CHANNEL_INVENTORY_PUSH';
module.exports.CHANNEL_AVAILABILITY_PUSH = 'CHANNEL_AVAILABILITY_PUSH';
module.exports.CHANNEL_PUSH_PROPERTY_CONTENT = 'CHANNEL_PUSH_PROPERTY_CONTENT';
module.exports.CHANNEL_PUSH_BOOKING = 'CHANNEL_PUSH_BOOKING';
module.exports.CHANNEL_PUSH_PROMOTIONS = 'CHANNEL_PUSH_PROMOTIONS';
module.exports.CHANNEL_PUSH_TAX_AND_CHARGES = 'CHANNEL_PUSH_TAX_AND_CHARGES';

module.exports.COMMAND_STATUS_IN_PROGRESS = 'IN_PROGRESS';
module.exports.COMMAND_STATUS_SUCCESS = 'SUCCESS';
module.exports.COMMAND_STATUS_FAILURE = 'FAILURE';
module.exports.COMMAND_STATUS_ABORTED = 'ABORTED';

module.exports.COMMAND_PROCESS_STATUS_RUNNING = 'RUNNING';
module.exports.COMMAND_PROCESS_STATUS_STOPPED = 'STOPPED';

module.exports.SYSOTEL_IBE_CHANNEL_API = 'SYSOTEL_IBE_CHANNEL_API';
module.exports.SYSOTEL_CMS_OPEN_API = 'SYSOTEL_CMS_OPEN_API';

module.exports.BE_APP_STATUS_ACTIVE = 'ACTIVE';
module.exports.BE_APP_STATUS_INACTIVE = 'INACTIVE';

module.exports.BE_INVENTORY_CLOSE = 'CLOSE'
module.exports.BE_INVENTORY_OPEN = 'OPEN'
