module.exports.PROPERTY_STATUS_INACTIVE = 'INACTIVE';
module.exports.PROPERTY_STATUS_ACTIVE = 'ACTIVE';

module.exports.SPACE_STATUS_ACTIVE = 'ACTIVE';
module.exports.SPACE_STATUS_INACTIVE = 'INACTIVE';

module.exports.PRODUCT_STATUS_ACTIVE = 'ACTIVE';
module.exports.PRODUCT_STATUS_INACTIVE = 'INACTIVE';

module.exports.AMENITY_TARGET_PROPERTY = 'PROPERTY'
module.exports.AMENITY_TARGET_SPACE = 'SPACE'

module.exports.PROMOTION_TYPE_BASIC = 'BASIC'
module.exports.PROMOTION_TYPE_EARLY_BIRD = 'EARLY_BIRD'
module.exports.PROMOTION_TYPE_LAST_MINUTE = 'LAST_MINUTE'

module.exports.ACCOUNT_TYPE_SELF = "SELF";

module.exports.CURRENCY_INR = "INR";

module.exports.TIMEZONE_ASIA_KOLKATA = 'Asia/Kolkata'

module.exports.DINING_TYPE_RESTAURANT = 'RESTAURANT';
module.exports.DINING_TYPE_CAFE = 'CAFE';
module.exports.DINING_TYPE_BAR = 'BAR';
module.exports.DINING_TYPE_LOUNGE = 'LOUNGE';
module.exports.DINING_TYPE_PUB = 'PUB';
module.exports.DINING_TYPE_BISTRO = 'BISTRO';
module.exports.DINING_TYPE_BUFFET = 'BUFFET';
module.exports.DINING_TYPE_FINE_DINING = 'FINE_DINING';
module.exports.DINING_TYPE_FOOD_COURT = 'FOOD_COURT';
module.exports.DINING_TYPE_DELI = 'DELI';
module.exports.DINING_TYPE_PIZZERIA = 'PIZZERIA';
module.exports.DINING_TYPE_BRASSERIE = 'BRASSERIE';
module.exports.DINING_TYPE_TEA_ROOM = 'TEA_ROOM';
module.exports.DINING_TYPE_GASTROPUB = 'GASTROPUB';
module.exports.DINING_TYPE_GRILL_ROOM = 'GRILL_ROOM';
module.exports.DINING_TYPE_WINE_BAR = 'WINE_BAR';
module.exports.DINING_TYPE_JUICE_BAR_SMOOTHIE_BAR = 'JUICE_BAR_SMOOTHIE_BAR';
module.exports.DINING_TYPE_ICE_CREAM_PARLOR = 'ICE_CREAM_PARLOR';

module.exports.IMAGE_TYPE_LOGO = 'LOGO';
module.exports.IMAGE_TYPE_BANNER = 'BANNER';
module.exports.IMAGE_TYPE_IMAGE = 'IMAGE';

module.exports.BUSINESS_STATUS_OPERATIONAL = 'OPERATIONAL';
module.exports.BUSINESS_STATUS_CLOSED_TEMPORARILY = 'CLOSED_TEMPORARILY';
module.exports.BUSINESS_STATUS_CLOSED_PERMANENTLY = 'CLOSED_PERMANENTLY';

module.exports.JOB_TYPE_CONTRACT_BASE = 'CONTRACT_BASE';
module.exports.JOB_TYPE_FREELANCER = 'FREELANCER';
module.exports.JOB_TYPE_FULL_TIME = 'FULL_TIME';
module.exports.JOB_TYPE_PART_TIME = 'PART_TIME';
module.exports.JOB_TYPE_REMOTE = 'REMOTE';
module.exports.JOB_TYPE_INTERNSHIP = 'INTERNSHIP';
module.exports.JOB_TYPE_ADMINISTRATIVE = 'ADMINISTRATIVE';
module.exports.JOB_TYPE_INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY';
module.exports.JOB_TYPE_SALES_MARKETING = 'SALES_MARKETING';
module.exports.JOB_TYPE_CUSTOMER_SERVICE = 'CUSTOMER_SERVICE';
module.exports.JOB_TYPE_FINANCE_ACCOUNTING = 'FINANCE_ACCOUNTING';
module.exports.JOB_TYPE_HUMAN_RESOURCES = 'HUMAN_RESOURCES';
module.exports.JOB_TYPE_ENGINEERING = 'ENGINEERING';
module.exports.JOB_TYPE_PROJECT_MANAGEMENT = 'PROJECT_MANAGEMENT';
module.exports.JOB_TYPE_CONSULTING = 'CONSULTING';
module.exports.JOB_TYPE_FREELANCE_SELF_EMPLOYED = 'FREELANCE_SELF_EMPLOYED';

module.exports.DOMAIN_TYPE_INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY';
module.exports.DOMAIN_TYPE_SALES_AND_MARKETING = 'SALES_AND_MARKETING';
module.exports.DOMAIN_TYPE_HUMAN_RESOURCES = 'HUMAN_RESOURCES';

module.exports.AUTOMATION_QUEUED_STATUS_QUEUED = "QUEUED"
module.exports.AUTOMATION_QUEUED_STATUS_SUCCESS = "SUCCESS"
module.exports.AUTOMATION_QUEUED_STATUS_FAILED = "FAILED"
module.exports.AUTOMATION_QUEUED_STATUS_ABORTED = "ABORTED"

module.exports.FAQ_CATEGORY_RESERVATION = 'RESERVATION';
module.exports.FAQ_CATEGORY_PRICING_PAYMENT = 'PRICING_PAYMENT';
module.exports.FAQ_CATEGORY_SPACE_TYPE_AMENITIES = 'SPACE_TYPE_AMENITIES';
module.exports.FAQ_CATEGORY_CANCELLATION_AND_CHARGES = 'CANCELLATION_AND_CHARGES';
module.exports.FAQ_CATEGORY_CHECK_IN_CHECK_OUT = 'CHECK_IN_CHECK_OUT';
module.exports.FAQ_CATEGORY_FACILITIES_SERVICES = 'FACILITIES_SERVICES';
module.exports.FAQ_CATEGORY_SPECIAL_REQUEST = 'SPECIAL_REQUEST';
module.exports.FAQ_CATEGORY_LOYALTY_PROGRAM_PROMOTIONS = 'LOYALTY_PROGRAM_PROMOTIONS';
module.exports.FAQ_CATEGORY_SAFETY_SECURITY = 'SAFETY_SECURITY';
module.exports.FAQ_CATEGORY_LOCAL_INFORMATION_RECOMMENDATION = 'LOCAL_INFORMATION_RECOMMENDATION';
module.exports.FAQ_CATEGORY_OTHER = 'OTHER';
