module.exports.PROPERTY_STATUS_INACTIVE = 'INACTIVE';
module.exports.PROPERTY_STATUS_ACTIVE = 'ACTIVE';

module.exports.SPACE_STATUS_ACTIVE = 'ACTIVE';
module.exports.SPACE_STATUS_INACTIVE = 'INACTIVE';

module.exports.PRODUCT_STATUS_ACTIVE = 'ACTIVE';
module.exports.PRODUCT_STATUS_INACTIVE = 'INACTIVE';

module.exports.AMENITY_TARGET_PROPERTY = 'PROPERTY'
module.exports.AMENITY_TARGET_SPACE = 'SPACE'

module.exports.PROMOTION_TYPE_BASIC = 'BASIC'
module.exports.PROMOTION_TYPE_EARLY_BIRD = 'EARLY_BIRD'
module.exports.PROMOTION_TYPE_LAST_MINUTE = 'LAST_MINUTE'

module.exports.ACCOUNT_TYPE_SELF = "SELF";

module.exports.CURRENCY_INR = "INR";

module.exports.TIMEZONE_ASIA_KOLKATA = 'Asia/Kolkata'
