export const CONNECTION_STATUS_ACTIVE = 'ACTIVE'
export const CONNECTION_STATUS_DISABLE = 'DISABLE'

export const API_LOG_STATUS_PENDING = 'PENDING'
export const API_LOG_STATUS_SUCCESS = 'SUCCESS'
export const API_LOG_STATUS_FAILED = 'FAILED'
export const API_LOG_STATUS_UNKNOWN = 'UNKNOWN'