module.exports.PROPERTY_MODULES_BOOKING_ENGINE = 'BE';
module.exports.PROPERTY_MODULES_CHANNEL_MANAGER = "CM";
module.exports.PROPERTY_MODULES_CONTENT_MANAGEMENT_SYSTEM = "CMS";
module.exports.PROPERTY_MODULES_CENTRAL_RESERVATION_SYSTEM = "CRS";
module.exports.PROPERTY_MODULES_YIELD_AUTOMATION_SYSTEM = "IYA";
module.exports.PROPERTY_MODULES_REPUTATION_MANAGER = "RM";
module.exports.PROPERTY_MODULES_RATE_SHOPPER = "RS";

module.exports.ADMIN_SECURITY_PERMISSIONS = 'ADMIN_PERMISSIONS';
module.exports.ADMIN_SECURITY_ROLES = 'ADMIN_ROLES';
module.exports.ADMIN_PERMISSION_READ = 'READ';
module.exports.ADMIN_PERMISSION_WRITE = 'WRITE';
module.exports.ADMIN_PERMISSION_DELETE = 'DELETE';
module.exports.ADMIN_PERMISSION_SPECIAL = 'SPECIAL';
module.exports.ADMIN_PERMISSION_DOWNLOAD = 'DOWNLOAD';
module.exports.ADMIN_PERMISSION_WILDCARD = 'WILDCARD';