export const PROPERTY_MODULES_BOOKING_ENGINE = 'BE';
export const PROPERTY_MODULES_CHANNEL_MANAGER = "CM";
export const PROPERTY_MODULES_CONTENT_MANAGEMENT_SYSTEM = "CMS";
export const PROPERTY_MODULES_CENTRAL_RESERVATION_SYSTEM = "CRS";
export const PROPERTY_MODULES_YIELD_AUTOMATION_SYSTEM = "IYA";
export const PROPERTY_MODULES_REPUTATION_MANAGER = "RM";
export const PROPERTY_MODULES_RATE_SHOPPER = "RS";

export const ADMIN_SECURITY_PERMISSIONS = 'ADMIN_PERMISSIONS';
export const ADMIN_SECURITY_ROLES = 'ADMIN_ROLES';
export const ADMIN_PERMISSION_READ = 'READ';
export const ADMIN_PERMISSION_WRITE = 'WRITE';
export const ADMIN_PERMISSION_DELETE = 'DELETE';
export const ADMIN_PERMISSION_SPECIAL = 'SPECIAL';
export const ADMIN_PERMISSION_DOWNLOAD = 'DOWNLOAD';
export const ADMIN_PERMISSION_WILDCARD = 'WILDCARD';