module.exports.FullAccess = '*';
module.exports.ACCOUNT_FullAccess = 'ACCOUNT.*';
module.exports.ACCOUNT_DescribeProfile = 'ACCOUNT:DescribeProfile';
module.exports.ACCOUNT_EditProfile = 'ACCOUNT:EditProfile';
module.exports.ACCOUNT_ChangeProfilePassword = 'ACCOUNT:ChangeProfilePassword';
module.exports.IAM_fullAccess = 'IAM.*';
module.exports.IAM_AdminPermissions_FullAccess = 'IAM:AdminPermissions:*';
module.exports.IAM_AdminPermissions_SortPermissions = 'IAM:AdminPermissions:SortPermissions';
module.exports.IAM_AdminPermissions_ListPermissions = 'IAM:AdminPermissions:ListPermissions';
module.exports.IAM_AdminPermissions_DescribePermission = 'IAM:AdminPermissions:DescribePermission';
module.exports.IAM_AdminPermissions_EditPermissions = 'IAM:AdminPermissions:EditPermissions';
module.exports.IAM_AdminPermissions_ListRoles = 'IAM:AdminPermissions:ListRoles';
module.exports.IAM_AdminPermissions_DescribeRole = 'IAM:AdminPermissions:DescribeRole';
module.exports.IAM_AdminPermissions_CreateRole = 'IAM:AdminPermissions:CreateRole';
module.exports.IAM_AdminPermissions_EditRole = 'IAM:AdminPermissions:EditRole';
module.exports.IAM_AdminPermissions_EditRolePermissions = 'IAM:AdminPermissions:EditRolePermissions';
module.exports.IAM_AdminManagement_FullAccess = 'IAM:AdminManagement:*';
module.exports.IAM_AdminManagement_ListAdmins = 'IAM:AdminManagement:ListAdmins';
module.exports.IAM_AdminManagement_CreateAdmin = 'IAM:AdminManagement:CreateAdmin';
module.exports.IAM_AdminManagement_DescribeAdmin = 'IAM:AdminManagement:DescribeAdmin';
module.exports.IAM_AdminManagement_EditAdmin = 'IAM:AdminManagement:EditAdmin';
module.exports.IAM_AdminManagement_ActivateAdmin = 'IAM:AdminManagement:ActivateAdmin';
module.exports.IAM_AdminManagement_BlockAdmin = 'IAM:AdminManagement:BlockAdmin';
module.exports.IAM_AdminManagement_AssignRole = 'IAM:AdminManagement:AssignRole';
module.exports.IAM_AdminManagement_RevokeRole = 'IAM:AdminManagement:RevokeRole';
module.exports.IAM_AdminManagement_AssignDirectPermission = 'IAM:AdminManagement:AssignDirectPermission';
module.exports.IAM_AdminManagement_RevokeDirectPermission = 'IAM:AdminManagement:RevokeDirectPermission';
module.exports.IAM_AdminManagement_ChangePassword = 'IAM:AdminManagement:ChangePassword';
module.exports.CMS_FullAccess = 'CMS.*';
module.exports.CMS_ContentManagement_FullAccess = 'CMS:ContentManagement:ListLocations:*';
module.exports.CMS_ContentManagement_ListLocations = 'CMS:ContentManagement:ListLocations';
module.exports.CMS_ContentManagement_DescribeLocations = 'CMS:ContentManagement:DescribeLocations';
module.exports.CMS_ContentManagement_AddLocation = 'CMS:ContentManagement:AddLocation';
module.exports.CMS_ContentManagement_EditLocation = 'CMS:ContentManagement:EditLocation';
module.exports.CMS_PropertyManagement_FullAccess = 'CMS:PropertyManagement:*';
module.exports.CMS_PropertyManagement_ListProperties = 'CMS:PropertyManagement:ListProperties';
module.exports.CMS_PropertyManagement_DescribeProperty = 'CMS:PropertyManagement:DescribeProperty';
module.exports.CMS_PropertyManagement_CreateProperty = 'CMS:PropertyManagement:CreateProperty';
module.exports.CMS_PropertyManagement_EditPropertyBasicDetails = 'CMS:PropertyManagement:EditPropertyBasicDetails';
module.exports.CMS_PropertyManagement_ActivateProperty = 'CMS:PropertyManagement:ActivateProperty';
module.exports.CMS_PropertyManagement_BlockProperty = 'CMS:PropertyManagement:BlockProperty';
module.exports.CMS_PropertyManagement_AssignExtranetUser = 'CMS:PropertyManagement:AssignExtranetUser';
module.exports.CMS_PropertyManagement_RevokeExtranetUser = 'CMS:PropertyManagement:RevokeExtranetUser';
module.exports.IBE_FullAccess = 'IBE:*';
module.exports.IBE_Bookings_FullAccess = 'IBE:Bookings:*';
module.exports.IBE_Bookings_ListBookings = 'IBE:Bookings:ListBookings';
module.exports.IBE_Bookings_DescribeBooking = 'IBE:Bookings:DescribeBooking';
module.exports.IBE_Bookings_TriggerNotifications = 'IBE:Bookings:TriggerNotifications';
module.exports.IBE_Bookings_ExportReports = 'IBE:Bookings:ExportReports'; // new
module.exports.IBE_BookingDashboard_FullAccess = 'IBE:BookingDashboard:*';
module.exports.IBE_BookingDashboard_ViewCharts = 'IBE:Bookings:ViewCharts';
module.exports.IBE_BeGroups_FullAccess = 'IBE:BeGroups:*';
module.exports.IBE_BeGroups_ListGroups = 'IBE:BeGroups:ListGroups';
module.exports.IBE_BeGroups_DescribeGroup = 'IBE:BeGroups:DescribeGroup';
module.exports.IBE_BeGroups_CreateGroup = 'IBE:BeGroups:CreateGroup';
module.exports.IBE_BeGroups_EditGroup = 'IBE:BeGroups:EditGroup';
module.exports.IBE_BeGroups_AssignProperty = 'IBE:BeGroups:AssignProperty';
module.exports.IBE_BeGroups_RemoveProperty = 'IBE:BeGroups:RemoveProperty';
module.exports.IBE_GoogleHotels_FullAccess = 'IBE:GoogleHotels:*';
module.exports.IBE_GoogleHotels_ListProperties = 'IBE:GoogleHotels:ListProperties';
module.exports.IBE_GoogleHotels_DownloadListing = 'IBE:GoogleHotels:DownloadListing';
module.exports.IBE_Connectivity_FullAccess = 'IBE:Connectivity:*';
module.exports.IBE_Connectivity_ListConnectivity = 'IBE:Connectivity:ListConnectivity';
module.exports.IBE_Connectivity_DescribeConnectivity = 'IBE:Connectivity:DescribeConnectivity';
module.exports.IBE_Connectivity_CreateConnectivity = 'IBE:Connectivity:CreateConnectivity';
module.exports.IBE_Connectivity_EditConnectivity = 'IBE:Connectivity:EditConnectivity';
module.exports.IBE_Connectivity_ActivateConnectivity = 'IBE:Connectivity:ActivateConnectivity';
module.exports.IBE_Connectivity_DisableConnectivity = 'IBE:Connectivity:DisableConnectivity';
module.exports.IBE_Connectivity_ViewSecrets = 'IBE:Connectivity:ViewSecrets';
module.exports.IBE_Connectivity_DescribeSecrets = 'IBE:Connectivity:DescribeSecrets';
module.exports.IBE_Connectivity_ViewOnboardingDetails = 'IBE:Connectivity:ViewOnboardingDetails'; // new
module.exports.IBE_AriMonitoring_FullAccess = 'IBE:AriMonitoring:*';
module.exports.IBE_AriMonitoring_ViewMonitoring = 'IBE:AriMonitoring:ViewMonitoring'; // modified. old symbol - IBE:ViewMonitoring:*
module.exports.IBE_AriMonitoring_ExportReport = 'IBE:AriMonitoring:ExportReport'; // new
module.exports.IBE_ChannelLogs_FullAccess = 'IBE:ChannelLogs:*';
module.exports.IBE_ChannelLogs_ListLogs = 'IBE:ChannelLogs:ListLogs';
module.exports.IBE_ChannelLogs_DescribeLog = 'IBE:ChannelLogs:DescribeLog';
module.exports.IBE_ChannelLogs_ReviewLog = 'IBE:ChannelLogs:ReviewLog';
module.exports.IBE_ApiLogs_FullAccess = 'IBE:ApiLogs:*'; // new
module.exports.IBE_ApiLogs_ListLogs = 'IBE:ApiLogs:ListLogs'; // new
module.exports.IBE_ApiLogs_DescribeLogs = 'IBE:ApiLogs:DescribeLogs'; // new
module.exports.IBE_WebsiteSettings_FullAccess = 'IBE:WebsiteSettings:*'; // new
module.exports.IBE_WebsiteSettings_ViewSettings = 'IBE:WebsiteSettings:ViewSettings'; // new
module.exports.IBE_WebsiteSettings_UpdateSettings = 'IBE:WebsiteSettings:UpdateSettings'; // new
module.exports.IYA_FullAccess = 'IYA:*';
module.exports.IYA_BookingDataManagement_FullAccess = 'IYA:BookingDataManagement:*';
module.exports.IYA_BookingDataManagement_BookingSetups_FullAccess = 'IYA:BookingDataManagement:BookingSetups:*';
module.exports.IYA_BookingDataManagement_BookingSetups_ListSetups = 'IYA:BookingDataManagement:BookingSetups:ListSetups';
module.exports.IYA_BookingDataManagement_BookingSetups_DescribeSetup = 'IYA:BookingDataManagement:BookingSetups:DescribeSetup';
module.exports.IYA_BookingDataManagement_BookingSetups_CreateSetup = 'IYA:BookingDataManagement:BookingSetups:CreateSetup';
module.exports.IYA_BookingDataManagement_BookingSetups_EditSetup = 'IYA:BookingDataManagement:BookingSetups:EditSetup';
module.exports.IYA_BookingDataManagement_BookingSetups_ActivateSetup = 'IYA:BookingDataManagement:BookingSetups:ActivateSetup';
module.exports.IYA_BookingDataManagement_BookingSetups_RejectSetup = 'IYA:BookingDataManagement:BookingSetups:RejectSetup';
module.exports.IYA_BookingDataManagement_BookingSetups_DisableSetup = 'IYA:BookingDataManagement:BookingSetups:DisableSetup';
module.exports.IYA_BookingDataManagement_BookingSetups_DeleteSetup = 'IYA:BookingDataManagement:BookingSetups:DeleteSetup';
module.exports.IYA_BookingDataManagement_BookingConfigs_FullAccess = 'IYA:BookingDataManagement:BookingConfigs:*';
module.exports.IYA_BookingDataManagement_BookingConfigs_ListConfigs = 'IYA:BookingDataManagement:BookingConfigs:ListConfigs';
module.exports.IYA_BookingDataManagement_BookingConfigs_DescribeConfig = 'IYA:BookingDataManagement:BookingConfigs:DescribeConfig';
module.exports.IYA_BookingDataManagement_BookingConfigs_CreateConfig = 'IYA:BookingDataManagement:BookingConfigs:CreateConfig';
module.exports.IYA_BookingDataManagement_BookingConfigs_ActivateConfig = 'IYA:BookingDataManagement:BookingConfigs:ActivateConfig';
module.exports.IYA_BookingDataManagement_BookingConfigs_DisableConfig = 'IYA:BookingDataManagement:BookingConfigs:DisableConfig';
module.exports.IYA_BookingDataManagement_BookingConfigs_RejectConfig = 'IYA:BookingDataManagement:BookingConfigs:RejectConfig';
module.exports.IYA_BookingDataManagement_BookingConfigs_DeleteConfig = 'IYA:BookingDataManagement:BookingConfigs:DeleteConfig';
module.exports.IYA_BookingDataManagement_BookingConfigs_DescribeOnboardingDetails = 'IYA:BookingDataManagement:BookingConfigs:DescribeOnboardingDetails';
module.exports.IYA_BookingDataManagement_BookingConfigs_DescribeSecrets = 'IYA:BookingDataManagement:BookingConfigs:DescribeSecrets';
module.exports.IYA_BookingDataManagement_BookingConfigs_DownloadSecrets = 'IYA:BookingDataManagement:BookingConfigs:DownloadSecrets';
module.exports.IYA_BookingDataManagement_BookingActivity_FullAccess = 'IYA:BookingDataManagement:BookingActivity:*';
module.exports.IYA_BookingDataManagement_BookingActivity_ListActivity = 'IYA:BookingDataManagement:BookingActivity:ListActivity';
module.exports.IYA_BookingDataManagement_BookingActivity_DescribeActivity = 'IYA:BookingDataManagement:BookingActivity:DescribeActivity';
module.exports.IYA_BookingDataManagement_BookingSummaryActivity_FullAccess = 'IYA:BookingDataManagement:BookingSummaryActivity:*';
module.exports.IYA_BookingDataManagement_BookingSummaryActivity_ListActivity = 'IYA:BookingDataManagement:BookingSummaryActivity:ListActivity';
module.exports.IYA_BookingDataManagement_BookingSummaryActivity_DescribeActivity = 'IYA:BookingDataManagement:BookingSummaryActivity:DescribeActivity';
module.exports.IYA_BookingDataManagement_BookingSummaryInspection_FullAccess = 'IYA:BookingDataManagement:BookingSummaryInspection:*';
module.exports.IYA_BookingDataManagement_BookingSummaryInspection_ListData = 'IYA:BookingDataManagement:BookingSummaryInspection:ListData';
module.exports.IYA_BookingDataManagement_BookingSummaryInspection_DescribeData = 'IYA:BookingDataManagement:BookingSummaryInspection:DescribeData';
module.exports.IYA_RateShoppingManagement_FullAccess = 'IYA:RateShoppingManagement:*';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_FullAccess = 'IYA:RateShoppingManagement:RateShopperSetups:*';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_ListSetups = 'IYA:RateShoppingManagement:RateShopperSetups:ListSetups';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_DescribeSetup = 'IYA:RateShoppingManagement:RateShopperSetups:DescribeSetup';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_CreateSetup = 'IYA:RateShoppingManagement:RateShopperSetups:CreateSetup';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_EditSetup = 'IYA:RateShoppingManagement:RateShopperSetups:EditSetup';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_ActivateSetup = 'IYA:RateShoppingManagement:RateShopperSetups:ActivateSetup';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_RejectSetup = 'IYA:RateShoppingManagement:RateShopperSetups:RejectSetup';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_DisableSetup = 'IYA:RateShoppingManagement:RateShopperSetups:DisableSetup';
module.exports.IYA_RateShoppingManagement_RateShopperSetups_DeleteSetup = 'IYA:RateShoppingManagement:RateShopperSetups:DeleteSetup';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_FullAccess = 'IYA:RateShoppingManagement:RateShopperConfigs:*';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_ListConfigs = 'IYA:RateShoppingManagement:RateShopperConfigs:ListConfigs';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_DescribeConfig = 'IYA:RateShoppingManagement:RateShopperConfigs:DescribeConfig';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_CreateConfig = 'IYA:RateShoppingManagement:RateShopperConfigs:CreateConfig';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_ActivateConfig = 'IYA:RateShoppingManagement:RateShopperConfigs:ActivateConfig';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_DisableConfig = 'IYA:RateShoppingManagement:RateShopperConfigs:DisableConfig';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_RejectConfig = 'IYA:RateShoppingManagement:RateShopperConfigs:RejectConfig';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_DeleteConfig = 'IYA:RateShoppingManagement:RateShopperConfigs:DeleteConfig';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_DescribeOnboardingDetails = 'IYA:RateShoppingManagement:RateShopperConfigs:DescribeOnboardingDetails';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_DescribeSecrets = 'IYA:RateShoppingManagement:RateShopperConfigs:DescribeSecrets';
module.exports.IYA_RateShoppingManagement_RateShopperConfigs_DownloadSecrets = 'IYA:RateShoppingManagement:RateShopperConfigs:DownloadSecrets';
module.exports.IYA_RateShoppingManagement_RateShoppingActivity_FullAccess = 'IYA:RateShoppingManagement:RateShoppingActivity:*';
module.exports.IYA_RateShoppingManagement_RateShoppingActivity_ListActivity = 'IYA:RateShoppingManagement:RateShoppingActivity:ListActivity';
module.exports.IYA_RateShoppingManagement_RateShoppingActivity_DescribeActivity = 'IYA:RateShoppingManagement:RateShoppingActivity:DescribeActivity';
module.exports.IYA_RateShoppingManagement_RateShoppingInspection_FullAccess = 'IYA:RateShoppingManagement:RateShoppingInspection:*';
module.exports.IYA_RateShoppingManagement_RateShoppingInspection_ListData = 'IYA:RateShoppingManagement:RateShoppingInspection:ListData';
module.exports.IYA_RateShoppingManagement_RateShoppingInspection_DescribeData = 'IYA:RateShoppingManagement:RateShoppingInspection:DescribeData';
module.exports.IYA_ReviewDataManagement_FullAccess = 'IYA:ReviewDataManagement:*';
module.exports.IYA_ReviewDataManagement_ReviewSetups_FullAccess = 'IYA:ReviewDataManagement:ReviewSetups:*';
module.exports.IYA_ReviewDataManagement_ReviewSetups_ListSetups = 'IYA:ReviewDataManagement:ReviewSetups:ListSetups';
module.exports.IYA_ReviewDataManagement_ReviewSetups_DescribeSetup = 'IYA:ReviewDataManagement:ReviewSetups:DescribeSetup';
module.exports.IYA_ReviewDataManagement_ReviewSetups_CreateSetup = 'IYA:ReviewDataManagement:ReviewSetups:CreateSetup';
module.exports.IYA_ReviewDataManagement_ReviewSetups_EditSetup = 'IYA:ReviewDataManagement:ReviewSetups:EditSetup';
module.exports.IYA_ReviewDataManagement_ReviewSetups_ActivateSetup = 'IYA:ReviewDataManagement:ReviewSetups:ActivateSetup';
module.exports.IYA_ReviewDataManagement_ReviewSetups_RejectSetup = 'IYA:ReviewDataManagement:ReviewSetups:RejectSetup';
module.exports.IYA_ReviewDataManagement_ReviewSetups_DisableSetup = 'IYA:ReviewDataManagement:ReviewSetups:DisableSetup';
module.exports.IYA_ReviewDataManagement_ReviewSetups_DeleteSetup = 'IYA:ReviewDataManagement:ReviewSetups:DeleteSetup';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_FullAccess = 'IYA:ReviewDataManagement:ReviewConfigs:*';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_ListConfigs = 'IYA:ReviewDataManagement:ReviewConfigs:ListConfigs';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_DescribeConfig = 'IYA:ReviewDataManagement:ReviewConfigs:DescribeConfig';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_CreateConfig = 'IYA:ReviewDataManagement:ReviewConfigs:CreateConfig';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_ActivateConfig = 'IYA:ReviewDataManagement:ReviewConfigs:ActivateConfig';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_DisableConfig = 'IYA:ReviewDataManagement:ReviewConfigs:DisableConfig';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_RejectConfig = 'IYA:ReviewDataManagement:ReviewConfigs:RejectConfig';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_DeleteConfig = 'IYA:ReviewDataManagement:ReviewConfigs:DeleteConfig';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_DescribeOnboardingDetails = 'IYA:ReviewDataManagement:ReviewConfigs:DescribeOnboardingDetails';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_DescribeSecrets = 'IYA:ReviewDataManagement:ReviewConfigs:DescribeSecrets';
module.exports.IYA_ReviewDataManagement_ReviewConfigs_DownloadSecrets = 'IYA:ReviewDataManagement:ReviewConfigs:DownloadSecrets';
module.exports.IYA_ReviewDataManagement_ReviewActivity_FullAccess = 'IYA:ReviewDataManagement:ReviewActivity:*';
module.exports.IYA_ReviewDataManagement_ReviewActivity_ListActivity = 'IYA:ReviewDataManagement:ReviewActivity:ListActivity';
module.exports.IYA_ReviewDataManagement_ReviewActivity_DescribeActivity = 'IYA:ReviewDataManagement:ReviewActivity:DescribeActivity';
module.exports.IYA_ReviewDataManagement_ReviewSummaryActivity_FullAccess = 'IYA:ReviewDataManagement:ReviewSummaryActivity:*';
module.exports.IYA_ReviewDataManagement_ReviewSummaryActivity_ListActivity = 'IYA:ReviewDataManagement:ReviewSummaryActivity:ListActivity';
module.exports.IYA_ReviewDataManagement_ReviewSummaryActivity_DescribeActivity = 'IYA:ReviewDataManagement:ReviewSummaryActivity:DescribeActivity';
module.exports.IYA_CompsetManagement_FullAccess = 'IYA:CompsetManagement:*';
module.exports.IYA_CompsetManagement_Compsets_FullAccess = 'IYA:CompsetManagement:Compsets:*';
module.exports.IYA_CompsetManagement_Compsets_ListSetups = 'IYA:CompsetManagement:Compsets:ListSetups';
module.exports.IYA_CompsetManagement_Compsets_DescribeSetup = 'IYA:CompsetManagement:Compsets:DescribeSetup';
module.exports.IYA_CompsetManagement_Compsets_CreateSetup = 'IYA:CompsetManagement:Compsets:CreateSetup';
module.exports.IYA_CompsetManagement_Compsets_EditSetup = 'IYA:CompsetManagement:Compsets:EditSetup';
module.exports.IYA_CompsetManagement_Compsets_ActivateSetup = 'IYA:CompsetManagement:Compsets:ActivateSetup';
module.exports.IYA_CompsetManagement_Compsets_RejectSetup = 'IYA:CompsetManagement:Compsets:RejectSetup';
module.exports.IYA_CompsetManagement_Compsets_DisableSetup = 'IYA:CompsetManagement:Compsets:DisableSetup';
module.exports.IYA_CompsetManagement_Compsets_DeleteSetup = 'IYA:CompsetManagement:Compsets:DeleteSetup';
module.exports.IYA_DemandManagement_FullAccess = 'IYA:DemandManagement:*';
module.exports.IYA_DemandManagement_PropertyDemandSetups_FullAccess = 'IYA:DemandManagement:PropertyDemandSetups:*';
module.exports.IYA_DemandManagement_PropertyDemandSetups_ListSetups = 'IYA:DemandManagement:PropertyDemandSetups:ListSetups';
module.exports.IYA_DemandManagement_PropertyDemandSetups_DescribeSetup = 'IYA:DemandManagement:PropertyDemandSetups:DescribeSetup';
module.exports.IYA_DemandManagement_PropertyDemandSetups_CreateSetup = 'IYA:DemandManagement:PropertyDemandSetups:CreateSetup';
module.exports.IYA_DemandManagement_PropertyDemandSetups_EditSetup = 'IYA:DemandManagement:PropertyDemandSetups:EditSetup';
module.exports.IYA_DemandManagement_PropertyDemandSetups_ActivateSetup = 'IYA:DemandManagement:PropertyDemandSetups:ActivateSetup';
module.exports.IYA_DemandManagement_PropertyDemandSetups_RejectSetup = 'IYA:DemandManagement:PropertyDemandSetups:RejectSetup';
module.exports.IYA_DemandManagement_PropertyDemandSetups_DisableSetup = 'IYA:DemandManagement:PropertyDemandSetups:DisableSetup';
module.exports.IYA_DemandManagement_PropertyDemandSetups_DeleteSetup = 'IYA:DemandManagement:PropertyDemandSetups:DeleteSetup';
module.exports.IYA_PropertyVariablesSetup_FullAccess = 'IYA:PropertyVariablesSetup:*';
module.exports.IYA_PropertyVariablesSetup_ListSetups = 'IYA:PropertyVariablesSetup:ListSetups';
module.exports.IYA_PropertyVariablesSetup_DescribeSetup = 'IYA:PropertyVariablesSetup:DescribeSetup';
module.exports.IYA_PropertyVariablesSetup_CreateSetup = 'IYA:PropertyVariablesSetup:CreateSetup';
module.exports.IYA_PropertyVariablesSetup_EditSetup = 'IYA:PropertyVariablesSetup:EditSetup';
module.exports.IYA_PropertyVariablesSetup_ActivateSetup = 'IYA:PropertyVariablesSetup:ActivateSetup';
module.exports.IYA_PropertyVariablesSetup_RejectSetup = 'IYA:PropertyVariablesSetup:RejectSetup';
module.exports.IYA_PropertyVariablesSetup_DisableSetup = 'IYA:PropertyVariablesSetup:DisableSetup';
module.exports.IYA_PropertyVariablesSetup_DeleteSetup = 'IYA:PropertyVariablesSetup:DeleteSetup';
module.exports.IYA_Automation_FullAccess = 'IYA:Automation:*';
module.exports.IYA_Automation_ListRoutines = 'IYA:Automation:ListRoutines';
module.exports.IYA_Automation_DescribeRoutine = 'IYA:Automation:DescribeRoutine';
module.exports.IYA_Automation_ListTasks = 'IYA:Automation:ListTasks';
module.exports.IYA_Automation_DescribeTask = 'IYA:Automation:DescribeTask';
module.exports.IYA_Automation_ListTaskAttempts = 'IYA:Automation:ListTaskAttempts';
module.exports.IYA_Automation_DescribeTaskAttempt = 'IYA:Automation:DescribeTaskAttempt';
module.exports.IYA_Intelligence_FullAccess = 'IYA:FullAccess:*'; // new
module.exports.IYA_Intelligence_ListSetups = 'IYA:ListSetups:*'; // new
module.exports.IYA_Intelligence_DescribeSetup = 'IYA:DescribeSetup:*'; // new
module.exports.IYA_Intelligence_CreateSetup = 'IYA:CreateSetup:*'; // new
module.exports.IYA_Intelligence_EditSetup = 'IYA:EditSetup:*'; // new
module.exports.IYA_Intelligence_DisableSetup = 'IYA:DisableSetup:*'; // new
module.exports.IYA_Intelligence_ActivateSetup = 'IYA:ActivateSetup:*'; // new
module.exports.IYA_Intelligence_RejectSetup = 'IYA:RejectSetup:*'; // new
module.exports.IYA_Intelligence_DeleteSetup = 'IYA:DeleteSetup:*'; // new
module.exports.IYA_ApiLogs_FullAccess = 'IYA:ApiLogs:*';
module.exports.IYA_ApiLogs_ListLogs = 'IYA:ApiLogs:ListLogs';
module.exports.IYA_ApiLogs_DescribeLog = 'IYA:ApiLogs:DescribeLog';
module.exports.IYA_VendorManagement_FullAccess = 'IYA:VendorManagement:*';
module.exports.IYA_VendorManagement_AiRateMetrics_FullAccess = 'IYA:VendorManagement:AiRateMetrics:*';
module.exports.IYA_VendorManagement_AiRateMetrics_ListRateShops = 'IYA:VendorManagement:AiRateMetrics:ListRateShops';
module.exports.IYA_VendorManagement_AiRateMetrics_DescribeRateShop = 'IYA:VendorManagement:AiRateMetrics:DescribeRateShop';
module.exports.IYA_VendorManagement_AiRateMetrics_ListRateQueues = 'IYA:VendorManagement:AiRateMetrics:ListRateQueues';
module.exports.IYA_VendorManagement_AiRateMetrics_DescribeRateSQueue = 'IYA:VendorManagement:AiRateMetrics:DescribeRateSQueue';
module.exports.IYA_VendorManagement_AiRateMetrics_ListRateQueueData = 'IYA:VendorManagement:AiRateMetrics:ListRateQueueData';
module.exports.IYA_VendorManagement_AiRateMetrics_DescribeRatesQueueData = 'IYA:VendorManagement:AiRateMetrics:DescribeRatesQueueData'; // renamed. DescribeRatesQueueData 'S' was capital before.
module.exports.IYA_VendorManagement_AiRateMetrics_SearchHotel = 'IYA:VendorManagement:AiRateMetrics:SearchHotel'; // new
module.exports.IYA_VendorManagement_AiRateMetrics_ViewAccountCredits = 'IYA:VendorManagement:AiRateMetrics:ViewAccountCredits'; // new
module.exports.IYA_VendorManagement_AiRateMetrics_GetQueueStatus = 'IYA:VendorManagement:AiRateMetrics:GetQueueStatus'; // new
module.exports.IYA_VendorManagement_AiRateMetrics_ViewReferenceContent = 'IYA:VendorManagement:AiRateMetrics:ViewReferenceContent'; // new
module.exports.IYA_VendorManagement_AiReviews_FullAccess = 'IYA:VendorManagement:AiReviews:*'; // new
module.exports.IYA_VendorManagement_AiReviews_SearchHotel = 'IYA:VendorManagement:SearchHotel:*'; // new
module.exports.IYA_VendorManagement_AiReviews_RequestHotel = 'IYA:VendorManagement:RequestHotel:*'; // new