export const  _MARKET_CHANNEL_CLEARTRIP = 'CLEARTRIP';
export const  _MARKET_CHANNEL_RESAVENUE = 'RESAVENUE';
export const  _MARKET_CHANNEL_MAKEMYTRIP = 'MAKEMYTRIP';
export const  _MARKET_CHANNEL_GOIBIBO = 'GOIBIBO';
export const  _MARKET_CHANNEL_AGODA = 'AGODA';
export const  _MARKET_CHANNEL_EXPEDIA = 'EXPEDIA';
export const  _MARKET_CHANNEL_TRAVEL_GURU = 'TRAVEL_GURU';
export const  _MARKET_CHANNEL_BOOKING_DOT_COM = 'BOOKING_DOT_COM';
export const  _MARKET_CHANNEL_VIA = 'VIA';
export const  _MARKET_CHANNEL_HOTELS_COMBINED = 'HOTELS_COMBINED';
export const  _MARKET_CHANNEL_ONLINE_GDS = 'ONLINE_GDS';
export const  _MARKET_CHANNEL_MR_AND_MRS_SMITH = 'MR_AND_MRS_SMITH';
export const  _MARKET_CHANNEL_HOTELS_BED = 'HOTELS_BED';
export const  _MARKET_CHANNEL_WELCOM_HERITAGE = 'Welcom_HERITAGE';
export const  _MARKET_CHANNEL_DOTW = 'DOTW';
export const  _MARKET_CHANNEL_SIMPLOTEL = 'SIMPLOTEL';
export const  _MARKET_CHANNEL_HRS = 'HRS';
export const  _MARKET_CHANNEL_EASE_MY_TRIP = 'EASE_MY_TRIP';
export const  _MARKET_CHANNEL_TRIP_DOT_COM = 'TRIP_DOT_COM';
export const  _MARKET_CHANNEL_TRIPADVISOR = 'TRIPADVISOR';
export const  _MARKET_CHANNEL_PAYTM = 'PAYTM';
export const  _MARKET_CHANNEL_TRAVELIKO = 'TRAVELIKO';
export const  _MARKET_CHANNEL_HAPPY_EASY_GO = 'HAPPY_EASY_GO';
export const  _MARKET_CHANNEL_HOBSE = 'HOBSE';
export const  _MARKET_CHANNEL_BOOK_LOGIC = 'BOOK_LOGIC';
export const  _MARKET_CHANNEL_IRCTC = 'IRCTC';
export const  _MARKET_CHANNEL_XENIA = 'XENIA';
export const  _MARKET_CHANNEL_CHANNEX = 'CHANNEX';
export const  _MARKET_CHANNEL_RESAVENUE_PMS = 'RESAVENUE_PMS';
export const  _MARKET_CHANNEL_TOUR_MY_INDIA = 'TOUR_MY_INDIA';
export const  _MARKET_CHANNEL_VEEKEND = 'VEEKEND';
export const  _MARKET_CHANNEL_ONE_FINE_RATE = 'ONE_FINE_RATE';
export const  _MARKET_CHANNEL_SYSOTEL = 'SYSOTEL';
export const  _MARKET_CHANNEL_HOTLA = 'HOTLA';
export const  _MARKET_CHANNEL_TRAVIATE = 'TRAVIATE';
export const  _MARKET_CHANNEL_ONLINE_VACATIONS = 'ONLINE_VACATIONS';
export const  _MARKET_CHANNEL_ROOM_STATUS_HUB = 'ROOM_STATUS_HUB';
export const  _MARKET_CHANNEL_TRAVEL_BOUTIQUE = 'TRAVEL_BOUTIQUE';
export const  _MARKET_CHANNEL_HOSTEL_WORLD = 'HOSTEL_WORLD';
export const  _MARKET_CHANNEL_GOOGLE = 'GOOGLE';
export const  _MARKET_CHANNEL_HOTELS_DOT_COM = 'HOTELS_DOT_COM';
export const  _MARKET_CHANNEL_PRICELINE = 'PRICELINE';
export const  _MARKET_CHANNEL_ORBITZ = 'ORBITZ';
export const  _MARKET_CHANNEL_IHG_DOT_COM = 'IHG_DOT_COM';
export const  _MARKET_CHANNEL_MARRIOTT = 'MARRIOTT';
export const  _MARKET_CHANNEL_RADISSONCOM = 'RADISSONCOM';
export const  _MARKET_CHANNEL_HILTON = 'HILTON';
export const  _MARKET_CHANNEL_BOOKBESTWESTERNCOM = 'BOOKBESTWESTERNCOM';
export const  _MARKET_CHANNEL_HRSCOM = 'HRSCOM';
export const  _MARKET_CHANNEL_ACCORHOTELS = 'ACCORHOTELS';
export const  _MARKET_CHANNEL_JUMIA = 'JUMIA';
export const  _MARKET_CHANNEL_YATRA = 'YATRA';
export const  _MARKET_CHANNEL_HOSTELWORLD = 'HOSTELWORLD';
export const  _MARKET_CHANNEL_LATEROOMS = 'LATEROOMS';
export const  _MARKET_CHANNEL_SPLENDIA = 'SPLENDIA';
export const  _MARKET_CHANNEL_BESTDAY = 'BESTDAY';
export const  _MARKET_CHANNEL_PRICETRAVEL = 'PRICETRAVEL';
export const  _MARKET_CHANNEL_AIRBNB = 'AIRBNB';
export const  _MARKET_CHANNEL_LASTMINUTE_DOT_COM = 'LASTMINUTE_DOT_COM';
export const  _MARKET_CHANNEL_TRAVELOKA = 'TRAVELOKA';
export const  _MARKET_CHANNEL_HOTELLOOK = 'HOTELLOOK';
export const  _MARKET_CHANNEL_OSTROVOK = 'OSTROVOK';
export const  _MARKET_CHANNEL_PEGIPEGI = 'PEGIPEGI';
export const  _MARKET_CHANNEL_TIKET = 'TIKET';
export const  _MARKET_CHANNEL_RAKUTEN = 'RAKUTEN';
export const  _MARKET_CHANNEL_CTRIP = 'CTRIP';
export const  _MARKET_CHANNEL_TRAVELREPUBLIC = 'TRAVELREPUBLIC';
export const  _MARKET_CHANNEL_MRANDMRSSMITH = 'MRANDMRSSMITH';
export const  _MARKET_CHANNEL_FABHOTELS = 'FABHOTELS';
export const  _MARKET_CHANNEL_TREEBO = 'TREEBO';
export const  _MARKET_CHANNEL_HOLIDAYCHECK = 'HOLIDAYCHECK';
export const  _MARKET_CHANNEL_TRAVELOCITY = 'TRAVELOCITY';
export const  _MARKET_CHANNEL_CHEAPTICKETS = 'CHEAPTICKETS';
export const  _MARKET_CHANNEL_EBOOKERS = 'EBOOKERS';
export const  _MARKET_CHANNEL_DESPEGAR = 'DESPEGAR';
export const  _MARKET_CHANNEL_MEITUAN = 'MEITUAN';
export const  _MARKET_CHANNEL_BOOKINGS_FLIGHTEXPERT_COM = 'BOOKINGS_FLIGHTEXPERT_COM';
export const  _MARKET_CHANNEL_SHARETRIP = 'SHARETRIP';
export const  _MARKET_CHANNEL_GOZAYAAN = 'GOZAYAAN';
export const  _MARKET_CHANNEL_RURUBU = 'RURUBU';
export const  _MARKET_CHANNEL_BE_SYNXIS_COM = 'BE_SYNXIS_COM';
export const  _MARKET_CHANNEL_WORLDROAMER = 'WORLDROAMER';
export const  _MARKET_CHANNEL_MYKONOS = 'MYKONOS';
export const  _MARKET_CHANNEL_BOOK_RGUEST_COM = 'BOOK_RGUEST_COM';
export const  _MARKET_CHANNEL_BOOKINGS_HOTELREZ_CO_UK = 'BOOKINGS_HOTELREZ_CO_UK';
export const  _MARKET_CHANNEL_SECURE_HOTEL_BOOKING = 'SECURE_HOTEL_BOOKING';
export const  _MARKET_CHANNEL_SHOUSUGIBANHOUSE = 'SHOUSUGIBANHOUSE';
export const  _MARKET_CHANNEL_RSWS_KRIPALU = 'RSWS_KRIPALU';
export const  _MARKET_CHANNEL_TUI = 'TUI';
export const  _MARKET_CHANNEL_GRANDBARAKA_HOTEL = 'GRANDBARAKA_HOTEL';
export const  _MARKET_CHANNEL_WEBHOTELIER = 'WEBHOTELIER';
export const  _MARKET_CHANNEL_BLASTNESS = 'BLASTNESS';
export const  _MARKET_CHANNEL_BOOK_SECURE = 'BOOK_SECURE';
export const  _MARKET_CHANNEL_VERTICAL_BOOKING = 'VERTICAL_BOOKING';
export const  _MARKET_CHANNEL_DIRECT_BOOK = 'DIRECT_BOOK';
export const  _MARKET_CHANNEL_EURO_STARS_HOTELS = 'EURO_STARS_HOTELS';
export const  _MARKET_CHANNEL_HOTEL_ZIMBROS = 'HOTEL_ZIMBROS';
export const  _MARKET_CHANNEL_BOOK_OMNIBEES = 'BOOK_OMNIBEES';
export const  _MARKET_CHANNEL_HF_HOTELS = 'HF_HOTELS';
export const  _MARKET_CHANNEL_REHLAT = 'REHLAT';
export const  _MARKET_CHANNEL_SESIMBRA_HOTEL_SPA = 'SESIMBRA_HOTEL_SPA';
export const  _MARKET_CHANNEL_ONE_PAGE_BOOKING = 'ONE_PAGE_BOOKING';
export const  _MARKET_CHANNEL_ADAGIO_CITY = 'ADAGIO_CITY';
export const  _MARKET_CHANNEL_MASA_HOTEL = 'MASA_HOTEL';
export const  _MARKET_CHANNEL_BOOKING_CAMPING = 'BOOKING_CAMPING';
export const  _MARKET_CHANNEL_BOOKING_EXPERT = 'BOOKING_EXPERT';
export const  _MARKET_CHANNEL_SCIDOO = 'SCIDOO';
export const  _MARKET_CHANNEL_H10_HOTELS = 'H10_HOTELS';
export const  _MARKET_CHANNEL_D_EDGE = 'D_EDGE';
export const  _MARKET_CHANNEL_SECURE_IPER_BOOKING = 'SECURE_IPER_BOOKING';
export const  _MARKET_CHANNEL_E_GDS = 'E_GDS';
export const  _MARKET_CHANNEL_HU_OPEN_AIR = 'HU_OPEN_AIR';
export const  _MARKET_CHANNEL_ORLANDO_INCHIANTI = 'ORLANDO_INCHIANTI';
export const  _MARKET_CHANNEL_NET_BOOKING_NATURAL_BOOKING = 'NET_BOOKING_NATURAL_BOOKING';
export const  _MARKET_CHANNEL_CAMPING_SERENO = 'CAMPING_SERENO';
export const  _MARKET_CHANNEL_CAMPING_CISANO = 'CAMPING_CISANO';
export const  _MARKET_CHANNEL_ICONNECT_PRENOTA_ONLINE = 'ICONNECT_PRENOTA_ONLINE';
export const  _MARKET_CHANNEL_PALACIO_ESTORIL_HOTEL = 'PALACIO_ESTORIL_HOTEL';
export const  _MARKET_CHANNEL_BOOKING_PREMIUM_SECURE_HOLIDAY = 'BOOKING_PREMIUM_SECURE_HOLIDAY';
export const  _MARKET_CHANNEL_SECURE_GUEST_CENTRIC = 'SECURE_GUEST_CENTRIC';
export const  _MARKET_CHANNEL_ALL_CAMPS = 'ALL_CAMPS';
export const  _MARKET_CHANNEL_DOMPEDRO = 'DOMPEDRO';
export const  _MARKET_CHANNEL_RESERVAS_VILAGALE = 'RESERVAS_VILAGALE';
export const  _MARKET_CHANNEL_HOTEL_BB = 'HOTEL_BB';
export const  _MARKET_CHANNEL_SIMPLE_BOOKING = 'SIMPLE_BOOKING';
export const  _MARKET_CHANNEL_ABBA_HOTELES = 'ABBA_HOTELES';
export const  _MARKET_CHANNEL_LOHONO = 'LOHONO';
export const  _MARKET_CHANNEL_SAFFRON_STAYS = 'SAFFRON_STAYS';
export const  _MARKET_CHANNEL_A_HOTEL = 'A_HOTEL';
export const  _MARKET_CHANNEL_TRAVEL_CLICK = 'TRAVEL_CLICK';
export const  _MARKET_CHANNEL_DEIFIORI = 'DEIFIORI';
export const  _MARKET_CHANNEL_BAIA_HOLIDAY = 'BAIA_HOLIDAY';
export const  _MARKET_CHANNEL_UNION_LIDO = 'UNION_LIDO';
export const  _MARKET_CHANNEL_IBEROSTAR = 'IBEROSTAR';
export const  _MARKET_CHANNEL_BOOK_CORE = 'BOOK_CORE';
export const  _MARKET_CHANNEL_RIU = 'RIU';
export const  _MARKET_CHANNEL_MIRAI = 'MIRAI';
export const  _MARKET_CHANNEL_SECURE_BOOKING = 'SECURE_BOOKING';
export const  _MARKET_CHANNEL_BOOKING_MY_GUEST_CARE = 'BOOKING_MY_GUEST_CARE';
export const  _MARKET_CHANNEL_CINEMA_8 = 'CINEMA 8';
export const  _MARKET_CHANNEL_ERICSOFT = 'ERICSOFT';
export const  _MARKET_CHANNEL_QUICK_BOOKING = 'QUICK_BOOKING';
export const  _MARKET_CHANNEL_HOTELS_EDREAMS = 'HOTELS_EDREAMS';
export const  _MARKET_CHANNEL_TRAVEL = 'TRAVEL';
export const  _MARKET_CHANNEL_HOTELS_CTRIP_COM = 'HOTELS_CTRIP_COM';

export const  COMPETITION_STATUS_ACTIVE = 'ACTIVE';
export const  COMPETITION_STATUS_DISABLED = 'DISABLED';
export const  COMPETITION_STATUS_ONBOARDING = 'ONBOARDING';

export const  COMPETITION_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
export const  COMPETITION_ONBOARDING_STATUS_REJECTED = 'REJECTED';
export const  COMPETITION_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const  COMPETITION_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

export const COMPETITION_SETUP_PROMOTION = 'PROMOTION'
export const COMPETITION_SETUP_PROMO_CODE = 'PROMO_CODE'

export const PROPERTY_REVIEW_ACTIVITY_METHOD_NO_EFFECT = 'NO_EFFECT';

export const  BUDGET_SETUP_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
export const  BUDGET_SETUP_ONBOARDING_STATUS_REJECTED = 'REJECTED';
export const  BUDGET_SETUP_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const  BUDGET_SETUP_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';
export const  BUDGET_SETUP_STATUS_ACTIVE = 'ACTIVE';
export const  BUDGET_SETUP_STATUS_DISABLED = 'DISABLED';
export const  BUDGET_SETUP_STATUS_ONBOARDING = 'ONBOARDING';

export const  AI_RATE_QUEUE_STATUS_IN_PROGRESS = "IN_PROGRESS";
export const  AI_RATE_QUEUE_STATUS_COMPLETED = "COMPLETED";
export const  AI_RATE_QUEUE_STATUS_TERMINATED_WITH_ERRORS = "TERMINATED_WITH_ERRORS";
export const  AI_RATE_QUEUE_STATUS_TERMINATED_WITH_CREDIT_ERROR = "TERMINATED_WITH_CREDIT_ERROR";
export const  AI_RATE_QUEUE_STATUS_RE_RUN_IN_PROGRESS = "RE_RUN_IN_PROGRESS";
export const  AI_RATE_QUEUE_STATUS_UNKNOWN = "UNKNOWN";

export const AI_RATE_QUEUE_ATTEMPT_STATUS_PENDING = "PENDING";
export const AI_RATE_QUEUE_ATTEMPT_STATUS_SUCCESS = "SUCCESS";
export const AI_RATE_QUEUE_ATTEMPT_STATUS_FAILED = "FAILED";
export const AI_RATE_QUEUE_ATTEMPT_STATUS_EXPIRED = "EXPIRED";
export const AI_RATE_QUEUE_ATTEMPT_STATUS_PARTIAL_SUCCESS =  "PARTIAL_SUCCESS";

export const BOOKING_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
export const BOOKING_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
export const BOOKING_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

export const  RATE_SHOPPING_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
export const  RATE_SHOPPING_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
export const  RATE_SHOPPING_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

export const REVIEW_INSIGHTS_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
export const REVIEW_INSIGHTS_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
export const REVIEW_INSIGHTS_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

export const TASK_ATTEMPT_STATUS_SUCCESS = 'SUCCESS';
export const TASK_ATTEMPT_STATUS_FAILURE = 'FAILURE';

export const RMS_REST_API = 'RMS_REST_API';
export const RESAVENUE_CM_API = 'RESAVENUE_CM_API';
export const RATE_GAIN_DEMAND_AI = 'RATE_GAIN_DEMAND_AI';
export const AI_RATE_METRICS = 'AI_RATE_METRICS';
export const AI_REVIEWS = 'AI_REVIEWS';
export const AI_EDDI = 'AI_EDDI';

export const REVIEW_CATEGORY_SERVICE = 'SERVICE';
export const REVIEW_CATEGORY_CLEANLINESS = 'CLEANLINESS';
export const REVIEW_CATEGORY_SLEEP_QUALITY = 'SLEEP_QUALITY';
export const REVIEW_CATEGORY_LOCATION = 'LOCATION';
export const REVIEW_CATEGORY_SPACE = 'SPACE';
export const REVIEW_CATEGORY_BREAKFAST = 'BREAKFAST';
export const REVIEW_CATEGORY_VALUE = 'VALUE';
export const REVIEW_CATEGORY_SPA = 'SPA';
export const REVIEW_CATEGORY_ROOM = 'ROOM';
export const REVIEW_CATEGORY_COMFORT = 'COMFORT';
export const REVIEW_CATEGORY_FACILITIES = 'FACILITIES';
export const REVIEW_CATEGORY_STAFF = 'STAFF';
export const REVIEW_CATEGORY_VALUE_FOR_MONEY = 'VALUE_FOR_MONEY';
export const REVIEW_CATEGORY_FREE_WIFI = 'FREE_WIFI';
export const REVIEW_CATEGORY_FOOD_DRINK = 'FOOD_DRINK';
export const REVIEW_CATEGORY_HOTEL_CONDITION = 'HOTEL_CONDITION';
export const REVIEW_CATEGORY_POOL = 'POOL';

export const PRODUCT_SHOPPING_STATUS_SUCCESS = 'SUCCESS'
export const PRODUCT_SHOPPING_STATUS_SOLD_OUT = 'SOLD_OUT'
export const PRODUCT_SHOPPING_STATUS_NO_SPACE_AVAILABLE = 'NO_SPACE_AVAILABLE'
export const PRODUCT_SHOPPING_STATUS_PROPERTY_NOT_LISTED = 'PROPERTY_NOT_LISTED'
export const PRODUCT_SHOPPING_STATUS_UNKNOWN = 'UNKNOWN'

export const INVENTORY_ACCURACY_DAILY = 'DAILY';
export const INVENTORY_ACCURACY_HOURLY = 'HOURLY';

export const AGE_CODE_ADULT = 'A';
export const AGE_CODE_CHILD = 'C';

export const DEMAND_QUEUE_STATUS_IN_PROGRESS = "IN_PROGRESS";
export const DEMAND_QUEUE_STATUS_COMPLETED = "COMPLETED";
export const DEMAND_QUEUE_STATUS_FAILED = "FAILED";

export const HOTELOGIX_PMS_HNF_REPORT_V1 = 'HOTELOGIX_PMS_HNF_REPORT_FILE_V1'
export const SYSOTEL_PROPERTY_DEMAND_REPORT_V1 = 'SYSOTEL_AI_PROPERTY_DEMAND_REPORT_V1'

export const DATA_ACTIVITY_STATUS_SUCCESS = 'SUCCESS';
export const DATA_ACTIVITY_STATUS_PARTIAL_SUCCESS = 'PARTIAL_SUCCESS';
export const DATA_ACTIVITY_STATUS_FAILED = 'FAILED';
export const DATA_ACTIVITY_STATUS_PENDING = 'PENDING';

export const PROPERTY_REVIEW_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
export const PROPERTY_REVIEW_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
export const PROPERTY_REVIEW_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

export const CONFIG_STATUS_ONBOARDING = 'ONBOARDING';
export const CONFIG_STATUS_ACTIVE = 'ACTIVE';
export const CONFIG_STATUS_DISABLED = 'DISABLED';

export const ROUTINE_STATUS_ACTIVE = 'ACTIVE';
export const ROUTINE_STATUS_INACTIVE = 'INACTIVE';
export const ROUTINE_STATUS_DELETED = 'DELETED';

export const TASK_STATUS_PENDING = 'PENDING';
export const TASK_STATUS_PROCESSING = 'PROCESSING';
export const TASK_STATUS_SUCCESS = 'SUCCESS';
export const TASK_STATUS_FAILURE = 'FAILURE';
export const TASK_STATUS_FAILED = 'FAILED';
export const TASK_STATUS_ABORTED = 'ABORTED';

export const CHANNEL_ID_AI_REVIEWS = 'AI_REVIEWS';
export const CHANNEL_ID_AI_RATE_METRICS = 'AI_RATE_METRICS';

export const ROUTINE_CATEGORY_REVIEWS = 'REVIEWS';
export const ROUTINE_CATEGORY_RATE_SHOPPER = 'RATE_SHOPPER';

export const TASK_CATEGORY_REVIEWS = 'REVIEWS';
export const TASK_CATEGORY_RATE_SHOPPER = 'RATE_SHOPPER';
export const DATA_ACTIVITY_BLAME_INTERNAL = 'INTERNAL'
export const DATA_ACTIVITY_BLAME_EXTERNAL = 'EXTERNAL'
export const DATA_ACTIVITY_BLAME_UNKNOWN = 'UNKNOWN'
export const DATA_ACTIVITY_ERROR_CODE_TYPE_AUTH = 'AUTH'
export const DATA_ACTIVITY_ERROR_CODE_TYPE_VALIDATION = 'VALIDATION'
export const DATA_ACTIVITY_ERROR_CODE_TYPE_VENDOR_ERROR = 'VENDOR_ERROR'
export const DATA_ACTIVITY_ERROR_CODE_TYPE_INTERNAL = 'INTERNAL'
export const DATA_ACTIVITY_ERROR_CODE_TYPE_UNKNOWN = 'UNKNOWN'

export const DATA_ACTIVITY_ERROR_CODE_TYPE_OTHER = 'OTHER'
export const DATA_OUTPUT_TYPE_COMMENT = 'COMMENT'
export const DATA_OUTPUT_TYPE_INFO = 'INFO'
export const DATA_OUTPUT_TYPE_WARNING = 'WARNING'

export const DATA_OUTPUT_TYPE_ERROR = 'ERROR'
export const AI_RATE_QUEUE_STATUS_IN_COMPLETED = 'COMPLETED'
export const AI_RATE_QUEUE_STATUS_IN_TERMINATED_WITH_ERRORS = 'TERMINATED_WITH_ERRORS'
export const AI_RATE_QUEUE_STATUS_IN_TERMINATED_WITH_CREDIT_ERROR = 'TERMINATED_WITH_CREDIT_ERROR'
export const AI_RATE_QUEUE_STATUS_IN_RE_RUN_IN_PROGRESS = 'RE_RUN_IN_PROGRESS'
export const AI_RATE_QUEUE_STATUS_IN_UNKNOWN = 'UNKNOWN'
export const AI_DATA_ACTIVITY_STATUS_PENDING = 'PENDING'
export const AI_DATA_ACTIVITY_STATUS_SUCCESS = 'SUCCESS'
export const AI_DATA_ACTIVITY_STATUS_PARTIAL_SUCCESS = 'PARTIAL_SUCCESS'
export const AI_DATA_ACTIVITY_STATUS_FAILED = 'FAILED'
export const AI_DATA_ACTIVITY_STATUS_NO_EFFECT = 'NO_EFFECT'
export const REVIEW_TYPE_AI_REVIEWS_PULL_ALL = "AI_REVIEWS_PULL_ALL"
export const REVIEW_TYPE_AI_REVIEWS_PULL_PARTIAL = "AI_REVIEWS_PULL_PARTIAL"
export const REVIEW_TYPE_AI_REVIEWS_PULL_INSIGHTS = "AI_REVIEWS_PULL_INSIGHTS"
export const REVIEW_TYPE_RESAVENUE_CM_API_PULL_ALL_BOOKINGS = "RESAVENUE_CM_API_PULL_ALL_BOOKINGS"
export const REVIEW_TYPE_RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS = "RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS"
export const REVIEW_TYPE_AI_RATE_METRICS_ORDER_DISPATCHER = "AI_RATE_METRICS_ORDER_DISPATCHER"
export const REVIEW_TYPE_EDDI_SYNC_SCHEDULER = "EDDI_SYNC_SCHEDULER"
export const REVIEW_TYPE_EDDI_SYNC_CITY_EVENTS = "EDDI_SYNC_CITY_EVENTS"

export const API_LOGS_STATUS_PROCESSING = 'PROCESSING';
export const API_LOGS_STATUS_SUCCESS = 'SUCCESS';
export const API_LOGS_STATUS_FAILURE = 'FAILURE';
export const API_LOGS_STATUS_UNKNOWN = 'UNKNOWN';

export const API_LOGS_FORMAT_JSON = 'JSON';
export const API_LOGS_FORMAT_XML = 'XML';


export const API_LOGS_DIRECTION_INCOMING = 'INCOMING';
export const API_LOGS_DIRECTION_OUTGOING = 'OUTGOING';

export const API_LOGS_PROTOCOL_REST = 'REST';
export const API_LOGS_PROTOCOL_SOAP = 'SOAP';

export const API_LOGS_HTTP_METHOD_GET = 'GET';
export const API_LOGS_HTTP_METHOD_PUT = 'PUT';
export const API_LOGS_HTTP_METHOD_PATCH = 'PATCH';
export const API_LOGS_HTTP_METHOD_POST = 'POST';
export const API_LOGS_HTTP_METHOD_DELETE = 'DELETE';


export const API_LOGS_TYPE_DEMAND_AI_AUTH_TOKEN = 'DEMAND_AI_AUTH_TOKEN';
export const API_LOGS_TYPE_DEMAND_AI_CITY_DEMAND = 'DEMAND_AI_CITY_DEMAND';
export const API_LOGS_TYPE_DEMAND_AI_HOTEL_DEMAND = 'DEMAND_AI_HOTEL_DEMAND';
export const API_LOGS_TYPE_DEMAND_AI_AIRLINE_DATA = 'DEMAND_AI_AIRLINE_DATA';
export const API_LOGS_TYPE_RMS_REST_API_GET_CLIENT_URL = 'RMS_REST_API_GET_CLIENT_URL';
export const API_LOGS_TYPE_RMS_REST_API_GET_AUTH_TOKEN = 'RMS_REST_API_GET_AUTH_TOKEN';
export const API_LOGS_TYPE_RMS_REST_API_GET_AVAILABILITY_GRID = 'RMS_REST_API_GET_AVAILABILITY_GRID';
export const API_LOGS_TYPE_RMS_REST_API_RESERVATIONS_SEARCH = 'RMS_REST_API_RESERVATIONS_SEARCH';
export const API_LOGS_TYPE_RMS_REST_API_RESERVATIONS_ACTUAL_ACCOUNT = 'RMS_REST_API_RESERVATIONS_ACTUAL_ACCOUNT';
export const API_LOGS_TYPE_RESAVENUE_CM_API_PULL_INVENTORY = 'RESAVENUE_CM_API_PULL_INVENTORY';
export const API_LOGS_TYPE_RESAVENUE_CM_API_PULL_BOOKINGS = 'RESAVENUE_CM_API_PULL_BOOKINGS';
export const API_LOGS_TYPE_RESAVENUE_CM_API_PULL_RATES = 'RESAVENUE_CM_API_PULL_RATES';
export const API_LOGS_TYPE_GOOGLE_PLACES_API_GET_PLACE_DETAILS = 'GOOGLE_PLACES_API_GET_PLACE_DETAILS';
export const API_LOGS_TYPE_AI_REVIEWS_AUTH_TOKEN = 'AI_REVIEWS_AUTH_TOKEN';
export const API_LOGS_TYPE_AI_FETCH_REVIEWS = 'AI_FETCH_REVIEWS';
export const API_LOGS_TYPE_AI_FETCH_REVIEWS_INSIGHTS = 'AI_FETCH_REVIEWS_INSIGHTS';
export const API_LOGS_TYPE_AI_RATE_METRICS_AUTH_TOKEN = 'AI_RATE_METRICS_AUTH_TOKEN';
export const API_LOGS_TYPE_AI_RATE_METRICS_CREATE_RATE_SHOP = 'AI_RATE_METRICS_CREATE_RATE_SHOP';
export const API_LOGS_TYPE_AI_RATE_METRICS_RUN_RATE_SHOP = 'AI_RATE_METRICS_RUN_RATE_SHOP';
export const API_LOGS_TYPE_AI_RATE_METRICS_GET_RATES_BY_QUEUE = 'AI_RATE_METRICS_GET_RATES_BY_QUEUE';
export const API_LOGS_TYPE_AI_RATE_METRICS_GET_QUEUE_STATUS = 'AI_RATE_METRICS_GET_QUEUE_STATUS';
export const API_LOGS_TYPE_AI_EDDI_AUTH_TOKEN = 'AI_EDDI_AUTH_TOKEN';
export const API_LOGS_TYPE_AI_EDDI_DEMAND_SHOP_REQUEST = 'AI_EDDI_DEMAND_SHOP_REQUEST';
export const API_LOGS_TYPE_AI_EDDI_GET_DEMAND_DATA = 'AI_EDDI_GET_DEMAND_DATA';

export const PRODUCT_SHOPPING_STATUS_NO_SPACES_AVAILABLE = 'NO_SPACES_AVAILABLE'

export const SYSOTEL_AI_IYA = 'SYSOTEL_AI_IYA';
export const HOTELOGIX_PMS_HNF_REPORT_FILE_V1 = 'HOTELOGIX_PMS_HNF_REPORT_FILE_V1';
export const SYSOTEL_AI = 'SYSOTEL_AI';

export const UPLOAD_STATUS_ACCEPTED = 'ACCEPTED';
export const UPLOAD_STATUS_REJECTED = 'REJECTED';
export const SYSOTEL_AI_PROPERTY_DEMAND_V1 = 'SYSOTEL_AI_PROPERTY_DEMAND_V1';


export const AI_REVIEWS_PULL_ALL = 'AI_REVIEWS_PULL_ALL';
export const AI_REVIEWS_PULL_PARTIAL = 'AI_REVIEWS_PULL_PARTIAL';
export const AI_REVIEWS_PULL_INSIGHTS = 'AI_REVIEWS_PULL_INSIGHTS';
export const RESAVENUE_CM_API_PULL_ALL_BOOKINGS = 'RESAVENUE_CM_API_PULL_ALL_BOOKINGS';
export const RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS = 'RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS';
export const AI_RATE_METRICS_ORDER_DISPATCHER = 'AI_RATE_METRICS_ORDER_DISPATCHER';
export const EDDI_SYNC_SCHEDULER = 'EDDI_SYNC_SCHEDULER';
export const EDDI_SYNC_CITY_EVENTS = 'EDDI_SYNC_CITY_EVENTS';
export const AI_RATE_METRICS_PULL_QUEUE_DATA = 'AI_RATE_METRICS_PULL_QUEUE_DATA';
export const PROCESS_HOTELOGIX_PMS_BOOKING_HNF_REPORT_V1 = 'PROCESS_HOTELOGIX_PMS_BOOKING_HNF_REPORT_V1';
export const PROCESS_IDS_PMS_BOOKING_HNF_REPORT_V1 = 'PROCESS_IDS_PMS_BOOKING_HNF_REPORT_V1';
export const PROCESS_SYSOTEL_PROPERTY_DEMAND_V1 = 'PROCESS_SYSOTEL_PROPERTY_DEMAND_V1';
export const IDS_PMS_HNF_REPORT_FILE_V1 = 'IDS_PMS_HNF_REPORT_FILE_V1'
