module.exports.MARKET_CHANNEL_CLEARTRIP = 'CLEARTRIP';
module.exports.MARKET_CHANNEL_MAKEMYTRIP = 'MAKEMYTRIP';
module.exports.MARKET_CHANNEL_GOIBIBO = 'GOIBIBO';
module.exports.MARKET_CHANNEL_AGODA = 'AGODA';
module.exports.MARKET_CHANNEL_EXPEDIA = 'EXPEDIA';
module.exports.MARKET_CHANNEL_TRAVEL_GURU = 'TRAVEL_GURU';
module.exports.MARKET_CHANNEL_BOOKING_DOT_COM = 'BOOKING_DOT_COM';
module.exports.MARKET_CHANNEL_VIA = 'VIA';
module.exports.MARKET_CHANNEL_HOTELS_COMBINED = 'HOTELS_COMBINED';
module.exports.MARKET_CHANNEL_ONLINE_GDS = 'ONLINE_GDS';
module.exports.MARKET_CHANNEL_MR_AND_MRS_SMITH = 'MR_AND_MRS_SMITH';
module.exports.MARKET_CHANNEL_HOTELS_BED = 'HOTELS_BED';
module.exports.MARKET_CHANNEL_WELCOM_HERITAGE = 'Welcom_HERITAGE';
module.exports.MARKET_CHANNEL_DOTW = 'DOTW';
module.exports.MARKET_CHANNEL_SIMPLOTEL = 'SIMPLOTEL';
module.exports.MARKET_CHANNEL_HRS = 'HRS';
module.exports.MARKET_CHANNEL_EASE_MY_TRIP = 'EASE_MY_TRIP';
module.exports.MARKET_CHANNEL_TRIP_DOT_COM = 'TRIP_DOT_COM';
module.exports.MARKET_CHANNEL_TRIPADVISOR = 'TRIPADVISOR';
module.exports.MARKET_CHANNEL_PAYTM = 'PAYTM';
module.exports.MARKET_CHANNEL_TRAVELIKO = 'TRAVELIKO';
module.exports.MARKET_CHANNEL_HAPPY_EASY_GO = 'HAPPY_EASY_GO';
module.exports.MARKET_CHANNEL_HOBSE = 'HOBSE';
module.exports.MARKET_CHANNEL_BOOK_LOGIC = 'BOOK_LOGIC';
module.exports.MARKET_CHANNEL_IRCTC = 'IRCTC';
module.exports.MARKET_CHANNEL_XENIA = 'XENIA';
module.exports.MARKET_CHANNEL_CHANNEX = 'CHANNEX';
module.exports.MARKET_CHANNEL_RESAVENUE_PMS = 'RESAVENUE_PMS';
module.exports.MARKET_CHANNEL_TOUR_MY_INDIA = 'TOUR_MY_INDIA';
module.exports.MARKET_CHANNEL_VEEKEND = 'VEEKEND';
module.exports.MARKET_CHANNEL_ONE_FINE_RATE = 'ONE_FINE_RATE';
module.exports.MARKET_CHANNEL_SYSOTEL = 'SYSOTEL';
module.exports.MARKET_CHANNEL_HOTLA = 'HOTLA';
module.exports.MARKET_CHANNEL_TRAVIATE = 'TRAVIATE';
module.exports.MARKET_CHANNEL_ONLINE_VACATIONS = 'ONLINE_VACATIONS';
module.exports.MARKET_CHANNEL_ROOM_STATUS_HUB = 'ROOM_STATUS_HUB';
module.exports.MARKET_CHANNEL_TRAVEL_BOUTIQUE = 'TRAVEL_BOUTIQUE';
module.exports.MARKET_CHANNEL_HOSTEL_WORLD = 'HOSTEL_WORLD';
module.exports.MARKET_CHANNEL_GOOGLE = 'GOOGLE';
module.exports.MARKET_CHANNEL_HOTELS_DOT_COM = 'HOTELS_DOT_COM';
module.exports.MARKET_CHANNEL_PRICELINE = 'PRICELINE';
module.exports.MARKET_CHANNEL_ORBITZ = 'ORBITZ';
module.exports.MARKET_CHANNEL_IHG_DOT_COM = 'IHG_DOT_COM';
module.exports.MARKET_CHANNEL_MARRIOTT = 'MARRIOTT';
module.exports.MARKET_CHANNEL_RADISSONCOM = 'RADISSONCOM';
module.exports.MARKET_CHANNEL_HILTON = 'HILTON';
module.exports.MARKET_CHANNEL_BOOKBESTWESTERNCOM = 'BOOKBESTWESTERNCOM';
module.exports.MARKET_CHANNEL_HRSCOM = 'HRSCOM';
module.exports.MARKET_CHANNEL_ACCORHOTELS = 'ACCORHOTELS';
module.exports.MARKET_CHANNEL_JUMIA = 'JUMIA';
module.exports.MARKET_CHANNEL_YATRA = 'YATRA';
module.exports.MARKET_CHANNEL_HOSTELWORLD = 'HOSTELWORLD';
module.exports.MARKET_CHANNEL_LATEROOMS = 'LATEROOMS';
module.exports.MARKET_CHANNEL_SPLENDIA = 'SPLENDIA';
module.exports.MARKET_CHANNEL_BESTDAY = 'BESTDAY';
module.exports.MARKET_CHANNEL_PRICETRAVEL = 'PRICETRAVEL';
module.exports.MARKET_CHANNEL_AIRBNB = 'AIRBNB';
module.exports.MARKET_CHANNEL_LASTMINUTE_DOT_COM = 'LASTMINUTE_DOT_COM';
module.exports.MARKET_CHANNEL_TRAVELOKA = 'TRAVELOKA';
module.exports.MARKET_CHANNEL_HOTELLOOK = 'HOTELLOOK';
module.exports.MARKET_CHANNEL_OSTROVOK = 'OSTROVOK';
module.exports.MARKET_CHANNEL_PEGIPEGI = 'PEGIPEGI';
module.exports.MARKET_CHANNEL_TIKET = 'TIKET';
module.exports.MARKET_CHANNEL_RAKUTEN = 'RAKUTEN';
module.exports.MARKET_CHANNEL_CTRIP = 'CTRIP';
module.exports.MARKET_CHANNEL_TRAVELREPUBLIC = 'TRAVELREPUBLIC';
module.exports.MARKET_CHANNEL_MRANDMRSSMITH = 'MRANDMRSSMITH';
module.exports.MARKET_CHANNEL_FABHOTELS = 'FABHOTELS';
module.exports.MARKET_CHANNEL_TREEBO = 'TREEBO';
module.exports.MARKET_CHANNEL_HOLIDAYCHECK = 'HOLIDAYCHECK';
module.exports.MARKET_CHANNEL_TRAVELOCITY = 'TRAVELOCITY';
module.exports.MARKET_CHANNEL_CHEAPTICKETS = 'CHEAPTICKETS';
module.exports.MARKET_CHANNEL_EBOOKERS = 'EBOOKERS';
module.exports.MARKET_CHANNEL_DESPEGAR = 'DESPEGAR';
module.exports.MARKET_CHANNEL_MEITUAN = 'MEITUAN';
module.exports.MARKET_CHANNEL_BOOKINGS_FLIGHTEXPERT_COM = 'BOOKINGS_FLIGHTEXPERT_COM';
module.exports.MARKET_CHANNEL_SHARETRIP = 'SHARETRIP';
module.exports.MARKET_CHANNEL_GOZAYAAN = 'GOZAYAAN';
module.exports.MARKET_CHANNEL_RURUBU = 'RURUBU';
module.exports.MARKET_CHANNEL_BE_SYNXIS_COM = 'BE_SYNXIS_COM';
module.exports.MARKET_CHANNEL_WORLDROAMER = 'WORLDROAMER';
module.exports.MARKET_CHANNEL_MYKONOS = 'MYKONOS';
module.exports.MARKET_CHANNEL_BOOK_RGUEST_COM = 'BOOK_RGUEST_COM';
module.exports.MARKET_CHANNEL_BOOKINGS_HOTELREZ_CO_UK = 'BOOKINGS_HOTELREZ_CO_UK';
module.exports.MARKET_CHANNEL_SECURE_HOTEL_BOOKING = 'SECURE_HOTEL_BOOKING';
module.exports.MARKET_CHANNEL_SHOUSUGIBANHOUSE = 'SHOUSUGIBANHOUSE';
module.exports.MARKET_CHANNEL_RSWS_KRIPALU = 'RSWS_KRIPALU';
module.exports.MARKET_CHANNEL_TUI = 'TUI';
module.exports.MARKET_CHANNEL_GRANDBARAKA_HOTEL = 'GRANDBARAKA_HOTEL';
module.exports.MARKET_CHANNEL_WEBHOTELIER = 'WEBHOTELIER';
module.exports.MARKET_CHANNEL_BLASTNESS = 'BLASTNESS';
module.exports.MARKET_CHANNEL_BOOK_SECURE = 'BOOK_SECURE';
module.exports.MARKET_CHANNEL_VERTICAL_BOOKING = 'VERTICAL_BOOKING';
module.exports.MARKET_CHANNEL_DIRECT_BOOK = 'DIRECT_BOOK';
module.exports.MARKET_CHANNEL_EURO_STARS_HOTELS = 'EURO_STARS_HOTELS';
module.exports.MARKET_CHANNEL_HOTEL_ZIMBROS = 'HOTEL_ZIMBROS';
module.exports.MARKET_CHANNEL_BOOK_OMNIBEES = 'BOOK_OMNIBEES';
module.exports.MARKET_CHANNEL_HF_HOTELS = 'HF_HOTELS';
module.exports.MARKET_CHANNEL_REHLAT = 'REHLAT';
module.exports.MARKET_CHANNEL_SESIMBRA_HOTEL_SPA = 'SESIMBRA_HOTEL_SPA';
module.exports.MARKET_CHANNEL_ONE_PAGE_BOOKING = 'ONE_PAGE_BOOKING';
module.exports.MARKET_CHANNEL_ADAGIO_CITY = 'ADAGIO_CITY';
module.exports.MARKET_CHANNEL_MASA_HOTEL = 'MASA_HOTEL';
module.exports.MARKET_CHANNEL_BOOKING_CAMPING = 'BOOKING_CAMPING';
module.exports.MARKET_CHANNEL_BOOKING_EXPERT = 'BOOKING_EXPERT';
module.exports.MARKET_CHANNEL_SCIDOO = 'SCIDOO';
module.exports.MARKET_CHANNEL_H10_HOTELS = 'H10_HOTELS';
module.exports.MARKET_CHANNEL_D_EDGE = 'D_EDGE';
module.exports.MARKET_CHANNEL_SECURE_IPER_BOOKING = 'SECURE_IPER_BOOKING';
module.exports.MARKET_CHANNEL_E_GDS = 'E_GDS';
module.exports.MARKET_CHANNEL_HU_OPEN_AIR = 'HU_OPEN_AIR';
module.exports.MARKET_CHANNEL_ORLANDO_INCHIANTI = 'ORLANDO_INCHIANTI';
module.exports.MARKET_CHANNEL_NET_BOOKING_NATURAL_BOOKING = 'NET_BOOKING_NATURAL_BOOKING';
module.exports.MARKET_CHANNEL_CAMPING_SERENO = 'CAMPING_SERENO';
module.exports.MARKET_CHANNEL_CAMPING_CISANO = 'CAMPING_CISANO';
module.exports.MARKET_CHANNEL_ICONNECT_PRENOTA_ONLINE = 'ICONNECT_PRENOTA_ONLINE';
module.exports.MARKET_CHANNEL_PALACIO_ESTORIL_HOTEL = 'PALACIO_ESTORIL_HOTEL';
module.exports.MARKET_CHANNEL_BOOKING_PREMIUM_SECURE_HOLIDAY = 'BOOKING_PREMIUM_SECURE_HOLIDAY';
module.exports.MARKET_CHANNEL_SECURE_GUEST_CENTRIC = 'SECURE_GUEST_CENTRIC';
module.exports.MARKET_CHANNEL_ALL_CAMPS = 'ALL_CAMPS';
module.exports.MARKET_CHANNEL_DOMPEDRO = 'DOMPEDRO';
module.exports.MARKET_CHANNEL_RESERVAS_VILAGALE = 'RESERVAS_VILAGALE';
module.exports.MARKET_CHANNEL_HOTEL_BB = 'HOTEL_BB';
module.exports.MARKET_CHANNEL_SIMPLE_BOOKING = 'SIMPLE_BOOKING';
module.exports.MARKET_CHANNEL_ABBA_HOTELES = 'ABBA_HOTELES';
module.exports.MARKET_CHANNEL_LOHONO = 'LOHONO';
module.exports.MARKET_CHANNEL_SAFFRON_STAYS = 'SAFFRON_STAYS';
module.exports.MARKET_CHANNEL_A_HOTEL = 'A_HOTEL';
module.exports.MARKET_CHANNEL_TRAVEL_CLICK = 'TRAVEL_CLICK';
module.exports.MARKET_CHANNEL_DEIFIORI = 'DEIFIORI';
module.exports.MARKET_CHANNEL_BAIA_HOLIDAY = 'BAIA_HOLIDAY';
module.exports.MARKET_CHANNEL_UNION_LIDO = 'UNION_LIDO';
module.exports.MARKET_CHANNEL_IBEROSTAR = 'IBEROSTAR';
module.exports.MARKET_CHANNEL_BOOK_CORE = 'BOOK_CORE';
module.exports.MARKET_CHANNEL_RIU = 'RIU';
module.exports.MARKET_CHANNEL_MIRAI = 'MIRAI';
module.exports.MARKET_CHANNEL_SECURE_BOOKING = 'SECURE_BOOKING';
module.exports.MARKET_CHANNEL_BOOKING_MY_GUEST_CARE = 'BOOKING_MY_GUEST_CARE';
module.exports.MARKET_CHANNEL_CINEMA_8 = 'CINEMA 8';
module.exports.MARKET_CHANNEL_ERICSOFT = 'ERICSOFT';
module.exports.MARKET_CHANNEL_QUICK_BOOKING = 'QUICK_BOOKING';
module.exports.MARKET_CHANNEL_HOTELS_EDREAMS = 'HOTELS_EDREAMS';
module.exports.MARKET_CHANNEL_TRAVEL = 'TRAVEL';
module.exports.MARKET_CHANNEL_HOTELS_CTRIP_COM = 'HOTELS_CTRIP_COM';

module.exports.COMPETITION_STATUS_ACTIVE = 'ACTIVE';
module.exports.COMPETITION_STATUS_DISABLED = 'DISABLED';
module.exports.COMPETITION_STATUS_ONBOARDING = 'ONBOARDING';

module.exports.COMPETITION_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
module.exports.COMPETITION_ONBOARDING_STATUS_REJECTED = 'REJECTED';
module.exports.COMPETITION_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
module.exports.COMPETITION_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

module.exports.COMPETITION_SETUP_PROMOTION = 'PROMOTION'
module.exports.COMPETITION_SETUP_PROMO_CODE = 'PROMO_CODE'

module.exports.PROPERTY_REVIEW_ACTIVITY_METHOD_NO_EFFECT = 'NO_EFFECT';

module.exports.BUDGET_SETUP_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
module.exports.BUDGET_SETUP_ONBOARDING_STATUS_REJECTED = 'REJECTED';
module.exports.BUDGET_SETUP_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
module.exports.BUDGET_SETUP_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';
module.exports.BUDGET_SETUP_STATUS_ACTIVE = 'ACTIVE';
module.exports.BUDGET_SETUP_STATUS_DISABLED = 'DISABLED';
module.exports.BUDGET_SETUP_STATUS_ONBOARDING = 'ONBOARDING';

module.exports.AI_RATE_QUEUE_STATUS_IN_PROGRESS = "IN_PROGRESS";
module.exports.AI_RATE_QUEUE_STATUS_COMPLETED = "COMPLETED";
module.exports.AI_RATE_QUEUE_STATUS_TERMINATED_WITH_ERRORS = "TERMINATED_WITH_ERRORS";
module.exports.AI_RATE_QUEUE_STATUS_TERMINATED_WITH_CREDIT_ERROR = "TERMINATED_WITH_CREDIT_ERROR";
module.exports.AI_RATE_QUEUE_STATUS_RE_RUN_IN_PROGRESS = "RE_RUN_IN_PROGRESS";
module.exports.AI_RATE_QUEUE_STATUS_UNKNOWN = "UNKNOWN";

module.exports.AI_RATE_QUEUE_ATTEMPT_STATUS_PENDING = "PENDING";
module.exports.AI_RATE_QUEUE_ATTEMPT_STATUS_SUCCESS = "SUCCESS";
module.exports.AI_RATE_QUEUE_ATTEMPT_STATUS_FAILED = "FAILED";
module.exports.AI_RATE_QUEUE_ATTEMPT_STATUS_EXPIRED = "EXPIRED";
module.exports.AI_RATE_QUEUE_ATTEMPT_STATUS_PARTIAL_SUCCESS =  "PARTIAL_SUCCESS";

module.exports.BOOKING_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
module.exports.BOOKING_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
module.exports.BOOKING_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

module.exports.RATE_SHOPPING_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
module.exports.RATE_SHOPPING_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
module.exports.RATE_SHOPPING_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

module.exports.REVIEW_INSIGHTS_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
module.exports.REVIEW_INSIGHTS_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
module.exports.REVIEW_INSIGHTS_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

module.exports.TASK_ATTEMPT_STATUS_SUCCESS = 'SUCCESS';
module.exports.TASK_ATTEMPT_STATUS_FAILURE = 'FAILURE';

module.exports.RMS_REST_API = 'RMS_REST_API';
module.exports.RESAVENUE_CM_API = 'RESAVENUE_CM_API';
module.exports.RATE_GAIN_DEMAND_AI = 'RATE_GAIN_DEMAND_AI';
module.exports.AI_RATE_METRICS = 'AI_RATE_METRICS';
module.exports.AI_REVIEWS = 'AI_REVIEWS';
module.exports.AI_EDDI = 'AI_EDDI';

module.exports.REVIEW_CATEGORY_SERVICE = 'SERVICE';
module.exports.REVIEW_CATEGORY_CLEANLINESS = 'CLEANLINESS';
module.exports.REVIEW_CATEGORY_SLEEP_QUALITY = 'SLEEP_QUALITY';
module.exports.REVIEW_CATEGORY_LOCATION = 'LOCATION';
module.exports.REVIEW_CATEGORY_SPACE = 'SPACE';
module.exports.REVIEW_CATEGORY_BREAKFAST = 'BREAKFAST';
module.exports.REVIEW_CATEGORY_VALUE = 'VALUE';
module.exports.REVIEW_CATEGORY_SPA = 'SPA';
module.exports.REVIEW_CATEGORY_ROOM = 'ROOM';
module.exports.REVIEW_CATEGORY_COMFORT = 'COMFORT';
module.exports.REVIEW_CATEGORY_FACILITIES = 'FACILITIES';
module.exports.REVIEW_CATEGORY_STAFF = 'STAFF';
module.exports.REVIEW_CATEGORY_VALUE_FOR_MONEY = 'VALUE_FOR_MONEY';
module.exports.REVIEW_CATEGORY_FREE_WIFI = 'FREE_WIFI';
module.exports.REVIEW_CATEGORY_FOOD_DRINK = 'FOOD_DRINK';
module.exports.REVIEW_CATEGORY_HOTEL_CONDITION = 'HOTEL_CONDITION';
module.exports.REVIEW_CATEGORY_POOL = 'POOL';

module.exports.PRODUCT_SHOPPING_STATUS_SUCCESS = 'SUCCESS'
module.exports.PRODUCT_SHOPPING_STATUS_SOLD_OUT = 'SOLD_OUT'
module.exports.PRODUCT_SHOPPING_STATUS_NO_SPACE_AVAILABLE = 'NO_SPACE_AVAILABLE'
module.exports.PRODUCT_SHOPPING_STATUS_PROPERTY_NOT_LISTED = 'PROPERTY_NOT_LISTED'
module.exports.PRODUCT_SHOPPING_STATUS_UNKNOWN = 'UNKNOWN'

module.exports.INVENTORY_ACCURACY_DAILY = 'DAILY';
module.exports.INVENTORY_ACCURACY_HOURLY = 'HOURLY';

module.exports.AGE_CODE_ADULT = 'A';
module.exports.AGE_CODE_CHILD = 'C';

module.exports.DEMAND_QUEUE_STATUS_IN_PROGRESS = "IN_PROGRESS";
module.exports.DEMAND_QUEUE_STATUS_COMPLETED = "COMPLETED";
module.exports.DEMAND_QUEUE_STATUS_FAILED = "FAILED";

module.exports.HOTELOGIX_PMS_HNF_REPORT_V1 = 'HOTELOGIX_PMS_HNF_REPORT_FILE_V1'
module.exports.SYSOTEL_PROPERTY_DEMAND_REPORT_V1 = 'SYSOTEL_AI_PROPERTY_DEMAND_REPORT_V1'

module.exports.DATA_ACTIVITY_STATUS_SUCCESS = 'SUCCESS';
module.exports.DATA_ACTIVITY_STATUS_PARTIAL_SUCCESS = 'PARTIAL_SUCCESS';
module.exports.DATA_ACTIVITY_STATUS_FAILED = 'FAILED';
module.exports.DATA_ACTIVITY_STATUS_PENDING = 'PENDING';

module.exports.PROPERTY_REVIEW_ACTIVITY_METHOD_ROUTINE = 'ROUTINE';
module.exports.PROPERTY_REVIEW_ACTIVITY_METHOD_EXTRANET_USER_TRIGGERED = 'EXTRANET_USER_TRIGGERED';
module.exports.PROPERTY_REVIEW_ACTIVITY_METHOD_ADMIN_TRIGGERED = 'ADMIN_TRIGGERED';

module.exports.CONFIG_STATUS_ONBOARDING = 'ONBOARDING';
module.exports.CONFIG_STATUS_ACTIVE = 'ACTIVE';
module.exports.CONFIG_STATUS_DISABLED = 'DISABLED';

module.exports.ROUTINE_STATUS_ACTIVE = 'ACTIVE';
module.exports.ROUTINE_STATUS_INACTIVE = 'INACTIVE';
module.exports.ROUTINE_STATUS_DELETED = 'DELETED';

module.exports.TASK_STATUS_PENDING = 'PENDING';
module.exports.TASK_STATUS_PROCESSING = 'PROCESSING';
module.exports.TASK_STATUS_SUCCESS = 'SUCCESS';
module.exports.TASK_STATUS_FAILURE = 'FAILURE';
module.exports.TASK_STATUS_FAILED = 'FAILED';
module.exports.TASK_STATUS_ABORTED = 'ABORTED';

module.exports.CHANNEL_MANAGER_IDS_NEXT = 'IDS_NEXT';
module.exports.CHANNEL_MANAGER_HOTELOGIX = 'HOTELOGIX';
module.exports.CHANNEL_MANAGER_WINCLOUD = 'WINCLOUD';
module.exports.CHANNEL_MANAGER_MAXIMOJO = 'MAXIMOJO';
module.exports.CHANNEL_MANAGER_RMS = 'RMS';
module.exports.CHANNEL_MANAGER_GOOGLE = 'GOOGLE';
module.exports.CHANNEL_MANAGER_RESAVENUE = 'RESAVENUE';

module.exports.CHANNEL_ID_AI_REVIEWS = 'AI_REVIEWS';
module.exports.CHANNEL_ID_AI_RATE_METRICS = 'AI_RATE_METRICS';

module.exports.ROUTINE_CATEGORY_REVIEWS = 'REVIEWS';
module.exports.ROUTINE_CATEGORY_RATE_SHOPPER = 'RATE_SHOPPER';

module.exports.TASK_CATEGORY_REVIEWS = 'REVIEWS';
module.exports.TASK_CATEGORY_RATE_SHOPPER = 'RATE_SHOPPER';
module.exports.DATA_ACTIVITY_BLAME_INTERNAL = 'INTERNAL'
module.exports.DATA_ACTIVITY_BLAME_EXTERNAL = 'EXTERNAL'
module.exports.DATA_ACTIVITY_BLAME_UNKNOWN = 'UNKNOWN'
module.exports.DATA_ACTIVITY_ERROR_CODE_TYPE_AUTH = 'AUTH'
module.exports.DATA_ACTIVITY_ERROR_CODE_TYPE_VALIDATION = 'VALIDATION'
module.exports.DATA_ACTIVITY_ERROR_CODE_TYPE_VENDOR_ERROR = 'VENDOR_ERROR'
module.exports.DATA_ACTIVITY_ERROR_CODE_TYPE_INTERNAL = 'INTERNAL'
module.exports.DATA_ACTIVITY_ERROR_CODE_TYPE_UNKNOWN = 'UNKNOWN'

module.exports.DATA_ACTIVITY_ERROR_CODE_TYPE_OTHER = 'OTHER'
module.exports.DATA_OUTPUT_TYPE_COMMENT = 'COMMENT'
module.exports.DATA_OUTPUT_TYPE_INFO = 'INFO'
module.exports.DATA_OUTPUT_TYPE_WARNING = 'WARNING'

module.exports.DATA_OUTPUT_TYPE_ERROR = 'ERROR'
module.exports.AI_RATE_QUEUE_STATUS_IN_COMPLETED = 'COMPLETED'
module.exports.AI_RATE_QUEUE_STATUS_IN_TERMINATED_WITH_ERRORS = 'TERMINATED_WITH_ERRORS'
module.exports.AI_RATE_QUEUE_STATUS_IN_TERMINATED_WITH_CREDIT_ERROR = 'TERMINATED_WITH_CREDIT_ERROR'
module.exports.AI_RATE_QUEUE_STATUS_IN_RE_RUN_IN_PROGRESS = 'RE_RUN_IN_PROGRESS'
module.exports.AI_RATE_QUEUE_STATUS_IN_UNKNOWN = 'UNKNOWN'
module.exports.AI_DATA_ACTIVITY_STATUS_PENDING = 'PENDING'
module.exports.AI_DATA_ACTIVITY_STATUS_SUCCESS = 'SUCCESS'
module.exports.AI_DATA_ACTIVITY_STATUS_PARTIAL_SUCCESS = 'PARTIAL_SUCCESS'
module.exports.AI_DATA_ACTIVITY_STATUS_FAILED = 'FAILED'
module.exports.AI_DATA_ACTIVITY_STATUS_NO_EFFECT = 'NO_EFFECT'
module.exports.REVIEW_TYPE_AI_REVIEWS_PULL_ALL = "AI_REVIEWS_PULL_ALL"
module.exports.REVIEW_TYPE_AI_REVIEWS_PULL_PARTIAL = "AI_REVIEWS_PULL_PARTIAL"
module.exports.REVIEW_TYPE_AI_REVIEWS_PULL_INSIGHTS = "AI_REVIEWS_PULL_INSIGHTS"
module.exports.REVIEW_TYPE_RESAVENUE_CM_API_PULL_ALL_BOOKINGS = "RESAVENUE_CM_API_PULL_ALL_BOOKINGS"
module.exports.REVIEW_TYPE_RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS = "RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS"
module.exports.REVIEW_TYPE_AI_RATE_METRICS_ORDER_DISPATCHER = "AI_RATE_METRICS_ORDER_DISPATCHER"
module.exports.REVIEW_TYPE_EDDI_SYNC_SCHEDULER = "EDDI_SYNC_SCHEDULER"
module.exports.REVIEW_TYPE_EDDI_SYNC_CITY_EVENTS = "EDDI_SYNC_CITY_EVENTS"

module.exports.API_LOGS_STATUS_PROCESSING = 'PROCESSING';
module.exports.API_LOGS_STATUS_SUCCESS = 'SUCCESS';
module.exports.API_LOGS_STATUS_FAILURE = 'FAILURE';
module.exports.API_LOGS_STATUS_UNKNOWN = 'UNKNOWN';

module.exports.API_LOGS_FORMAT_JSON = 'JSON';
module.exports.API_LOGS_FORMAT_XML = 'XML';


module.exports.API_LOGS_DIRECTION_INCOMING = 'INCOMING';
module.exports.API_LOGS_DIRECTION_OUTGOING = 'OUTGOING';

module.exports.API_LOGS_PROTOCOL_REST = 'REST';
module.exports.API_LOGS_PROTOCOL_SOAP = 'SOAP';

module.exports.API_LOGS_HTTP_METHOD_GET = 'GET';
module.exports.API_LOGS_HTTP_METHOD_PUT = 'PUT';
module.exports.API_LOGS_HTTP_METHOD_PATCH = 'PATCH';
module.exports.API_LOGS_HTTP_METHOD_POST = 'POST';
module.exports.API_LOGS_HTTP_METHOD_DELETE = 'DELETE';


module.exports.API_LOGS_TYPE_DEMAND_AI_AUTH_TOKEN = 'DEMAND_AI_AUTH_TOKEN';
module.exports.API_LOGS_TYPE_DEMAND_AI_CITY_DEMAND = 'DEMAND_AI_CITY_DEMAND';
module.exports.API_LOGS_TYPE_DEMAND_AI_HOTEL_DEMAND = 'DEMAND_AI_HOTEL_DEMAND';
module.exports.API_LOGS_TYPE_DEMAND_AI_AIRLINE_DATA = 'DEMAND_AI_AIRLINE_DATA';
module.exports.API_LOGS_TYPE_RMS_REST_API_GET_CLIENT_URL = 'RMS_REST_API_GET_CLIENT_URL';
module.exports.API_LOGS_TYPE_RMS_REST_API_GET_AUTH_TOKEN = 'RMS_REST_API_GET_AUTH_TOKEN';
module.exports.API_LOGS_TYPE_RMS_REST_API_GET_AVAILABILITY_GRID = 'RMS_REST_API_GET_AVAILABILITY_GRID';
module.exports.API_LOGS_TYPE_RMS_REST_API_RESERVATIONS_SEARCH = 'RMS_REST_API_RESERVATIONS_SEARCH';
module.exports.API_LOGS_TYPE_RMS_REST_API_RESERVATIONS_ACTUAL_ACCOUNT = 'RMS_REST_API_RESERVATIONS_ACTUAL_ACCOUNT';
module.exports.API_LOGS_TYPE_RESAVENUE_CM_API_PULL_INVENTORY = 'RESAVENUE_CM_API_PULL_INVENTORY';
module.exports.API_LOGS_TYPE_RESAVENUE_CM_API_PULL_BOOKINGS = 'RESAVENUE_CM_API_PULL_BOOKINGS';
module.exports.API_LOGS_TYPE_RESAVENUE_CM_API_PULL_RATES = 'RESAVENUE_CM_API_PULL_RATES';
module.exports.API_LOGS_TYPE_GOOGLE_PLACES_API_GET_PLACE_DETAILS = 'GOOGLE_PLACES_API_GET_PLACE_DETAILS';
module.exports.API_LOGS_TYPE_AI_REVIEWS_AUTH_TOKEN = 'AI_REVIEWS_AUTH_TOKEN';
module.exports.API_LOGS_TYPE_AI_FETCH_REVIEWS = 'AI_FETCH_REVIEWS';
module.exports.API_LOGS_TYPE_AI_FETCH_REVIEWS_INSIGHTS = 'AI_FETCH_REVIEWS_INSIGHTS';
module.exports.API_LOGS_TYPE_AI_RATE_METRICS_AUTH_TOKEN = 'AI_RATE_METRICS_AUTH_TOKEN';
module.exports.API_LOGS_TYPE_AI_RATE_METRICS_CREATE_RATE_SHOP = 'AI_RATE_METRICS_CREATE_RATE_SHOP';
module.exports.API_LOGS_TYPE_AI_RATE_METRICS_RUN_RATE_SHOP = 'AI_RATE_METRICS_RUN_RATE_SHOP';
module.exports.API_LOGS_TYPE_AI_RATE_METRICS_GET_RATES_BY_QUEUE = 'AI_RATE_METRICS_GET_RATES_BY_QUEUE';
module.exports.API_LOGS_TYPE_AI_RATE_METRICS_GET_QUEUE_STATUS = 'AI_RATE_METRICS_GET_QUEUE_STATUS';
module.exports.API_LOGS_TYPE_AI_EDDI_AUTH_TOKEN = 'AI_EDDI_AUTH_TOKEN';
module.exports.API_LOGS_TYPE_AI_EDDI_DEMAND_SHOP_REQUEST = 'AI_EDDI_DEMAND_SHOP_REQUEST';
module.exports.API_LOGS_TYPE_AI_EDDI_GET_DEMAND_DATA = 'AI_EDDI_GET_DEMAND_DATA';

module.exports.PRODUCT_SHOPPING_STATUS_NO_SPACES_AVAILABLE = 'NO_SPACES_AVAILABLE'

module.exports.SYSOTEL_AI_IYA = 'SYSOTEL_AI_IYA';
module.exports.SYSOTEL_CMS_OPEN_API = 'SYSOTEL_CMS_OPEN_API';
module.exports.HOTELOGIX_PMS_HNF_REPORT_FILE_V1 = 'HOTELOGIX_PMS_HNF_REPORT_FILE_V1';
module.exports.SYSOTEL_AI = 'SYSOTEL_AI';

module.exports.UPLOAD_STATUS_ACCEPTED = 'ACCEPTED';
module.exports.UPLOAD_STATUS_REJECTED = 'REJECTED';
module.exports.SYSOTEL_AI_PROPERTY_DEMAND_V1 = 'SYSOTEL_AI_PROPERTY_DEMAND_V1';

module.exports.AI_REVIEWS_PULL_ALL = 'AI_REVIEWS_PULL_ALL';
module.exports.AI_REVIEWS_PULL_PARTIAL = 'AI_REVIEWS_PULL_PARTIAL';
module.exports.AI_REVIEWS_PULL_INSIGHTS = 'AI_REVIEWS_PULL_INSIGHTS';
module.exports.RESAVENUE_CM_API_PULL_ALL_BOOKINGS = 'RESAVENUE_CM_API_PULL_ALL_BOOKINGS';
module.exports.RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS = 'RESAVENUE_CM_API_PULL_PARTIAL_BOOKINGS';
module.exports.AI_RATE_METRICS_ORDER_DISPATCHER = 'AI_RATE_METRICS_ORDER_DISPATCHER';
module.exports.EDDI_SYNC_SCHEDULER = 'EDDI_SYNC_SCHEDULER';
module.exports.EDDI_SYNC_CITY_EVENTS = 'EDDI_SYNC_CITY_EVENTS';
module.exports.AI_RATE_METRICS_PULL_QUEUE_DATA = 'AI_RATE_METRICS_PULL_QUEUE_DATA';
module.exports.PROCESS_HOTELOGIX_PMS_BOOKING_HNF_REPORT_V1 = 'PROCESS_HOTELOGIX_PMS_BOOKING_HNF_REPORT_V1';
module.exports.PROCESS_IDS_PMS_BOOKING_HNF_REPORT_V1 = 'PROCESS_IDS_PMS_BOOKING_HNF_REPORT_V1';
module.exports.PROCESS_SYSOTEL_PROPERTY_DEMAND_V1 = 'PROCESS_SYSOTEL_PROPERTY_DEMAND_V1';
module.exports.IDS_PMS_HNF_REPORT_FILE_V1 = 'IDS_PMS_HNF_REPORT_FILE_V1'

module.exports.EVENT_CATGEGORY_ENTERTAINMENT = 'ENTERTAINMENT';
module.exports.EVENT_CATGEGORY_HOLIDAYS_FESTIVAL_CELEBRATIONS = 'HOLIDAYS_FESTIVAL_CELEBRATIONS';
module.exports.EVENT_CATGEGORY_SPORTS = 'SPORTS';
module.exports.EVENT_CATGEGORY_TRADE_SHOW_BUSINESS_CONFERENCE = 'TRADE_SHOW_BUSINESS_CONFERENCE';
module.exports.EVENT_CATGEGORY_COMMUNITY = 'COMMUNITY';

// EVENT SUB CATEGORIES

module.exports.EVENT_SUBCATGEGORY_ARTS = 'ARTS';
module.exports.EVENT_SUBCATGEGORY_CONCERTS = 'CONCERTS';
module.exports.EVENT_SUBCATGEGORY_THEATRE = 'THEATRE';
module.exports.EVENT_SUBCATGEGORY_DANCE = 'DANCE';
module.exports.EVENT_SUBCATGEGORY_COMEDY = 'COMEDY';
module.exports.EVENT_SUBCATGEGORY_FAMILY_AND_KIDS = 'FAMILY_AND_KIDS';
module.exports.EVENT_SUBCATGEGORY_FILM_AND_MEDIA = 'FILM_AND_MEDIA';
module.exports.EVENT_SUBCATGEGORY_TOURISM = 'TOURISM';
module.exports.EVENT_SUBCATGEGORY_DAYS_OUT = 'DAYS_OUT';
module.exports.EVENT_SUBCATGEGORY_CLUBS = 'CLUBS';
module.exports.EVENT_SUBCATGEGORY_ATTRACTIONS = 'ATTRACTIONS';
module.exports.EVENT_SUBCATGEGORY_AMUSEMENT = 'AMUSEMENT';
module.exports.EVENT_SUBCATGEGORY_VISUAL_ART = 'VISUAL_ART';
module.exports.EVENT_SUBCATGEGORY_FOLKLORIC = 'FOLKLORIC';
module.exports.EVENT_SUBCATGEGORY_CALENDAR = 'CALENDAR';
module.exports.EVENT_SUBCATGEGORY_HISTORIC = 'HISTORIC';
module.exports.EVENT_SUBCATGEGORY_RELIGIOUS = 'RELIGIOUS';
module.exports.EVENT_SUBCATGEGORY_FESTIVAL = 'FESTIVAL';
module.exports.EVENT_SUBCATGEGORY_CELEBRATION = 'CELEBRATION';
module.exports.EVENT_SUBCATGEGORY_NATIONAL_HOLIDAY = 'NATIONAL_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_BANK_HOLIDAY = 'BANK_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_STATE_HOLIDAY = 'STATE_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_LOCAL_HOLIDAY = 'LOCAL_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_RELIGIOUS_HOLIDAY = 'RELIGIOUS_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_GOVERNMENT_HOLIDAY = 'GOVERNMENT_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_REGIONAL_HOLIDAY = 'REGIONAL_HOLIDAY';
module.exports.EVENT_SUBCATGEGORY_NBA = 'NBA';
module.exports.EVENT_SUBCATGEGORY_NFL = 'NFL';
module.exports.EVENT_SUBCATGEGORY_NHL = 'NHL';
module.exports.EVENT_SUBCATGEGORY_MLB = 'MLB';
module.exports.EVENT_SUBCATGEGORY_MLS = 'MLS';
module.exports.EVENT_SUBCATGEGORY_TENNIS = 'TENNIS';
module.exports.EVENT_SUBCATGEGORY_AMERICAN_FOOTBALL = 'AMERICAN_FOOTBALL';
module.exports.EVENT_SUBCATGEGORY_BASEBALL = 'BASEBALL';
module.exports.EVENT_SUBCATGEGORY_SOCCER_FOOTBALL = 'SOCCER_FOOTBALL';
module.exports.EVENT_SUBCATGEGORY_ICE_HOKEY = 'ICE_HOKEY';
module.exports.EVENT_SUBCATGEGORY_CRICKET = 'CRICKET';
module.exports.EVENT_SUBCATGEGORY_GOLF = 'GOLF';
module.exports.EVENT_SUBCATGEGORY_AUTO_RACING = 'AUTO_RACING';
module.exports.EVENT_SUBCATGEGORY_BOXING = 'BOXING';
module.exports.EVENT_SUBCATGEGORY_WRESTLING = 'WRESTLING';
module.exports.EVENT_SUBCATGEGORY_BASKETBALL = 'BASKETBALL';
module.exports.EVENT_SUBCATGEGORY_HOCKEY = 'HOCKEY';
module.exports.EVENT_SUBCATGEGORY_CYCLING = 'CYCLING';
module.exports.EVENT_SUBCATGEGORY_RUGBY = 'RUGBY';
module.exports.EVENT_SUBCATGEGORY_VOLLEYBALL = 'VOLLEYBALL';
module.exports.EVENT_SUBCATGEGORY_TRADESHOWS_FAIRS_EXPO = 'TRADESHOWS_FAIRS_EXPO';
module.exports.EVENT_SUBCATGEGORY_CONFERENCES = 'CONFERENCES';
module.exports.EVENT_SUBCATGEGORY_WORKSHOPS = 'WORKSHOPS';
module.exports.EVENT_SUBCATGEGORY_MEETUPS = 'MEETUPS';
module.exports.EVENT_SUBCATGEGORY_SEMINAR_AND_CLASSES = 'SEMINAR_AND_CLASSES';
module.exports.EVENT_SUBCATGEGORY_LECTURES_AND_TALKS = 'LECTURES_AND_TALKS';
module.exports.EVENT_SUBCATGEGORY_BUSINESS_AND_TECH = 'BUSINESS_AND_TECH';
module.exports.EVENT_SUBCATGEGORY_HEALTH_AND_WELLNESS = 'HEALTH_AND_WELLNESS';
module.exports.EVENT_SUBCATGEGORY_ACADEMIC = 'ACADEMIC';
module.exports.EVENT_SUBCATGEGORY_FASHION = 'FASHION';
module.exports.EVENT_SUBCATGEGORY_MARATHON = 'MARATHON';
module.exports.EVENT_SUBCATGEGORY_PROMOTIONAL = 'PROMOTIONAL';
module.exports.EVENT_SUBCATGEGORY_PARADE = 'PARADE';
module.exports.EVENT_SUBCATGEGORY_POLITICAL_AND_SOCIAL = 'POLITICAL_AND_SOCIAL';
module.exports.EVENT_SUBCATGEGORY_GOVERNMENT = 'GOVERNMENT';
module.exports.EVENT_SUBCATGEGORY_FOOD_FESTIVAL = 'FOOD_FESTIVAL';
module.exports.EVENT_SUBCATGEGORY_CHARITY_AND_CAUSES = 'CHARITY_AND_CAUSES';
module.exports.EVENT_SUBCATGEGORY_COMMUNITY_PARTY = 'COMMUNITY_PARTY';
module.exports.EVENT_SUBCATGEGORY_SPIRITUALITY = 'SPIRITUALITY';
module.exports.EVENT_SUBCATGEGORY_TRIATHLON = 'TRIATHLON';
module.exports.EVENT_SUBCATGEGORY_OTHER = 'OTHER';

module.exports.EVENT_STATUS_SCHEDULED = 'SCHEDULED';
module.exports.EVENT_STATUS_RESCHEDULED = 'RESCHEDULED';
module.exports.EVENT_STATUS_POSTPONED = 'POSTPONED';
module.exports.EVENT_STATUS_HOLIDAY_EVENTS = 'HOLIDAY_EVENTS';
module.exports.EVENT_STATUS_CANCELLED = 'CANCELLED';
module.exports.EVENT_STATUS_UNKNOWN = 'UNKNOWN';

module.exports.DEMAND_AI_AUTH_TOKEN = 'DEMAND_AI_AUTH_TOKEN';
module.exports.DEMAND_AI_CITY_DEMAND = 'DEMAND_AI_CITY_DEMAND';
module.exports.DEMAND_AI_HOTEL_DEMAND = 'DEMAND_AI_HOTEL_DEMAND';
module.exports.DEMAND_AI_AIRLINE_DATA = 'DEMAND_AI_AIRLINE_DATA';

module.exports.RMS_REST_API_GET_CLIENT_URL = 'RMS_REST_API_GET_CLIENT_URL';
module.exports.RMS_REST_API_GET_AUTH_TOKEN = 'RMS_REST_API_GET_AUTH_TOKEN';
module.exports.RMS_REST_API_GET_AVAILABILITY_GRID = 'RMS_REST_API_GET_AVAILABILITY_GRID';
module.exports.RMS_REST_API_RESERVATIONS_SEARCH = 'RMS_REST_API_RESERVATIONS_SEARCH';
module.exports.RMS_REST_API_RESERVATIONS_ACTUAL_ACCOUNT = 'RMS_REST_API_RESERVATIONS_ACTUAL_ACCOUNT';

module.exports.RESAVENUE_CM_API_PULL_INVENTORY = 'RESAVENUE_CM_API_PULL_INVENTORY';
module.exports.RESAVENUE_CM_API_PULL_BOOKINGS = 'RESAVENUE_CM_API_PULL_BOOKINGS';
module.exports.RESAVENUE_CM_API_PULL_RATES = 'RESAVENUE_CM_API_PULL_RATES';

module.exports.GOOGLE_PLACES_API_GET_PLACE_DETAILS = 'GOOGLE_PLACES_API_GET_PLACE_DETAILS';

module.exports.AI_REVIEWS_AUTH_TOKEN = 'AI_REVIEWS_AUTH_TOKEN';
module.exports.AI_REVIEWS_GET_HOTELS = 'AI_REVIEWS_GET_HOTELS';
module.exports.AI_FETCH_REVIEWS = 'AI_FETCH_REVIEWS';
module.exports.AI_FETCH_REVIEWS_INSIGHTS = 'AI_FETCH_REVIEWS_INSIGHTS';

module.exports.AI_RATE_METRICS_AUTH_TOKEN = 'AI_RATE_METRICS_AUTH_TOKEN';
module.exports.AI_RATE_METRICS_GET_HOTELS = 'AI_RATE_METRICS_GET_HOTELS';
module.exports.AI_RATE_METRICS_GET_HOTEL_INFO = 'AI_RATE_METRICS_GET_HOTEL_INFO';
module.exports.AI_RATE_METRICS_GET_CURRENCIES = 'AI_RATE_METRICS_GET_CURRENCIES';
module.exports.AI_RATE_METRICS_GET_COUNTRIES = 'AI_RATE_METRICS_GET_COUNTRIES';
module.exports.AI_RATE_METRICS_GET_SOURCES = 'AI_RATE_METRICS_GET_SOURCES';
module.exports.AI_RATE_METRICS_GET_ROOM_TYPES = 'AI_RATE_METRICS_GET_ROOM_TYPES';
module.exports.AI_RATE_METRICS_GET_MEAL_PLANS = 'AI_RATE_METRICS_GET_MEAL_PLANS';
module.exports.AI_RATE_METRICS_GET_CONDITIONS = 'AI_RATE_METRICS_GET_CONDITIONS';
module.exports.AI_RATE_METRICS_GET_STATUS_CODES = 'AI_RATE_METRICS_GET_STATUS_CODES';
module.exports.AI_RATE_METRICS_GET_POS = 'AI_RATE_METRICS_GET_POS';
module.exports.AI_RATE_METRICS_CREATE_RATE_SHOP = 'AI_RATE_METRICS_CREATE_RATE_SHOP';
module.exports.AI_RATE_METRICS_RUN_RATE_SHOP = 'AI_RATE_METRICS_RUN_RATE_SHOP';
module.exports.AI_RATE_METRICS_GET_RATES_BY_QUEUE = 'AI_RATE_METRICS_GET_RATES_BY_QUEUE';
module.exports.AI_RATE_METRICS_GET_QUEUE_STATUS = 'AI_RATE_METRICS_GET_QUEUE_STATUS';

module.exports.AI_EDDI_AUTH_TOKEN = 'AI_EDDI_AUTH_TOKEN';
module.exports.AI_EDDI_DEMAND_SHOP_REQUEST = 'AI_EDDI_DEMAND_SHOP_REQUEST';
module.exports.AI_EDDI_GET_DEMAND_DATA = 'AI_EDDI_GET_DEMAND_DATA';
module.exports.AI_EDDI_GET_EVENTS_INFO = 'AI_EDDI_GET_EVENTS_INFO';

module.exports.AI_RATE_METRICS_CHANNEL_MAPPING_STRATEGY_ID_MATCH = 'ID_MATCH';
module.exports.AI_RATE_METRICS_CHANNEL_MAPPING_STRATEGY_NAME_EXACT_MATCH = 'NAME_EXACT_MATCH';
module.exports.AI_RATE_METRICS_CHANNEL_MAPPING_STRATEGY_NAME_PARTIAL_MATCH = 'NAME_PARTIAL_MATCH';
module.exports.AI_RATE_METRICS_CHANNEL_MAPPING_STRATEGY_NAME_STARTS_WITH_MATCH = 'NAME_STARTS_WITH_MATCH';
module.exports.AI_RATE_METRICS_CHANNEL_MAPPING_STRATEGY_NAME_ENDS_WITH_MATCH = 'NAME_ENDS_WITH_MATCH';
