export const PROPERTY_MODULES_BOOKING_ENGINE = 'BE';
export const PROPERTY_MODULES_CHANNEL_MANAGER = "CM";
export const PROPERTY_MODULES_CONTENT_MANAGEMENT_SYSTEM = "CMS";
export const PROPERTY_MODULES_CENTRAL_RESERVATION_SYSTEM = "CRS";
export const PROPERTY_MODULES_YIELD_AUTOMATION_SYSTEM = "IYA";
export const PROPERTY_MODULES_REPUTATION_MANAGER = "RM";
export const PROPERTY_MODULES_RATE_SHOPPER = "RS";
export const PROPERTY_MODULES_CMSU = "CMSU";