export const PROPERTY_MODULES_BOOKING_ENGINE: string = 'BE';
export const PROPERTY_MODULES_CHANNEL_MANAGER: string = "CM";
export const PROPERTY_MODULES_CONTENT_MANAGEMENT_SYSTEM: string = "CMS";
export const PROPERTY_MODULES_CENTRAL_RESERVATION_SYSTEM: string = "CRS";
export const PROPERTY_MODULES_YIELD_AUTOMATION_SYSTEM: string = "IYA";
export const PROPERTY_MODULES_REPUTATION_MANAGER: string = "RM";
export const PROPERTY_MODULES_RATE_SHOPPER: string = "RS";