module.exports.RATE_SHOPPER_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED'
module.exports.RATE_SHOPPER_ONBOARDING_STATUS_REJECTED = 'REJECTED'
module.exports.RATE_SHOPPER_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
module.exports.RATE_SHOPPER_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

module.exports.RATE_SHOPPER_SETUP_STATUS_ACTIVE = 'ACTIVE';
module.exports.RATE_SHOPPER_SETUP_STATUS_DISABLED = 'DISABLED';
module.exports.RATE_SHOPPER_SETUP_STATUS_ONBOARDING = 'ONBOARDING';