export const RATE_SHOPPER_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED'
export const RATE_SHOPPER_ONBOARDING_STATUS_REJECTED = 'REJECTED'
export const RATE_SHOPPER_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const RATE_SHOPPER_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

export const RATE_SHOPPER_SETUP_STATUS_ACTIVE = 'ACTIVE';
export const RATE_SHOPPER_SETUP_STATUS_DISABLED = 'DISABLED';
export const RATE_SHOPPER_SETUP_STATUS_ONBOARDING = 'ONBOARDING';