module.exports.REVIEW_SETUP_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
module.exports.REVIEW_SETUP_ONBOARDING_STATUS_REJECTED = 'REJECTED';
module.exports.REVIEW_SETUP_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
module.exports.REVIEW_SETUP_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

module.exports.REVIEW_SETUP_STATUS_ONBOARDING = 'ONBOARDING';
module.exports.REVIEW_SETUP_STATUS_ACTIVE = 'ACTIVE';
module.exports.REVIEW_SETUP_STATUS_DISABLED = 'DISABLED';

module.exports.SENTIMENT_POLARITY_TYPE_POSITIVE = 'POSITIVE';
module.exports.SENTIMENT_POLARITY_TYPE_NEGATIVE = 'NEGATIVE';
module.exports.SENTIMENT_POLARITY_TYPE_NEUTRAL = 'NEUTRAL';
