export const REVIEW_SETUP_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
export const REVIEW_SETUP_STATUS_REJECTED = 'REJECTED';
export const REVIEW_SETUP_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const REVIEW_SETUP_STATUS_COMPLETED = 'COMPLETED';

export const REVIEW_SETUP_ONBOARDING_STATUS_ONBOARDING = 'ONBOARDING';
export const REVIEW_SETUP_ONBOARDING_STATUS_ACTIVE = 'ACTIVE';
export const REVIEW_SETUP_ONBOARDING_STATUS_DISABLED = 'DISABLED';