export const REVIEW_SETUP_ONBOARDING_STATUS_REQUEST_RECEIVED = 'REQUEST_RECEIVED';
export const REVIEW_SETUP_ONBOARDING_STATUS_REJECTED = 'REJECTED';
export const REVIEW_SETUP_ONBOARDING_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const REVIEW_SETUP_ONBOARDING_STATUS_COMPLETED = 'COMPLETED';

export const REVIEW_SETUP_STATUS_ONBOARDING = 'ONBOARDING';
export const REVIEW_SETUP_STATUS_ACTIVE = 'ACTIVE';
export const REVIEW_SETUP_STATUS_DISABLED = 'DISABLED';

export const SENTIMENT_POLARITY_TYPE_POSITIVE = 'POSITIVE';
export const SENTIMENT_POLARITY_TYPE_NEGATIVE = 'NEGATIVE';
export const SENTIMENT_POLARITY_TYPE_NEUTRAL = 'NEUTRAL';