const {
    MARKET_CHANNEL_CLEARTRIP,
    MARKET_CHANNEL_MAKEMYTRIP,
    MARKET_CHANNEL_GOIBIBO,
    MARKET_CHANNEL_AGODA,
    MARKET_CHANNEL_EXPEDIA,
    MARKET_CHANNEL_TRAVEL_GURU,
    MARKET_CHANNEL_BOOKING_DOT_COM,
    MARKET_CHANNEL_VIA,
    MARKET_CHANNEL_HOTELS_COMBINED,
    MARKET_CHANNEL_ONLINE_GDS,
    MARKET_CHANNEL_MR_AND_MRS_SMITH,
    MARKET_CHANNEL_HOTELS_BED,
    MARKET_CHANNEL_DOTW,
    MARKET_CHANNEL_SIMPLOTEL,
    MARKET_CHANNEL_HRS,
    MARKET_CHANNEL_EASE_MY_TRIP,
    MARKET_CHANNEL_TRIP_DOT_COM,
    MARKET_CHANNEL_TRIPADVISOR,
    MARKET_CHANNEL_PAYTM,
    MARKET_CHANNEL_TRAVELIKO,
    MARKET_CHANNEL_HAPPY_EASY_GO,
    MARKET_CHANNEL_HOBSE,
    MARKET_CHANNEL_BOOK_LOGIC,
    MARKET_CHANNEL_IRCTC,
    MARKET_CHANNEL_XENIA,
    MARKET_CHANNEL_CHANNEX,
    MARKET_CHANNEL_RESAVENUE_PMS,
    MARKET_CHANNEL_TOUR_MY_INDIA,
    MARKET_CHANNEL_VEEKEND,
    MARKET_CHANNEL_ONE_FINE_RATE,
    MARKET_CHANNEL_SYSOTEL,
    MARKET_CHANNEL_HOTLA,
    MARKET_CHANNEL_TRAVIATE,
    MARKET_CHANNEL_ONLINE_VACATIONS,
    MARKET_CHANNEL_ROOM_STATUS_HUB,
    MARKET_CHANNEL_TRAVEL_BOUTIQUE,
    MARKET_CHANNEL_HOSTEL_WORLD,
    MARKET_CHANNEL_GOOGLE,
    MARKET_CHANNEL_HOTELS_DOT_COM,
    MARKET_CHANNEL_PRICELINE,
    MARKET_CHANNEL_ORBITZ,
    MARKET_CHANNEL_IHG_DOT_COM,
    MARKET_CHANNEL_MARRIOTT,
    MARKET_CHANNEL_RADISSONCOM,
    MARKET_CHANNEL_HILTON,
    MARKET_CHANNEL_BOOKBESTWESTERNCOM,
    MARKET_CHANNEL_HRSCOM,
    MARKET_CHANNEL_ACCORHOTELS,
    MARKET_CHANNEL_JUMIA,
    MARKET_CHANNEL_YATRA,
    MARKET_CHANNEL_HOSTELWORLD,
    MARKET_CHANNEL_LATEROOMS,
    MARKET_CHANNEL_SPLENDIA,
    MARKET_CHANNEL_BESTDAY,
    MARKET_CHANNEL_PRICETRAVEL,
    MARKET_CHANNEL_AIRBNB,
    MARKET_CHANNEL_LASTMINUTE_DOT_COM,
    MARKET_CHANNEL_TRAVELOKA,
    MARKET_CHANNEL_HOTELLOOK,
    MARKET_CHANNEL_OSTROVOK,
    MARKET_CHANNEL_PEGIPEGI,
    MARKET_CHANNEL_TIKET,
    MARKET_CHANNEL_RAKUTEN,
    MARKET_CHANNEL_CTRIP,
    MARKET_CHANNEL_TRAVELREPUBLIC,
    MARKET_CHANNEL_MRANDMRSSMITH,
    MARKET_CHANNEL_FABHOTELS,
    MARKET_CHANNEL_TREEBO,
    MARKET_CHANNEL_HOLIDAYCHECK,
    MARKET_CHANNEL_TRAVELOCITY,
    MARKET_CHANNEL_CHEAPTICKETS,
    MARKET_CHANNEL_EBOOKERS,
    MARKET_CHANNEL_DESPEGAR,
    MARKET_CHANNEL_MEITUAN,
    MARKET_CHANNEL_BOOKINGS_FLIGHTEXPERT_COM,
    MARKET_CHANNEL_SHARETRIP,
    MARKET_CHANNEL_GOZAYAAN,
    MARKET_CHANNEL_RURUBU,
    MARKET_CHANNEL_BE_SYNXIS_COM,
    MARKET_CHANNEL_WORLDROAMER,
    MARKET_CHANNEL_MYKONOS,
    MARKET_CHANNEL_BOOK_RGUEST_COM,
    MARKET_CHANNEL_BOOKINGS_HOTELREZ_CO_UK,
    MARKET_CHANNEL_SECURE_HOTEL_BOOKING,
    MARKET_CHANNEL_SHOUSUGIBANHOUSE,
    MARKET_CHANNEL_RSWS_KRIPALU,
    MARKET_CHANNEL_TUI,
    MARKET_CHANNEL_GRANDBARAKA_HOTEL,
    MARKET_CHANNEL_WEBHOTELIER,
    MARKET_CHANNEL_BLASTNESS,
    MARKET_CHANNEL_BOOK_SECURE,
    MARKET_CHANNEL_VERTICAL_BOOKING,
    MARKET_CHANNEL_DIRECT_BOOK,
    MARKET_CHANNEL_EURO_STARS_HOTELS,
    MARKET_CHANNEL_HOTEL_ZIMBROS,
    MARKET_CHANNEL_BOOK_OMNIBEES,
    MARKET_CHANNEL_HF_HOTELS,
    MARKET_CHANNEL_REHLAT,
    MARKET_CHANNEL_SESIMBRA_HOTEL_SPA,
    MARKET_CHANNEL_ONE_PAGE_BOOKING,
    MARKET_CHANNEL_ADAGIO_CITY,
    MARKET_CHANNEL_MASA_HOTEL,
    MARKET_CHANNEL_BOOKING_CAMPING,
    MARKET_CHANNEL_BOOKING_EXPERT,
    MARKET_CHANNEL_SCIDOO,
    MARKET_CHANNEL_D_EDGE,
    MARKET_CHANNEL_SECURE_IPER_BOOKING,
    MARKET_CHANNEL_E_GDS,
    MARKET_CHANNEL_HU_OPEN_AIR,
    MARKET_CHANNEL_ORLANDO_INCHIANTI,
    MARKET_CHANNEL_NET_BOOKING_NATURAL_BOOKING,
    MARKET_CHANNEL_CAMPING_SERENO,
    MARKET_CHANNEL_CAMPING_CISANO,
    MARKET_CHANNEL_ICONNECT_PRENOTA_ONLINE,
    MARKET_CHANNEL_PALACIO_ESTORIL_HOTEL,
    MARKET_CHANNEL_BOOKING_PREMIUM_SECURE_HOLIDAY,
    MARKET_CHANNEL_SECURE_GUEST_CENTRIC,
    MARKET_CHANNEL_ALL_CAMPS,
    MARKET_CHANNEL_DOMPEDRO,
    MARKET_CHANNEL_RESERVAS_VILAGALE,
    MARKET_CHANNEL_HOTEL_BB,
    MARKET_CHANNEL_SIMPLE_BOOKING,
    MARKET_CHANNEL_ABBA_HOTELES,
    MARKET_CHANNEL_LOHONO,
    MARKET_CHANNEL_SAFFRON_STAYS,
    MARKET_CHANNEL_A_HOTEL,
    MARKET_CHANNEL_TRAVEL_CLICK,
    MARKET_CHANNEL_DEIFIORI,
    MARKET_CHANNEL_BAIA_HOLIDAY,
    MARKET_CHANNEL_UNION_LIDO,
    MARKET_CHANNEL_IBEROSTAR,
    MARKET_CHANNEL_BOOK_CORE,
    MARKET_CHANNEL_RIU,
    MARKET_CHANNEL_MIRAI,
    MARKET_CHANNEL_SECURE_BOOKING,
    MARKET_CHANNEL_BOOKING_MY_GUEST_CARE,
    MARKET_CHANNEL_ERICSOFT,
    MARKET_CHANNEL_QUICK_BOOKING,
    MARKET_CHANNEL_HOTELS_EDREAMS,
    MARKET_CHANNEL_TRAVEL,
    MARKET_CHANNEL_HOTELS_CTRIP_COM,
    CHANNEL_MANAGER_IDS_NEXT,
    CHANNEL_MANAGER_HOTELOGIX,
    CHANNEL_MANAGER_WINCLOUD,
    CHANNEL_MANAGER_MAXIMOJO,
    CHANNEL_MANAGER_RESAVENUE,
    CHANNEL_MANAGER_RMS,
} = require("../../constants/IyaConstants.js");

const {CHANNEL_MANAGER_EASEROOMS, SYSOTEL_IBE_CHANNEL_API} = require("../../constants/BeConstants.js");

const LogoMappings = (channelId) => {

    const logoMappings = {
        [SYSOTEL_IBE_CHANNEL_API]: require('../../assets/MarketChannelLogos/SYSOTEL_LOGO.svg').default,
        [MARKET_CHANNEL_CLEARTRIP]: require('../../assets/MarketChannelLogos/CLEARTRIP.svg').default,
        [CHANNEL_MANAGER_RESAVENUE]: require('../../assets/MarketChannelLogos/RESAVENUE.svg').default,
        [MARKET_CHANNEL_MAKEMYTRIP]: require('../../assets/MarketChannelLogos/MAKEMYTRIP.svg').default,
        [MARKET_CHANNEL_GOIBIBO]:  require('../../assets/MarketChannelLogos/GOIBIBO.svg').default,
        [MARKET_CHANNEL_AGODA]:  require('../../assets/MarketChannelLogos/AGODA.svg').default,
        [MARKET_CHANNEL_EXPEDIA]:  require('../../assets/MarketChannelLogos/EXPEDIA.svg').default,
        [MARKET_CHANNEL_TRAVEL_GURU]: require('../../assets/MarketChannelLogos/TRAVELGURU.svg').default,
        [MARKET_CHANNEL_BOOKING_DOT_COM]: require('../../assets/MarketChannelLogos/bookingdotcom.svg').default,
        [MARKET_CHANNEL_VIA]: require('../../assets/MarketChannelLogos/VIA.svg').default,
        [MARKET_CHANNEL_HOTELS_COMBINED]: require('../../assets/MarketChannelLogos/HOTELS_COMBINED.svg').default,
        //     [MARKET_CHANNEL_ONLINE_GDS]: _ONLINE_GDS
        [MARKET_CHANNEL_MR_AND_MRS_SMITH]: require('../../assets/MarketChannelLogos/MR_AND_MRS_SMITH.svg').default,
        [MARKET_CHANNEL_HOTELS_BED]: require('../../assets/MarketChannelLogos/HOTELS_BED.svg').default,
        [MARKET_CHANNEL_DOTW]: require('../../assets/MarketChannelLogos/DOTW.svg').default,
        [MARKET_CHANNEL_SIMPLOTEL]: require('../../assets/MarketChannelLogos/SIMPLOTEL.svg').default,
        [MARKET_CHANNEL_HRS]: require('../../assets/MarketChannelLogos/HRS.svg').default,
        [MARKET_CHANNEL_EASE_MY_TRIP]: require('../../assets/MarketChannelLogos/EASE_MY_TRIP.svg').default,
        [MARKET_CHANNEL_TRIP_DOT_COM]: require('../../assets/MarketChannelLogos/TRIP_DOT_COM.svg').default,
        [MARKET_CHANNEL_TRIPADVISOR]: require('../../assets/MarketChannelLogos/TRIPADVISOR.svg').default,
        [MARKET_CHANNEL_PAYTM]: require('../../assets/MarketChannelLogos/PAYTM.svg').default,
        [MARKET_CHANNEL_TRAVELIKO]: require('../../assets/MarketChannelLogos/TRAVELIKO.svg').default,
        [MARKET_CHANNEL_HAPPY_EASY_GO]: require('../../assets/MarketChannelLogos/HAPPY_EASY_GO.svg').default,
        [MARKET_CHANNEL_HOBSE]: require('../../assets/MarketChannelLogos/HOBSE.svg').default,
        [MARKET_CHANNEL_BOOK_LOGIC]: require('../../assets/MarketChannelLogos/Book_Logic.svg').default,
        [MARKET_CHANNEL_IRCTC]: require('../../assets/MarketChannelLogos/IRCTC.svg').default,
        [MARKET_CHANNEL_XENIA]: require('../../assets/MarketChannelLogos/XENIA.svg').default,
        [MARKET_CHANNEL_CHANNEX]: require('../../assets/MarketChannelLogos/CHANNEX.svg').default,
        //     [MARKET_CHANNEL_RESAVENUE_PMS]: _RESAVENUE_PMS
        [MARKET_CHANNEL_TOUR_MY_INDIA]: require('../../assets/MarketChannelLogos/TOUR_MY_INDIA.svg').default,
        //     [MARKET_CHANNEL_VEEKEND]: _VEEKEND
        [MARKET_CHANNEL_ONE_FINE_RATE]: require('../../assets/MarketChannelLogos/ONE_FINE_RATE.svg').default,
        [MARKET_CHANNEL_SYSOTEL]: require('../../assets/MarketChannelLogos/SYSOTEL_ICON.svg').default,
        //     [MARKET_CHANNEL_HOTLA]: _HOTLA
        [MARKET_CHANNEL_TRAVIATE]: require('../../assets/MarketChannelLogos/TRAVIATE.svg').default,
        [MARKET_CHANNEL_ONLINE_VACATIONS]: require('../../assets/MarketChannelLogos/ONLINE_VACATIONS.svg').default,
        [MARKET_CHANNEL_ROOM_STATUS_HUB]: require('../../assets/MarketChannelLogos/ROOM_STATUS_HUB.svg').default,
        [MARKET_CHANNEL_TRAVEL_BOUTIQUE]: require('../../assets/MarketChannelLogos/TRAVEL_BOUTIQUE.svg').default,
        [MARKET_CHANNEL_HOSTEL_WORLD]: require('../../assets/MarketChannelLogos/HOSTEL_WORLD.svg').default,
        [MARKET_CHANNEL_GOOGLE]: require('../../assets/MarketChannelLogos/GOOGLE.svg').default,
        [MARKET_CHANNEL_HOTELS_DOT_COM]: require('../../assets/MarketChannelLogos/HOTELS_DOT_COM.svg').default,
        [MARKET_CHANNEL_PRICELINE]: require('../../assets/MarketChannelLogos/PRICELINE.svg').default,
        [MARKET_CHANNEL_ORBITZ]: require('../../assets/MarketChannelLogos/ORBITZ.svg').default,
        [MARKET_CHANNEL_IHG_DOT_COM]: require('../../assets/MarketChannelLogos/IHG_DOT_COM.svg').default,
        [MARKET_CHANNEL_MARRIOTT]: require('../../assets/MarketChannelLogos/MARRIOTT.svg').default,
        [MARKET_CHANNEL_RADISSONCOM]: require('../../assets/MarketChannelLogos/RADISSONCOM.svg').default,
        [MARKET_CHANNEL_HILTON]: require('../../assets/MarketChannelLogos/HILTON.svg').default,
        [MARKET_CHANNEL_BOOKBESTWESTERNCOM]: require('../../assets/MarketChannelLogos/Best_Western.svg').default,
        //     [MARKET_CHANNEL_HRSCOM]: _HRSCOM
        [MARKET_CHANNEL_ACCORHOTELS]: require('../../assets/MarketChannelLogos/ACCORHOTELS.svg').default,
        [MARKET_CHANNEL_JUMIA]: require('../../assets/MarketChannelLogos/JUMIA.svg').default,
        [MARKET_CHANNEL_YATRA]: require('../../assets/MarketChannelLogos/YATRA.svg').default,
        //     [MARKET_CHANNEL_HOSTELWORLD]: _HOSTELWORLD
        [MARKET_CHANNEL_LATEROOMS]: require('../../assets/MarketChannelLogos/LATEROOMS.svg').default,
        [MARKET_CHANNEL_SPLENDIA]: require('../../assets/MarketChannelLogos/SPLENDIA.svg').default,
        [MARKET_CHANNEL_BESTDAY]: require('../../assets/MarketChannelLogos/BESTDAY.svg').default,
        [MARKET_CHANNEL_PRICETRAVEL]: require('../../assets/MarketChannelLogos/PRICETRAVEL.svg').default,
        [MARKET_CHANNEL_AIRBNB]: require('../../assets/MarketChannelLogos/AIRBNB.svg').default,
        [MARKET_CHANNEL_LASTMINUTE_DOT_COM]: require('../../assets/MarketChannelLogos/LASTMINUTE_DOT_COM.svg').default,
        [MARKET_CHANNEL_TRAVELOKA]: require('../../assets/MarketChannelLogos/TRAVELOKA.svg').default,
        [MARKET_CHANNEL_HOTELLOOK]: require('../../assets/MarketChannelLogos/HOTELLOOK.svg').default,
        [MARKET_CHANNEL_OSTROVOK]: require('../../assets/MarketChannelLogos/OSTROVOK.svg').default,
        [MARKET_CHANNEL_PEGIPEGI]: require('../../assets/MarketChannelLogos/PEGIPEGI.svg').default,
        //     [MARKET_CHANNEL_TIKET]: _TIKET
        [MARKET_CHANNEL_RAKUTEN]: require('../../assets/MarketChannelLogos/RAKUTEN.svg').default,
        [MARKET_CHANNEL_CTRIP]: require('../../assets/MarketChannelLogos/CTRIP.svg').default,
        [MARKET_CHANNEL_TRAVELREPUBLIC]: require('../../assets/MarketChannelLogos/TRAVELREPUBLIC.svg').default,
        //     [MARKET_CHANNEL_MRANDMRSSMITH]: _MRANDMRSSMITH
        [MARKET_CHANNEL_FABHOTELS]: require('../../assets/MarketChannelLogos/FABHOTELS.svg').default,
        [MARKET_CHANNEL_TREEBO]: require('../../assets/MarketChannelLogos/TREEBO.svg').default,
        [MARKET_CHANNEL_HOLIDAYCHECK]: require('../../assets/MarketChannelLogos/HOLIDAYCHECK.svg').default,
        [MARKET_CHANNEL_TRAVELOCITY]: require('../../assets/MarketChannelLogos/TRAVELOCITY.svg').default,
        [MARKET_CHANNEL_CHEAPTICKETS]: require('../../assets/MarketChannelLogos/CHEAPTICKETS.svg').default,
        [MARKET_CHANNEL_EBOOKERS]: require('../../assets/MarketChannelLogos/EBOOKERS.svg').default,
        [MARKET_CHANNEL_DESPEGAR]: require('../../assets/MarketChannelLogos/DESPEGAR.svg').default,
        [MARKET_CHANNEL_MEITUAN]: require('../../assets/MarketChannelLogos/MEITUAN.svg').default,
        [MARKET_CHANNEL_BOOKINGS_FLIGHTEXPERT_COM]: require('../../assets/MarketChannelLogos/BOOKINGS_FLIGHTEXPERT_COM.svg').default,
        [MARKET_CHANNEL_SHARETRIP]: require('../../assets/MarketChannelLogos/SHARETRIP.svg').default,
        [MARKET_CHANNEL_GOZAYAAN]: require('../../assets/MarketChannelLogos/GOZAYAAN.svg').default,
        [MARKET_CHANNEL_RURUBU]: require('../../assets/MarketChannelLogos/RURUBU.svg').default,
        [MARKET_CHANNEL_BE_SYNXIS_COM]: require('../../assets/MarketChannelLogos/BE_SYNXIS_COM.svg').default,
        [MARKET_CHANNEL_WORLDROAMER]: require('../../assets/MarketChannelLogos/WORLDROAMER.svg').default,
        //     [MARKET_CHANNEL_MYKONOS]: _MYKONOS
        [MARKET_CHANNEL_BOOK_RGUEST_COM]: require('../../assets/MarketChannelLogos/BOOK_RGUEST_COM.svg').default,
        [MARKET_CHANNEL_BOOKINGS_HOTELREZ_CO_UK]: require('../../assets/MarketChannelLogos/BOOKINGS_HOTELREZ_CO_UK.svg').default,
        //     [MARKET_CHANNEL_SECURE_HOTEL_BOOKING]: _SECURE_HOTEL_BOOKING
        [MARKET_CHANNEL_SHOUSUGIBANHOUSE]: require('../../assets/MarketChannelLogos/SHOUSUGIBANHOUSE.svg').default,
        [MARKET_CHANNEL_RSWS_KRIPALU]: require('../../assets/MarketChannelLogos/RSWS_KRIPALU.svg').default,
        [MARKET_CHANNEL_TUI]: require('../../assets/MarketChannelLogos/TUI.svg').default,
        //     [MARKET_CHANNEL_GRANDBARAKA_HOTEL]: _GRANDBARAKA_HOTEL
        [MARKET_CHANNEL_WEBHOTELIER]: require('../../assets/MarketChannelLogos/WEBHOTELIER.svg').default,
        [MARKET_CHANNEL_BLASTNESS]: require('../../assets/MarketChannelLogos/BLASTNESS.svg').default,
        //     [MARKET_CHANNEL_BOOK_SECURE]: _BOOK_SECURE
        [MARKET_CHANNEL_VERTICAL_BOOKING]: require('../../assets/MarketChannelLogos/VERTICAL_BOOKING.svg').default,
        //     [MARKET_CHANNEL_DIRECT_BOOK]: _DIRECT_BOOK
        [MARKET_CHANNEL_EURO_STARS_HOTELS]: require('../../assets/MarketChannelLogos/EURO_STARS_HOTELS.svg').default,
        //     [MARKET_CHANNEL_HOTEL_ZIMBROS]: _HOTEL_ZIMBROS,
        [MARKET_CHANNEL_BOOK_OMNIBEES]: require('../../assets/MarketChannelLogos/BOOK_OMNIBEES.svg').default,
        [MARKET_CHANNEL_HF_HOTELS]: require('../../assets/MarketChannelLogos/HF_HOTELS.svg').default,
        [MARKET_CHANNEL_REHLAT]: require('../../assets/MarketChannelLogos/REHLAT.svg').default,
        [MARKET_CHANNEL_SESIMBRA_HOTEL_SPA]: require('../../assets/MarketChannelLogos/SESIMBRA_HOTEL_SPA.svg').default,
        //     [MARKET_CHANNEL_ONE_PAGE_BOOKING]: _ONE_PAGE_BOOKING
        [MARKET_CHANNEL_ADAGIO_CITY]: require('../../assets/MarketChannelLogos/ADAGIO_CITY.svg').default,
        [MARKET_CHANNEL_MASA_HOTEL]: require('../../assets/MarketChannelLogos/MASA_HOTEL.svg').default,
        //     [MARKET_CHANNEL_BOOKING_CAMPING]: _BOOKING_CAMPING
        [MARKET_CHANNEL_BOOKING_EXPERT]: require('../../assets/MarketChannelLogos/BOOKING_EXPERT.svg').default,
        [MARKET_CHANNEL_SCIDOO]: require('../../assets/MarketChannelLogos/SCIDOO.svg').default,
        [MARKET_CHANNEL_D_EDGE]: require('../../assets/MarketChannelLogos/D_EDGE.svg').default,
        [MARKET_CHANNEL_SECURE_IPER_BOOKING]: require('../../assets/MarketChannelLogos/SECURE_IPER_BOOKING.svg').default,
        [MARKET_CHANNEL_E_GDS]: require('../../assets/MarketChannelLogos/E_GDS.svg').default,
        [MARKET_CHANNEL_HU_OPEN_AIR]: require('../../assets/MarketChannelLogos/HU_OPEN_AIR.svg').default,
        [MARKET_CHANNEL_ORLANDO_INCHIANTI]: require('../../assets/MarketChannelLogos/ORLANDO_INCHIANTI.svg').default,
        [MARKET_CHANNEL_NET_BOOKING_NATURAL_BOOKING]: require('../../assets/MarketChannelLogos/NET_BOOKING_NATURAL_BOOKING.svg').default,
        [MARKET_CHANNEL_CAMPING_SERENO]: require('../../assets/MarketChannelLogos/CAMPING_SERENO.svg').default,
        [MARKET_CHANNEL_CAMPING_CISANO]: require('../../assets/MarketChannelLogos/CAMPING_CISANO.svg').default,
        //     [MARKET_CHANNEL_ICONNECT_PRENOTA_ONLINE]: _ICONNECT_PRENOTA_ONLINE,
        [MARKET_CHANNEL_PALACIO_ESTORIL_HOTEL]: require('../../assets/MarketChannelLogos/PALACIO_ESTORIL_HOTEL.svg').default,
        //     [MARKET_CHANNEL_BOOKING_PREMIUM_SECURE_HOLIDAY]: _BOOKING_PREMIUM_SECURE_HOLIDAY,
        [MARKET_CHANNEL_SECURE_GUEST_CENTRIC]: require('../../assets/MarketChannelLogos/SECURE_GUEST_CENTRIC.svg').default,
        [MARKET_CHANNEL_ALL_CAMPS]: require('../../assets/MarketChannelLogos/ALL_CAMPS.svg').default,
        [MARKET_CHANNEL_DOMPEDRO]: require('../../assets/MarketChannelLogos/DOMPEDRO.svg').default,
        [MARKET_CHANNEL_RESERVAS_VILAGALE]: require('../../assets/MarketChannelLogos/RESERVAS_VILAGALE.svg').default,
        [MARKET_CHANNEL_HOTEL_BB]: require('../../assets/MarketChannelLogos/HOTEL_BB.svg').default,
        [MARKET_CHANNEL_SIMPLE_BOOKING]: require('../../assets/MarketChannelLogos/SIMPLE_BOOKING.svg').default,
        [MARKET_CHANNEL_ABBA_HOTELES]: require('../../assets/MarketChannelLogos/ABBA_HOTELES.svg').default,
        [MARKET_CHANNEL_LOHONO]: require('../../assets/MarketChannelLogos/LOHONO.svg').default,
        [MARKET_CHANNEL_SAFFRON_STAYS]: require('../../assets/MarketChannelLogos/SAFFRON_STAYS.svg').default,
        //     [MARKET_CHANNEL_A_HOTEL]: _A_HOTEL,
        [MARKET_CHANNEL_TRAVEL_CLICK]: require('../../assets/MarketChannelLogos/TRAVEL_CLICK.svg').default,
        [MARKET_CHANNEL_DEIFIORI]: require('../../assets/MarketChannelLogos/DEIFIORI.svg').default,
        [MARKET_CHANNEL_BAIA_HOLIDAY]: require('../../assets/MarketChannelLogos/BAIA_HOLIDAY.svg').default,
        [MARKET_CHANNEL_UNION_LIDO]: require('../../assets/MarketChannelLogos/UNION_LIDO.svg').default,
        [MARKET_CHANNEL_IBEROSTAR]: require('../../assets/MarketChannelLogos/IBEROSTAR.svg').default,
        [MARKET_CHANNEL_BOOK_CORE]: require('../../assets/MarketChannelLogos/BOOK_CORE.svg').default,
        [MARKET_CHANNEL_RIU]: require('../../assets/MarketChannelLogos/RIU.svg').default,
        [MARKET_CHANNEL_MIRAI]: require('../../assets/MarketChannelLogos/MIRAI.svg').default,
        [MARKET_CHANNEL_SECURE_BOOKING]: require('../../assets/MarketChannelLogos/SECURE_BOOKING.svg').default,
        [MARKET_CHANNEL_BOOKING_MY_GUEST_CARE]: require('../../assets/MarketChannelLogos/BOOKING_MY_GUEST_CARE.svg').default,
        [MARKET_CHANNEL_ERICSOFT]: require('../../assets/MarketChannelLogos/ERICSOFT.svg').default,
        [MARKET_CHANNEL_QUICK_BOOKING]: require('../../assets/MarketChannelLogos/QUICK_BOOKING.svg').default,
        [MARKET_CHANNEL_HOTELS_EDREAMS]: require('../../assets/MarketChannelLogos/HOTELS_EDREAMS.svg').default,
        [CHANNEL_MANAGER_IDS_NEXT]: require('../../assets/MarketChannelLogos/IDS_NEXT.svg').default,
        [CHANNEL_MANAGER_HOTELOGIX]: require('../../assets/MarketChannelLogos/HOTELOGIX.svg').default,
        [CHANNEL_MANAGER_WINCLOUD]: require('../../assets/MarketChannelLogos/WINCLOUD.svg').default,
        [CHANNEL_MANAGER_MAXIMOJO]: require('../../assets/MarketChannelLogos/MAXIMOJO.svg').default,
        [CHANNEL_MANAGER_RMS]: require('../../assets/MarketChannelLogos/RMS.svg').default,
        [CHANNEL_MANAGER_EASEROOMS]: require('../../assets/MarketChannelLogos/EASEROOM.svg').default,
        'NO_IMAGE_FOUND': require('../../assets/MarketChannelLogos/NO_IMAGE_FOUND.svg').default,
    }

    return logoMappings[channelId] || logoMappings['NO_IMAGE_FOUND']
}