const {
    AFFILIATION_SOURCE_AGODAYCS,
    AFFILIATION_SOURCE_AIRBNB,
    AFFILIATION_SOURCE_ALTOVITA,
    AFFILIATION_SOURCE_AOT,
    AFFILIATION_SOURCE_APARTMENTSONLINE,
    AFFILIATION_SOURCE_BAKUUN,
    AFFILIATION_SOURCE_BEDBANK,
    AFFILIATION_SOURCE_BELHOTEL,
    AFFILIATION_SOURCE_BOOKEASY,
    AFFILIATION_SOURCE_BOOKINGDIRECT,
    AFFILIATION_SOURCE_BOOKINGEYE,
    AFFILIATION_SOURCE_BOOKIT,
    AFFILIATION_SOURCE_BOOKNPAYXML,
    AFFILIATION_SOURCE_CAMPINGVISION,
    AFFILIATION_SOURCE_CTRIP,
    AFFILIATION_SOURCE_DESPEGAR,
    AFFILIATION_SOURCE_DNATA,
    AFFILIATION_SOURCE_DORMS,
    AFFILIATION_SOURCE_DOTW,
    AFFILIATION_SOURCE_EASEMYTRIP,
    AFFILIATION_SOURCE_ENTERTAINMENT,
    AFFILIATION_SOURCE_EXPEDIA,
    AFFILIATION_SOURCE_EZTRAVEL,
    AFFILIATION_SOURCE_FASTBOOKING,
    AFFILIATION_SOURCE_FINDBULOUS,
    AFFILIATION_SOURCE_FIVEPM,
    AFFILIATION_SOURCE_GETROOM,
    AFFILIATION_SOURCE_GETYOURWEB,
    AFFILIATION_SOURCE_GOIBIBO,
    AFFILIATION_SOURCE_GOOGLE,
    AFFILIATION_SOURCE_GRABROOMS,
    AFFILIATION_SOURCE_HAPPYEASYGO,
    AFFILIATION_SOURCE_HOO,
    AFFILIATION_SOURCE_HOOROO,
    AFFILIATION_SOURCE_HOSTELSCLUB,
    AFFILIATION_SOURCE_HOSTELWORLD,
    AFFILIATION_SOURCE_HOTELBEDS,
    AFFILIATION_SOURCE_HOTELBONANZA,
    AFFILIATION_SOURCE_HOTELNETWORK,
    AFFILIATION_SOURCE_HOTELSCOMBINED,
    AFFILIATION_SOURCE_HOTELTONIGHT,
    AFFILIATION_SOURCE_HOTERIP,
    AFFILIATION_SOURCE_HOTUSA,
    AFFILIATION_SOURCE_HOTWIRE,
    AFFILIATION_SOURCE_HRS,
    AFFILIATION_SOURCE_HYPERGUEST,
    AFFILIATION_SOURCE_ICHONOZ,
    AFFILIATION_SOURCE_IESCAPE,
    AFFILIATION_SOURCE_INSTANTMIGRATION,
    AFFILIATION_SOURCE_IRCTC,
    AFFILIATION_SOURCE_KLIKHOTEL,
    AFFILIATION_SOURCE_LIDO,
    AFFILIATION_SOURCE_MAX,
    AFFILIATION_SOURCE_METACHANNEL,
    AFFILIATION_SOURCE_MIDDLEEASTHOTEL,
    AFFILIATION_SOURCE_MITCHELLCORP,
    AFFILIATION_SOURCE_MRANDMRSSMITH,
    AFFILIATION_SOURCE_MYBOOKINGS,
    AFFILIATION_SOURCE_NEEDITNOW,
    AFFILIATION_SOURCE_NEORCHA,
    AFFILIATION_SOURCE_NETROOMZ,
    AFFILIATION_SOURCE_NOT1NIGHT,
    AFFILIATION_SOURCE_ODIGEO,
    AFFILIATION_SOURCE_OFFPEAKLUXURY,
    AFFILIATION_SOURCE_OMNIHOTELIER,
    AFFILIATION_SOURCE_ONEFINERATE,
    AFFILIATION_SOURCE_OSTROVOK,
    AFFILIATION_SOURCE_PANPACIFIC,
    AFFILIATION_SOURCE_PEGIPEGI,
    AFFILIATION_SOURCE_PELICAN,
    AFFILIATION_SOURCE_PRESTIGIA,
    AFFILIATION_SOURCE_QUICKBEDS,
    AFFILIATION_SOURCE_RAKUTEN,
    AFFILIATION_SOURCE_RECONLINE,
    AFFILIATION_SOURCE_RESERVHOTEL,
    AFFILIATION_SOURCE_ROIBACK,
    AFFILIATION_SOURCE_SAFFRONSTAYS,
    AFFILIATION_SOURCE_SAWADEEXML,
    AFFILIATION_SOURCE_SILVERDOORAPARTMENTS,
    AFFILIATION_SOURCE_SIMPLEBOOKING,
    AFFILIATION_SOURCE_SIMPLOTEL,
    AFFILIATION_SOURCE_SITU,
    AFFILIATION_SOURCE_SPEEDYBOOKER,
    AFFILIATION_SOURCE_STAAH,
    AFFILIATION_SOURCE_SUNHOTELS,
    AFFILIATION_SOURCE_SYNXIS,
    AFFILIATION_SOURCE_TABLETHOTELS,
    AFFILIATION_SOURCE_TBO,
    AFFILIATION_SOURCE_THEBUKING,
    AFFILIATION_SOURCE_TIKET,
    AFFILIATION_SOURCE_TIKITOUR,
    AFFILIATION_SOURCE_TOMAS,
    AFFILIATION_SOURCE_TOURPLAN,
    AFFILIATION_SOURCE_TRAVCO,
    AFFILIATION_SOURCE_TRAVELANIUM,
    AFFILIATION_SOURCE_TRAVELCLICK,
    AFFILIATION_SOURCE_TRAVELGURU,
    AFFILIATION_SOURCE_TRAVELOCITY,
    AFFILIATION_SOURCE_TRAVELOKA,
    AFFILIATION_SOURCE_TRAVELPORT,
    AFFILIATION_SOURCE_TRAVELSTAYNETWORKXML,
    AFFILIATION_SOURCE_TRAVEPIC,
    AFFILIATION_SOURCE_TRIPADVISOR,
    AFFILIATION_SOURCE_TRIPFACTORY,
    AFFILIATION_SOURCE_TRIPJACK,
    AFFILIATION_SOURCE_TXGB,
    AFFILIATION_SOURCE_VIAXML, AFFILIATION_SOURCE_VRBO, AFFILIATION_SOURCE_WEBHOTELIER, AFFILIATION_SOURCE_WEBROOMS
} = require("../constants/CMSUConstants.js");

const affiliationSourceIcon = (source) => {

    const iconMappings = {
        [AFFILIATION_SOURCE_AGODAYCS] : require('../assets/MarketChannelLogos/AGODA.svg').default,
        [AFFILIATION_SOURCE_AIRBNB] : require('../assets/MarketChannelLogos/AIRBNB.svg').default,
        // [AFFILIATION_SOURCE_ALTOVITA] :
        // [AFFILIATION_SOURCE_AOT] :
        // [AFFILIATION_SOURCE_BAKUUN] :
        // [AFFILIATION_SOURCE_APARTMENTSONLINE] :
        // [AFFILIATION_SOURCE_BEDBANK] :
        // [AFFILIATION_SOURCE_BELHOTEL] :
        // [AFFILIATION_SOURCE_BOOKEASY] :
        // [AFFILIATION_SOURCE_BOOKIT] :
        // [AFFILIATION_SOURCE_BOOKINGDIRECT] :
        // [AFFILIATION_SOURCE_BOOKINGEYE] : _BOOKINGEYE
        // [AFFILIATION_SOURCE_BOOKNPAYXML] : _BOOKNPAY
        // [AFFILIATION_SOURCE_CAMPINGVISION] : _CAMPING
        [AFFILIATION_SOURCE_CTRIP] : require('../assets/MarketChannelLogos/CTRIP.svg').default,
        [AFFILIATION_SOURCE_DESPEGAR] : require('../assets/MarketChannelLogos/DESPEGAR.svg').default,
        // [AFFILIATION_SOURCE_DNATA] :
        // [AFFILIATION_SOURCE_DORMS] :
        [AFFILIATION_SOURCE_DOTW] : require('../assets/MarketChannelLogos/DOTW.svg').default,
        [AFFILIATION_SOURCE_EASEMYTRIP] : require('../assets/MarketChannelLogos/EASE_MY_TRIP.svg').default,
        // [AFFILIATION_SOURCE_ENTERTAINMENT] :
        [AFFILIATION_SOURCE_EXPEDIA] : require('../assets/MarketChannelLogos/EXPEDIA.svg').default,
        // [AFFILIATION_SOURCE_TIKITOUR] :
        // [AFFILIATION_SOURCE_EZTRAVEL] :
        // [AFFILIATION_SOURCE_FASTBOOKING] :
        // [AFFILIATION_SOURCE_FINDBULOUS] :
        // [AFFILIATION_SOURCE_GETROOM] : GETR
        // [AFFILIATION_SOURCE_GETYOURWEB] :GETYOU
        [AFFILIATION_SOURCE_GOIBIBO] :require('../assets/MarketChannelLogos/GOIBIBO.svg').default,
        [AFFILIATION_SOURCE_GOOGLE] : require('../assets/MarketChannelLogos/GOOGLE.svg').default,
        // [AFFILIATION_SOURCE_GRABROOMS] : _GRABR
        [AFFILIATION_SOURCE_HAPPYEASYGO] : require('../assets/MarketChannelLogos/HAPPY_EASY_GO.svg').default,
        // [AFFILIATION_SOURCE_HOSTELSCLUB] :
        [AFFILIATION_SOURCE_HOSTELWORLD] : require('../assets/MarketChannelLogos/HOSTEL_WORLD.svg').default,
        [AFFILIATION_SOURCE_HOTELBEDS] : require('../assets/MarketChannelLogos/HOTELS_BED.svg').default,
        // [AFFILIATION_SOURCE_HOTELBONANZA] : _HOTEL
        // [AFFILIATION_SOURCE_HOTELNETWORK] : _HOTEL
        // [AFFILIATION_SOURCE_HOTELTONIGHT] : HOTEL_TO
        // [AFFILIATION_SOURCE_HOTELSCOMBINED] : HOTELS_COM
        // [AFFILIATION_SOURCE_HOO] : _HOO
        // [AFFILIATION_SOURCE_HOOROO] : HOOROO
        // [AFFILIATION_SOURCE_HOTERIP] : _HOTER
        // [AFFILIATION_SOURCE_HOTUSA] : _HOTUS
        // [AFFILIATION_SOURCE_HOTWIRE] : _HOTWIR
        [AFFILIATION_SOURCE_HRS] : require('../assets/MarketChannelLogos/HRS.svg').default,
        // [AFFILIATION_SOURCE_HYPERGUEST] : _HYPER
        // [AFFILIATION_SOURCE_ICHONOZ] : _ICHO
        // [AFFILIATION_SOURCE_IESCAPE] :
        // [AFFILIATION_SOURCE_INSTANTMIGRATION] : _INSTAN
        [AFFILIATION_SOURCE_IRCTC] : require('../assets/MarketChannelLogos/IRCTC.svg').default,
        // [AFFILIATION_SOURCE_KLIKHOTEL] : _KLI
        [AFFILIATION_SOURCE_LIDO] : require('../assets/MarketChannelLogos/UNION_LIDO.svg').default,
        // [AFFILIATION_SOURCE_MAX] : _MAX
        // [AFFILIATION_SOURCE_METACHANNEL] : _METACHA
        // [AFFILIATION_SOURCE_MIDDLEEASTHOTEL] : _MIDDLE
        // [AFFILIATION_SOURCE_MITCHELLCORP] : _MIT
        [AFFILIATION_SOURCE_MRANDMRSSMITH] : require('../assets/MarketChannelLogos/MR_AND_MRS_SMITH.svg').default,
        // [AFFILIATION_SOURCE_MYBOOKINGS] : _MY_
        // [AFFILIATION_SOURCE_NEEDITNOW] : _NEED_
        // [AFFILIATION_SOURCE_NEORCHA] : _NEORC
        // [AFFILIATION_SOURCE_NETROOMZ] : _NET
        // [AFFILIATION_SOURCE_NOT1NIGHT] : _NOT_
        // [AFFILIATION_SOURCE_ODIGEO] : _OD
        // [AFFILIATION_SOURCE_OFFPEAKLUXURY] : _OFF
        // [AFFILIATION_SOURCE_OMNIHOTELIER] : _OMNIH
        // [AFFILIATION_SOURCE_ONEFINERATE] : _ONEFINE
        [AFFILIATION_SOURCE_OSTROVOK] : require('../assets/MarketChannelLogos/OSTROVOK.svg').default,
        // [AFFILIATION_SOURCE_PANPACIFIC] : _PA
        [AFFILIATION_SOURCE_PEGIPEGI] : require('../assets/MarketChannelLogos/PEGIPEGI.svg').default,
        // [AFFILIATION_SOURCE_PELICAN] : _PELI
        // [AFFILIATION_SOURCE_PRESTIGIA] : _PREST
        // [AFFILIATION_SOURCE_QUICKBEDS] : _QUI
        [AFFILIATION_SOURCE_RAKUTEN] : require('../assets/MarketChannelLogos/RAKUTEN.svg').default,
        // [AFFILIATION_SOURCE_RECONLINE] : RCEO
        // [AFFILIATION_SOURCE_RESERVHOTEL] : _RES
        // [AFFILIATION_SOURCE_ROIBACK] : _RO
        [AFFILIATION_SOURCE_SAFFRONSTAYS] : require('../assets/MarketChannelLogos/SAFFRON_STAYS.svg').default,
        // [AFFILIATION_SOURCE_SAWADEEXML] : _SA
        // [AFFILIATION_SOURCE_SIMPLEBOOKING] : SIMPLE
        // [AFFILIATION_SOURCE_SILVERDOORAPARTMENTS] : _SILVER
        // [AFFILIATION_SOURCE_SPEEDYBOOKER] : _SPEED
        // [AFFILIATION_SOURCE_SITU] : _SI
        // [AFFILIATION_SOURCE_STAAH] : _STA
        // [AFFILIATION_SOURCE_SUNHOTELS] : _SUN
        [AFFILIATION_SOURCE_SYNXIS] : require('../assets/MarketChannelLogos/BE_SYNXIS_COM.svg').default,
        // [AFFILIATION_SOURCE_TABLETHOTELS] : _TA
        // [AFFILIATION_SOURCE_TBO] : _TBO
        // [AFFILIATION_SOURCE_FIVEPM] : _FIVE
        // [AFFILIATION_SOURCE_THEBUKING] : _THEBU
        // [AFFILIATION_SOURCE_TIKET] : _TI
        // [AFFILIATION_SOURCE_TOMAS] : _TOM
        [AFFILIATION_SOURCE_SIMPLOTEL] : require('../assets/MarketChannelLogos/SIMPLOTEL.svg').default,
        // [AFFILIATION_SOURCE_TOURPLAN] : _TOUR
        // [AFFILIATION_SOURCE_TRAVCO] : _TRA
        [AFFILIATION_SOURCE_TRAVELCLICK] : require('../assets/MarketChannelLogos/TRAVEL_CLICK.svg').default,
        // [AFFILIATION_SOURCE_TRAVELANIUM] : _TRAVELAN
        [AFFILIATION_SOURCE_TRAVELGURU] : require('../assets/MarketChannelLogos/TRAVELGURU.svg').default,
        [AFFILIATION_SOURCE_TRAVELOKA] : require('../assets/MarketChannelLogos/TRAVELOKA.svg').default,
        // [AFFILIATION_SOURCE_TRAVELPORT] : _TRAVEL
        [AFFILIATION_SOURCE_TRAVELOCITY] : require('../assets/MarketChannelLogos/TRAVELOCITY.svg').default,
        // [AFFILIATION_SOURCE_TRAVELSTAYNETWORKXML] : _TRAVEL_ST
        // [AFFILIATION_SOURCE_TRAVEPIC] : _TRAVEP
        [AFFILIATION_SOURCE_TRIPADVISOR] : require('../assets/MarketChannelLogos/TRIPADVISOR.svg').default,
        // [AFFILIATION_SOURCE_TXGB] : _TXG
        // [AFFILIATION_SOURCE_VIAXML] : _VIA
        // [AFFILIATION_SOURCE_TRIPFACTORY] : _TRIPFAC
        // [AFFILIATION_SOURCE_TRIPJACK] : _TRIPJ
        // [AFFILIATION_SOURCE_VRBO] :
        [AFFILIATION_SOURCE_WEBHOTELIER] : require('../assets/MarketChannelLogos/WEBHOTELIER.svg').default,
        // [AFFILIATION_SOURCE_WEBROOMS] : _WEBRO
        'NO_IMAGE_FOUND': require('../assets/MarketChannelLogos/NO_IMAGE_FOUND.svg').default
    }

    return iconMappings[source] || iconMappings['NO_IMAGE_FOUND']
}

module.exports = affiliationSourceIcon
