import {
    AFFILIATION_SOURCE_AGODAYCS,
    AFFILIATION_SOURCE_AIRBNB,
    AFFILIATION_SOURCE_ALTOVITA,
    AFFILIATION_SOURCE_AOT,
    AFFILIATION_SOURCE_APARTMENTSONLINE,
    AFFILIATION_SOURCE_BAKUUN,
    AFFILIATION_SOURCE_BEDBANK,
    AFFILIATION_SOURCE_BELHOTEL,
    AFFILIATION_SOURCE_BOOKEASY,
    AFFILIATION_SOURCE_BOOKINGDIRECT,
    AFFILIATION_SOURCE_BOOKINGEYE,
    AFFILIATION_SOURCE_BOOKIT,
    AFFILIATION_SOURCE_BOOKNPAYXML,
    AFFILIATION_SOURCE_CAMPINGVISION,
    AFFILIATION_SOURCE_CTRIP,
    AFFILIATION_SOURCE_DESPEGAR,
    AFFILIATION_SOURCE_DNATA,
    AFFILIATION_SOURCE_DORMS,
    AFFILIATION_SOURCE_DOTW,
    AFFILIATION_SOURCE_EASEMYTRIP,
    AFFILIATION_SOURCE_ENTERTAINMENT,
    AFFILIATION_SOURCE_EXPEDIA,
    AFFILIATION_SOURCE_EZTRAVEL,
    AFFILIATION_SOURCE_FASTBOOKING,
    AFFILIATION_SOURCE_FINDBULOUS,
    AFFILIATION_SOURCE_FIVEPM,
    AFFILIATION_SOURCE_GETROOM,
    AFFILIATION_SOURCE_GETYOURWEB,
    AFFILIATION_SOURCE_GOIBIBO,
    AFFILIATION_SOURCE_GOOGLE,
    AFFILIATION_SOURCE_GRABROOMS,
    AFFILIATION_SOURCE_HAPPYEASYGO,
    AFFILIATION_SOURCE_HOO,
    AFFILIATION_SOURCE_HOOROO,
    AFFILIATION_SOURCE_HOSTELSCLUB,
    AFFILIATION_SOURCE_HOSTELWORLD,
    AFFILIATION_SOURCE_HOTELBEDS,
    AFFILIATION_SOURCE_HOTELBONANZA,
    AFFILIATION_SOURCE_HOTELNETWORK,
    AFFILIATION_SOURCE_HOTELSCOMBINED,
    AFFILIATION_SOURCE_HOTELTONIGHT,
    AFFILIATION_SOURCE_HOTERIP,
    AFFILIATION_SOURCE_HOTUSA,
    AFFILIATION_SOURCE_HOTWIRE,
    AFFILIATION_SOURCE_HRS,
    AFFILIATION_SOURCE_HYPERGUEST,
    AFFILIATION_SOURCE_ICHONOZ,
    AFFILIATION_SOURCE_IESCAPE,
    AFFILIATION_SOURCE_INSTANTMIGRATION,
    AFFILIATION_SOURCE_IRCTC,
    AFFILIATION_SOURCE_KLIKHOTEL,
    AFFILIATION_SOURCE_LIDO,
    AFFILIATION_SOURCE_MAX,
    AFFILIATION_SOURCE_METACHANNEL,
    AFFILIATION_SOURCE_MIDDLEEASTHOTEL,
    AFFILIATION_SOURCE_MITCHELLCORP,
    AFFILIATION_SOURCE_MRANDMRSSMITH,
    AFFILIATION_SOURCE_MYBOOKINGS,
    AFFILIATION_SOURCE_NEEDITNOW,
    AFFILIATION_SOURCE_NEORCHA,
    AFFILIATION_SOURCE_NETROOMZ,
    AFFILIATION_SOURCE_NOT1NIGHT,
    AFFILIATION_SOURCE_ODIGEO,
    AFFILIATION_SOURCE_OFFPEAKLUXURY,
    AFFILIATION_SOURCE_OMNIHOTELIER,
    AFFILIATION_SOURCE_ONEFINERATE,
    AFFILIATION_SOURCE_OSTROVOK,
    AFFILIATION_SOURCE_PANPACIFIC,
    AFFILIATION_SOURCE_PEGIPEGI,
    AFFILIATION_SOURCE_PELICAN,
    AFFILIATION_SOURCE_PRESTIGIA,
    AFFILIATION_SOURCE_QUICKBEDS,
    AFFILIATION_SOURCE_RAKUTEN,
    AFFILIATION_SOURCE_RECONLINE,
    AFFILIATION_SOURCE_RESERVHOTEL,
    AFFILIATION_SOURCE_ROIBACK,
    AFFILIATION_SOURCE_SAFFRONSTAYS,
    AFFILIATION_SOURCE_SAWADEEXML,
    AFFILIATION_SOURCE_SILVERDOORAPARTMENTS,
    AFFILIATION_SOURCE_SIMPLEBOOKING,
    AFFILIATION_SOURCE_SIMPLOTEL,
    AFFILIATION_SOURCE_SITU,
    AFFILIATION_SOURCE_SPEEDYBOOKER,
    AFFILIATION_SOURCE_STAAH,
    AFFILIATION_SOURCE_SUNHOTELS,
    AFFILIATION_SOURCE_SYNXIS,
    AFFILIATION_SOURCE_TABLETHOTELS,
    AFFILIATION_SOURCE_TBO,
    AFFILIATION_SOURCE_THEBUKING,
    AFFILIATION_SOURCE_TIKET,
    AFFILIATION_SOURCE_TIKITOUR,
    AFFILIATION_SOURCE_TOMAS,
    AFFILIATION_SOURCE_TOURPLAN,
    AFFILIATION_SOURCE_TRAVCO,
    AFFILIATION_SOURCE_TRAVELANIUM,
    AFFILIATION_SOURCE_TRAVELCLICK,
    AFFILIATION_SOURCE_TRAVELGURU,
    AFFILIATION_SOURCE_TRAVELOCITY,
    AFFILIATION_SOURCE_TRAVELOKA,
    AFFILIATION_SOURCE_TRAVELPORT,
    AFFILIATION_SOURCE_TRAVELSTAYNETWORKXML,
    AFFILIATION_SOURCE_TRAVEPIC,
    AFFILIATION_SOURCE_TRIPADVISOR,
    AFFILIATION_SOURCE_TRIPFACTORY,
    AFFILIATION_SOURCE_TRIPJACK,
    AFFILIATION_SOURCE_TXGB,
    AFFILIATION_SOURCE_VIAXML, AFFILIATION_SOURCE_VRBO, AFFILIATION_SOURCE_WEBHOTELIER, AFFILIATION_SOURCE_WEBROOMS
} from "../../constants/CMSUConstants.js";
import {
    _AGODA,
    _AIRBNB, _BE_SYNXIS_COM,
    _CTRIP,
    _DESPEGAR,
    _DOTW,
    _EASE_MY_TRIP,
    _EXPEDIA,
    _GOIBIBO,
    _GOOGLE,
    _HAPPY_EASY_GO,
    _HOSTEL_WORLD,
    _HOTELS_BED,
    _HRS,
    _IRCTC,
    _MR_AND_MRS_SMITH,
    _OSTROVOK,
    _PEGIPEGI,
    _RAKUTEN, _SAFFRON_STAYS, _SIMPLOTEL, _TRAVEL_CLICK, _TRAVELGURU, _TRAVELOCITY, _TRAVELOKA, _TRIPADVISOR,
    _UNION_LIDO, _WEBHOTELIER
} from "../LogoImports.js";

export const affiliationSourceIconMapping = {
    [AFFILIATION_SOURCE_AGODAYCS] : _AGODA,
    [AFFILIATION_SOURCE_AIRBNB] : _AIRBNB,
    // [AFFILIATION_SOURCE_ALTOVITA] :
    // [AFFILIATION_SOURCE_AOT] :
    // [AFFILIATION_SOURCE_BAKUUN] :
    // [AFFILIATION_SOURCE_APARTMENTSONLINE] :
    // [AFFILIATION_SOURCE_BEDBANK] :
    // [AFFILIATION_SOURCE_BELHOTEL] :
    // [AFFILIATION_SOURCE_BOOKEASY] :
    // [AFFILIATION_SOURCE_BOOKIT] :
    // [AFFILIATION_SOURCE_BOOKINGDIRECT] :
    // [AFFILIATION_SOURCE_BOOKINGEYE] : _BOOKINGEYE
    // [AFFILIATION_SOURCE_BOOKNPAYXML] : _BOOKNPAY
    // [AFFILIATION_SOURCE_CAMPINGVISION] : _CAMPING
    [AFFILIATION_SOURCE_CTRIP] : _CTRIP,
    [AFFILIATION_SOURCE_DESPEGAR] : _DESPEGAR,
    // [AFFILIATION_SOURCE_DNATA] :
    // [AFFILIATION_SOURCE_DORMS] :
    [AFFILIATION_SOURCE_DOTW] : _DOTW,
    [AFFILIATION_SOURCE_EASEMYTRIP] : _EASE_MY_TRIP,
    // [AFFILIATION_SOURCE_ENTERTAINMENT] :
    [AFFILIATION_SOURCE_EXPEDIA] : _EXPEDIA,
    // [AFFILIATION_SOURCE_TIKITOUR] :
    // [AFFILIATION_SOURCE_EZTRAVEL] :
    // [AFFILIATION_SOURCE_FASTBOOKING] :
    // [AFFILIATION_SOURCE_FINDBULOUS] :
    // [AFFILIATION_SOURCE_GETROOM] : GETR
    // [AFFILIATION_SOURCE_GETYOURWEB] :GETYOU
    [AFFILIATION_SOURCE_GOIBIBO] :_GOIBIBO,
    [AFFILIATION_SOURCE_GOOGLE] : _GOOGLE,
    // [AFFILIATION_SOURCE_GRABROOMS] : _GRABR
    [AFFILIATION_SOURCE_HAPPYEASYGO] : _HAPPY_EASY_GO,
    // [AFFILIATION_SOURCE_HOSTELSCLUB] :
    [AFFILIATION_SOURCE_HOSTELWORLD] : _HOSTEL_WORLD,
    [AFFILIATION_SOURCE_HOTELBEDS] : _HOTELS_BED,
    // [AFFILIATION_SOURCE_HOTELBONANZA] : _HOTEL
    // [AFFILIATION_SOURCE_HOTELNETWORK] : _HOTEL
    // [AFFILIATION_SOURCE_HOTELTONIGHT] : HOTEL_TO
    // [AFFILIATION_SOURCE_HOTELSCOMBINED] : HOTELS_COM
    // [AFFILIATION_SOURCE_HOO] : _HOO
    // [AFFILIATION_SOURCE_HOOROO] : HOOROO
    // [AFFILIATION_SOURCE_HOTERIP] : _HOTER
    // [AFFILIATION_SOURCE_HOTUSA] : _HOTUS
    // [AFFILIATION_SOURCE_HOTWIRE] : _HOTWIR
    [AFFILIATION_SOURCE_HRS] : _HRS,
    // [AFFILIATION_SOURCE_HYPERGUEST] : _HYPER
    // [AFFILIATION_SOURCE_ICHONOZ] : _ICHO
    // [AFFILIATION_SOURCE_IESCAPE] :
    // [AFFILIATION_SOURCE_INSTANTMIGRATION] : _INSTAN
    [AFFILIATION_SOURCE_IRCTC] : _IRCTC,
    // [AFFILIATION_SOURCE_KLIKHOTEL] : _KLI
    [AFFILIATION_SOURCE_LIDO] : _UNION_LIDO,
    // [AFFILIATION_SOURCE_MAX] : _MAX
    // [AFFILIATION_SOURCE_METACHANNEL] : _METACHA
    // [AFFILIATION_SOURCE_MIDDLEEASTHOTEL] : _MIDDLE
    // [AFFILIATION_SOURCE_MITCHELLCORP] : _MIT
    [AFFILIATION_SOURCE_MRANDMRSSMITH] : _MR_AND_MRS_SMITH,
    // [AFFILIATION_SOURCE_MYBOOKINGS] : _MY_
    // [AFFILIATION_SOURCE_NEEDITNOW] : _NEED_
    // [AFFILIATION_SOURCE_NEORCHA] : _NEORC
    // [AFFILIATION_SOURCE_NETROOMZ] : _NET
    // [AFFILIATION_SOURCE_NOT1NIGHT] : _NOT_
    // [AFFILIATION_SOURCE_ODIGEO] : _OD
    // [AFFILIATION_SOURCE_OFFPEAKLUXURY] : _OFF
    // [AFFILIATION_SOURCE_OMNIHOTELIER] : _OMNIH
    // [AFFILIATION_SOURCE_ONEFINERATE] : _ONEFINE
    [AFFILIATION_SOURCE_OSTROVOK] : _OSTROVOK,
    // [AFFILIATION_SOURCE_PANPACIFIC] : _PA
    [AFFILIATION_SOURCE_PEGIPEGI] : _PEGIPEGI,
    // [AFFILIATION_SOURCE_PELICAN] : _PELI
    // [AFFILIATION_SOURCE_PRESTIGIA] : _PREST
    // [AFFILIATION_SOURCE_QUICKBEDS] : _QUI
    [AFFILIATION_SOURCE_RAKUTEN] : _RAKUTEN,
    // [AFFILIATION_SOURCE_RECONLINE] : RCEO
    // [AFFILIATION_SOURCE_RESERVHOTEL] : _RES
    // [AFFILIATION_SOURCE_ROIBACK] : _RO
    [AFFILIATION_SOURCE_SAFFRONSTAYS] : _SAFFRON_STAYS,
    // [AFFILIATION_SOURCE_SAWADEEXML] : _SA
    // [AFFILIATION_SOURCE_SIMPLEBOOKING] : SIMPLE
    // [AFFILIATION_SOURCE_SILVERDOORAPARTMENTS] : _SILVER
    // [AFFILIATION_SOURCE_SPEEDYBOOKER] : _SPEED
    // [AFFILIATION_SOURCE_SITU] : _SI
    // [AFFILIATION_SOURCE_STAAH] : _STA
    // [AFFILIATION_SOURCE_SUNHOTELS] : _SUN
    [AFFILIATION_SOURCE_SYNXIS] : _BE_SYNXIS_COM,
    // [AFFILIATION_SOURCE_TABLETHOTELS] : _TA
    // [AFFILIATION_SOURCE_TBO] : _TBO
    // [AFFILIATION_SOURCE_FIVEPM] : _FIVE
    // [AFFILIATION_SOURCE_THEBUKING] : _THEBU
    // [AFFILIATION_SOURCE_TIKET] : _TI
    // [AFFILIATION_SOURCE_TOMAS] : _TOM
    [AFFILIATION_SOURCE_SIMPLOTEL] : _SIMPLOTEL,
    // [AFFILIATION_SOURCE_TOURPLAN] : _TOUR
    // [AFFILIATION_SOURCE_TRAVCO] : _TRA
    [AFFILIATION_SOURCE_TRAVELCLICK] : _TRAVEL_CLICK,
    // [AFFILIATION_SOURCE_TRAVELANIUM] : _TRAVELAN
    [AFFILIATION_SOURCE_TRAVELGURU] : _TRAVELGURU,
    [AFFILIATION_SOURCE_TRAVELOKA] : _TRAVELOKA,
    // [AFFILIATION_SOURCE_TRAVELPORT] : _TRAVEL
    [AFFILIATION_SOURCE_TRAVELOCITY] : _TRAVELOCITY,
    // [AFFILIATION_SOURCE_TRAVELSTAYNETWORKXML] : _TRAVEL_ST
    // [AFFILIATION_SOURCE_TRAVEPIC] : _TRAVEP
    [AFFILIATION_SOURCE_TRIPADVISOR] : _TRIPADVISOR,
    // [AFFILIATION_SOURCE_TXGB] : _TXG
    // [AFFILIATION_SOURCE_VIAXML] : _VIA
    // [AFFILIATION_SOURCE_TRIPFACTORY] : _TRIPFAC
    // [AFFILIATION_SOURCE_TRIPJACK] : _TRIPJ
    // [AFFILIATION_SOURCE_VRBO] :
    [AFFILIATION_SOURCE_WEBHOTELIER] : _WEBHOTELIER,
    // [AFFILIATION_SOURCE_WEBROOMS] : _WEBRO
}